import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useInventory } from '../../context/InventoryContext.jsx'
import { can } from '../../lib/permissions.js'
import { Badge, Button, Card, EmptyState, Field, FilterBar, LoadingSkeleton, Modal, PageHeader, SearchInput, Select } from '../../components/ui.jsx'
import ServerTable from '../../components/ServerTable.jsx'
import * as api from '../../services/assetService.js'
import { listReturns as listSupplierReturns } from '../../services/supplierReturnService.js'

const text = (key, label, value = '', required = true) => ({ key, label, value, required })
const choices = (key, label, options, value = '', required = true) => ({ key, label, options, value, required })
const evidence = text('notes', 'Action evidence / notes')
const date = value => value ? new Date(value).toLocaleString() : 'Unknown'
const av = row => ({ expectedUpdatedAt: row.updatedAt })
const mv = (row, asset) => ({ expectedUpdatedAt: row.updatedAt, expectedAssetUpdatedAt: asset.updatedAt })

function useRemote(load, deps) {
  const [value, setValue] = useState(null), [error, setError] = useState(''), [retry, setRetry] = useState(0)
  useEffect(() => { setValue(null) }, deps)
  useEffect(() => { let active = true; setError(''); load().then(r => { if (active) setValue(r) }).catch(e => { if (active) setError(e.message) }); return () => { active = false } }, [...deps, retry])
  return { value, error, reload: () => setRetry(r => r + 1) }
}
function Unavailable({ error, reload }) { return error ? <Card><EmptyState title="Record unavailable" description={error} action={<Button onClick={reload}>Retry</Button>}/></Card> : <LoadingSkeleton/> }
function WorkflowForm({ title, description, fields = [], submit, reload, close }) {
  const [values, setValues] = useState(() => Object.fromEntries(fields.map(f => [f.key, f.value ?? '']))), [pending, setPending] = useState(false), [error, setError] = useState('')
  const set = (key, value) => setValues(v => ({ ...v, [key]: value }))
  async function save(e) { e.preventDefault(); setPending(true); setError(''); try { await submit(values); close() } catch (e) { setError(e.errors?.[0]?.message || e.message) } finally { setPending(false) } }
  async function refresh() { setPending(true); try { await reload(); setError('') } catch (e) { setError(e.message) } finally { setPending(false) } }
  return <Modal open onOpenChange={v => { if (!v && !pending) close() }} title={title} description={description}><form className="space-y-4" onSubmit={save}>{fields.map(f => <Field key={f.key} label={f.label} required={f.required}>{f.options ? <Select required={f.required} aria-label={f.label} value={values[f.key]} onChange={v => set(f.key, v)} options={f.options} placeholder="Choose"/> : f.type === 'date' ? <input required={f.required} aria-label={f.label} type="date" className="field" value={values[f.key]} onInput={e => set(f.key, e.currentTarget.value)} onChange={e => set(f.key, e.currentTarget.value)}/> : f.type === 'number' ? <input required={f.required} aria-label={f.label} type="number" min={f.min ?? 0} max={f.max} step={f.step || 1} className="field" value={values[f.key]} onChange={e => set(f.key, e.target.value)}/> : <textarea required={f.required} aria-label={f.label} className="field min-h-20" minLength={f.required ? 2 : undefined} maxLength={4000} value={values[f.key]} onChange={e => set(f.key, e.target.value)}/>}</Field>)}{error && <p role="alert" className="text-sm text-rose-600">{error}</p>}<div className="flex flex-wrap gap-2"><Button type="submit" loading={pending}>Confirm {title.toLowerCase()}</Button>{reload && <Button type="button" variant="secondary" disabled={pending} onClick={refresh}>Reload current record</Button>}<Button type="button" variant="secondary" disabled={pending} onClick={close}>Cancel</Button></div></form></Modal>
}
const planFields = row => [text('title', 'Plan title', row?.title), text('instructions', 'Service instructions', row?.instructions), { ...text('intervalDays', 'Interval in days', row?.intervalDays || 30), type: 'number', min: 1, max: 3650 }, { ...text('nextDueAt', 'Next due date (UTC)', row?.nextDueAt?.slice(0, 10) || new Date().toISOString().slice(0, 10)), type: 'date' }]
const serviceFields = [text('issue', 'Service issue'), text('technician', 'Technician', '', false), { ...text('cost', 'Estimated cost', 0), type: 'number', step: '.01' }, { ...text('serviceDate', 'Service date (UTC)', new Date().toISOString().slice(0, 10)), type: 'date' }]

export function AssetDetail() {
  const { id } = useParams(), { user, notify, refreshData } = useInventory(), remote = useRemote(() => api.getAsset(id), [id]), [action, setAction] = useState(null)
  const row = remote.value?.data, assignment = row?.assignments.find(a => a.status === 'ACTIVE')
  if (!row) return <Unavailable {...remote}/>
  const open = kind => setAction({ kind, asset: row, assignment })
  const reload = async () => { const r = await api.getAsset(id); setAction(a => ({ ...a, asset: r.data, assignment: r.data.assignments.find(r => r.status === 'ACTIVE') })); remote.reload() }
  const custodyFields = [text('assignedTo', 'Custodian name'), text('department', 'Department', '', false), text('location', 'Custody location', '', false), text('conditionOnAssign', 'Condition on issue'), evidence]
  const fields = action?.kind === 'assign' ? custodyFields : action?.kind === 'handover' ? [...custodyFields, text('conditionOnReturn', 'Previous custodian return inspection')] : action?.kind === 'return' ? [text('conditionOnReturn', 'Return inspection'), choices('disposition', 'Inspected disposition', ['AVAILABLE', 'QUARANTINE'], 'QUARANTINE'), evidence] : action?.kind === 'maintenance' ? serviceFields : action?.kind === 'plan' ? planFields() : [evidence]
  async function submit(values) {
    if (action.kind === 'maintenance') await api.createMaintenance({ ...values, assetId: id, expectedAssetUpdatedAt: action.asset.updatedAt, status: 'SCHEDULED' })
    else if (action.kind === 'plan') await api.createPlan({ ...values, assetId: id, expectedAssetUpdatedAt: action.asset.updatedAt })
    else await api.assetAction(id, action.kind, { ...values, ...av(action.asset), ...(['return', 'handover'].includes(action.kind) ? { expectedAssignmentUpdatedAt: action.assignment?.updatedAt } : {}) })
    notify('Asset action recorded.'); remote.reload(); await refreshData()
  }
  return <><PageHeader eyebrow="Asset custody" title={row.assetTag} subtitle={`${row.product.name} · ${row.serialNumber?.serialNumber || 'Unserialized asset'}`}/><Card className="mb-4 space-y-3 p-5"><div className="flex flex-wrap gap-3"><Badge>{row.status}</Badge><span>{row.warehouse?.name || 'Unknown legacy owner'}</span><span>Custodian: {assignment?.assignedTo || 'Unassigned'}</span></div><p className="text-sm subtle">Company assets are outside warehouse stock. Returning custody and recording warranty outcomes do not replenish inventory. {row.historyNotice}</p><div className="flex flex-wrap gap-2">{can(user, 'assets.EDIT') && <>{row.status === 'AVAILABLE' && !assignment && <Button onClick={() => open('assign')}>Assign custody</Button>}{row.status === 'ASSIGNED' && assignment && <Button onClick={() => open('handover')}>Hand over custody</Button>}{assignment && ['ASSIGNED', 'QUARANTINE'].includes(row.status) && <Button onClick={() => open('return')}>Return custody</Button>}{row.status === 'QUARANTINE' && <Button onClick={() => open('inspect')}>Inspect and release</Button>}{!assignment && ['AVAILABLE', 'QUARANTINE'].includes(row.status) && <Button variant="secondary" onClick={() => open('retire')}>Retire asset</Button>}</>}{can(user, 'assets.DELETE') && !assignment && ['AVAILABLE', 'QUARANTINE'].includes(row.status) && <Button variant="secondary" onClick={() => open('dispose')}>Dispose asset</Button>}{can(user, 'assets.CREATE') && !['RETIRED', 'DISPOSED', 'LOST'].includes(row.status) && <><Button variant="secondary" onClick={() => open('maintenance')}>Schedule corrective service</Button><Button variant="secondary" onClick={() => open('plan')}>Create preventive plan</Button></>}{can(user, 'warranty_claims.VIEW') && <Link className="text-brand-600" to="/assets/warranty-claims">Warranty claims</Link>}</div></Card>
  <Card className="mb-4 p-5"><h2 className="mb-3 font-bold">Custody history</h2>{row.assignments.length ? row.assignments.map(a => <div key={a.id} className="border-t divider py-3 text-sm"><strong>{a.assignedTo}</strong> · {a.department || 'No department'} · {a.status}<p className="text-xs subtle">Issued {date(a.assignedDate)}{a.returnedDate && ` · Returned ${date(a.returnedDate)}`}</p><p>Issue: {a.conditionOnAssign || 'Unrecorded'} · {a.notes || 'No issue notes'}</p>{a.returnedDate && <p>Return: {a.conditionOnReturn || 'Unrecorded'} · {a.returnNotes || 'No return notes'}</p>}</div>) : <p className="text-sm subtle">No recorded custody.</p>}</Card>
  <Card className="mb-4 p-5"><h2 className="mb-3 font-bold">Service documents</h2><Link className="mr-4 text-brand-600" to="/assets/maintenance">Maintenance records</Link><Link className="text-brand-600" to="/assets/preventive-maintenance">Preventive plans</Link>{row.maintenanceRecords.map(r => <p className="mt-3 text-sm" key={r.id}>{r.kind} · {r.issue} · {r.status} · {r.inspectionResult || 'Awaiting inspection'}</p>)}</Card>
  <Card className="p-5"><h2 className="mb-3 font-bold">Recorded activity</h2>{row.events.length ? row.events.map(e => <div key={e.id} className="border-t divider py-3 text-sm"><strong>{e.type}</strong> · {e.user.firstName} {e.user.lastName}<p>{e.notes}</p><p className="text-xs subtle">{date(e.createdAt)}</p></div>) : <p className="text-sm subtle">No events recorded since installation.</p>}</Card>{action && <WorkflowForm key={action.kind} title={action.kind === 'plan' ? 'Create preventive plan' : action.kind === 'maintenance' ? 'Schedule corrective service' : `${action.kind} asset`} description="Review current custody and inspection. A changed record requires an explicit reload." fields={fields} submit={submit} reload={reload} close={() => setAction(null)}/>}</>
}

export function MaintenanceRecords() {
  const { user, notify, refreshData } = useInventory(), [query, setQuery] = useState({ page: 1, status: '' }), remote = useRemote(() => api.getMaintenance(query), [query]), [action, setAction] = useState(null)
  const fields = action?.kind === 'complete' ? [choices('inspectionResult', 'Final inspection', ['AVAILABLE', 'QUARANTINE'], 'QUARANTINE'), { ...text('cost', 'Actual service cost', action.row.cost), type: 'number', step: '.01' }, evidence] : action?.kind === 'start' ? [text('technician', 'Technician', action.row.technician || '', false), evidence] : [evidence]
  async function submit(v) { const body = { ...v, ...mv(action.row, action.asset) }; if (action.kind === 'start') await api.updateMaintenance(action.row.id, { ...body, status: 'IN_REPAIR' }); else await api.maintenanceAction(action.row.id, action.kind, body); notify('Service action recorded.'); remote.reload(); await refreshData() }
  async function reload() { const r = await api.getMaintenanceRecord(action.row.id); setAction(a => ({ ...a, row: r.data, asset: r.data.asset })); remote.reload() }
  return <><PageHeader eyebrow="Asset Management" title="Maintenance Records" subtitle="Start service explicitly, retain custody, then record a final inspection." actions={<Link to="/assets"><Button variant="secondary">Choose asset to schedule</Button></Link>}/><FilterBar><Select aria-label="Service status" value={query.status} onChange={status => setQuery({ page: 1, status })} options={['SCHEDULED', 'IN_REPAIR', 'COMPLETED', 'CANCELLED']} placeholder="All service states"/><Button variant="secondary" onClick={remote.reload}>Refresh</Button></FilterBar>{!remote.value ? <Unavailable {...remote}/> : <ServerTable rows={remote.value.data} pagination={remote.value.pagination} onPage={page => setQuery(q => ({ ...q, page }))} emptyTitle="No services recorded" columns={[{ key: 'asset', label: 'Asset', render: r => <Link className="text-brand-600" to={`/assets/${r.assetId}`}>{r.asset.assetTag}</Link> }, { key: 'issue', label: 'Service', render: r => <div>{r.issue}<p className="text-xs subtle">{r.kind} · {r.plan?.title || 'Corrective'}</p><p className="text-xs subtle">{r.asset.serialNumber?.serialNumber || 'Unserialized'}</p></div> }, { key: 'serviceDate', label: 'Scheduled', render: r => date(r.serviceDate) }, { key: 'cost', label: 'Cost', render: r => String(r.cost) }, { key: 'status', label: 'State', render: r => <div><Badge>{r.status}</Badge><p className="text-xs">{r.inspectionResult || ''}</p><p className="text-xs subtle">{r.notes}</p></div> }, { key: 'actions', label: 'Actions', render: r => can(user, 'assets.EDIT') && <div className="flex flex-wrap gap-2">{(r.status === 'SCHEDULED' ? ['start', 'cancel'] : r.status === 'IN_REPAIR' ? ['complete', 'cancel'] : []).map(kind => <Button key={kind} size="sm" variant="secondary" onClick={() => setAction({ kind, row: r, asset: r.asset })}>{kind === 'start' ? 'Start service' : kind === 'complete' ? 'Complete service' : 'Cancel service'}</Button>)}</div> }]}/ >}{action && <WorkflowForm key={`${action.kind}-${action.row.id}`} title={`${action.kind} service`} description="Completion advances a preventive plan from the actual completion time. Cancelling repair retains its original hold; unknown legacy state stays quarantined." fields={fields} submit={submit} reload={reload} close={() => setAction(null)}/>}</>
}

export function PreventiveMaintenance() {
  const { user, notify } = useInventory(), [query, setQuery] = useState({ page: 1, due: '' }), remote = useRemote(() => api.getPlans(query), [query]), [action, setAction] = useState(null), [error, setError] = useState('')
  async function open(row, kind) { try { const r = await api.getAsset(row.assetId); setAction({ row, kind, asset: r.data }); setError('') } catch (e) { setError(e.message) } }
  async function reload() { const plans = await api.getPlans({ asset: action.row.assetId, limit: 100 }); const row = plans.data.find(r => r.id === action.row.id); if (!row) throw Error('Plan no longer accessible.'); const a = await api.getAsset(row.assetId); setAction(v => ({ ...v, row, asset: a.data })); remote.reload() }
  async function submit(v) { if (action.kind === 'schedule') await api.schedulePlan(action.row.id, mv(action.row, action.asset)); else await api.updatePlan(action.row.id, { ...av(action.row), ...(action.kind === 'edit' ? v : { status: action.kind === 'pause' ? 'PAUSED' : action.kind === 'resume' ? 'ACTIVE' : 'CANCELLED' }) }); notify('Plan action recorded.'); remote.reload() }
  return <><PageHeader eyebrow="Asset Management" title="Preventive Maintenance" subtitle="Due plans require an explicit service occurrence. Completing it advances the next due date." actions={<Link to="/assets"><Button variant="secondary">Choose asset to create plan</Button></Link>}/><FilterBar><Select aria-label="Plan window" value={query.due} onChange={due => setQuery({ page: 1, due })} options={[{ value: 'true', label: 'Due / overdue active plans' }]} placeholder="All plans"/><Button variant="secondary" onClick={remote.reload}>Refresh</Button></FilterBar>{error && <p role="alert" className="text-rose-600">{error}</p>}{!remote.value ? <Unavailable {...remote}/> : <ServerTable rows={remote.value.data} pagination={remote.value.pagination} onPage={page => setQuery(q => ({ ...q, page }))} emptyTitle="No preventive plans in this window" columns={[{ key: 'title', label: 'Plan', render: r => <div className="min-w-40"><strong>{r.title}</strong><p>{r.instructions}</p><Link className="text-brand-600" to={`/assets/${r.assetId}`}>{r.asset.assetTag}</Link></div> }, { key: 'intervalDays', label: 'Interval', render: r => `${r.intervalDays} days` }, { key: 'nextDueAt', label: 'Next due', render: r => <div>{date(r.nextDueAt)}{r.status === 'ACTIVE' && new Date(r.nextDueAt) <= new Date() && <p className="text-amber-700">Due / overdue</p>}</div> }, { key: 'status', label: 'State', render: r => <div><Badge>{r.status}</Badge><p className="text-xs subtle">{r.records.length ? `Open service: ${r.records[0].status}` : 'No open service'}</p></div> }, { key: 'actions', label: 'Actions', render: r => <div className="flex flex-wrap gap-2">{can(user, 'assets.CREATE') && r.status === 'ACTIVE' && !r.records.length && <Button size="sm" onClick={() => open(r, 'schedule')}>Schedule occurrence</Button>}{can(user, 'assets.EDIT') && r.status !== 'CANCELLED' && ['edit', r.status === 'PAUSED' ? 'resume' : 'pause', 'cancel'].map(kind => <Button key={kind} size="sm" variant="secondary" onClick={() => open(r, kind)}>{kind} plan</Button>)}</div> }]}/ >}{action && <WorkflowForm key={`${action.kind}-${action.row.id}`} title={`${action.kind} plan`} description="Pausing or cancelling a plan retains existing service documents. One record is allowed per due occurrence." fields={action.kind === 'edit' ? planFields(action.row) : []} submit={submit} reload={reload} close={() => setAction(null)}/>}</>
}

export function WarrantyClaims() {
  const { user } = useInventory(), navigate = useNavigate(), [query, setQuery] = useState({ page: 1, search: '', status: '' }), remote = useRemote(() => api.getClaims(query), [query]), [open, setOpen] = useState(false), [selected, setSelected] = useState(null), [search, setSearch] = useState(''), [sourcePage, setSourcePage] = useState(1), sources = useRemote(() => open && search.trim() ? api.getClaimSources({ search, page: sourcePage, limit: 20 }) : Promise.resolve({ data: [] }), [open, search, sourcePage])
  return <><PageHeader eyebrow="Asset Management" title="Warranty Claims" subtitle="Exact serial, supplier and receipt links with explicit supplier decisions." actions={can(user, 'warranty_claims.CREATE') && <Button onClick={() => setOpen(true)}>Create warranty draft</Button>}/><Card className="mb-4 p-4 text-sm subtle">Claims record evidence and supplier outcomes. They do not send messages, release stock holds, replace serial identities, return equipment to inventory or create purchase orders. Perform physical repair, inspection, receiving and supplier return actions in their own workflows.</Card><FilterBar><SearchInput value={query.search} onChange={search => setQuery(q => ({ ...q, page: 1, search }))} placeholder="Search claim or serial"/><Select aria-label="Claim state" value={query.status} onChange={status => setQuery(q => ({ ...q, page: 1, status }))} options={['DRAFT', 'SUBMITTED', 'ACCEPTED', 'RESOLVED', 'REJECTED', 'CANCELLED']} placeholder="All claim states"/><Button variant="secondary" onClick={remote.reload}>Refresh</Button></FilterBar>{!remote.value ? <Unavailable {...remote}/> : <ServerTable rows={remote.value.data} pagination={remote.value.pagination} onPage={page => setQuery(q => ({ ...q, page }))} emptyTitle="No warranty claims" columns={[{ key: 'claimNumber', label: 'Claim', render: r => <Link className="font-bold text-brand-600" to={`/assets/warranty-claims/${r.id}`}>{r.claimNumber}</Link> }, { key: 'serial', label: 'Serial', render: r => r.serialNumber.serialNumber }, { key: 'supplier', label: 'Supplier', render: r => r.supplier.companyName }, { key: 'warehouse', label: 'Claim warehouse', render: r => r.warehouse.name }, { key: 'status', label: 'State', render: r => <Badge>{r.status}</Badge> }, { key: 'outcome', label: 'Supplier outcome' }]}/ >}
  {open && <Modal open onOpenChange={setOpen} title="Choose claim source" description="Search an exact serial or asset tag. Reliable receipt links and recorded warranty dates are required."><SearchInput value={search} onChange={v => { setSearch(v); setSourcePage(1) }} placeholder="Search serial or asset tag"/>{!search.trim() && <p className="mt-3 text-sm subtle">Enter a serial number or asset tag to search.</p>}{search.trim() && !sources.value && !sources.error && <p role="status" className="mt-3 text-sm subtle">Loading source records…</p>}{search.trim() && sources.value && !sources.value.data.length && <p className="mt-3 text-sm subtle">No accessible equipment matches this search.</p>}{sources.error && <p role="alert" className="text-rose-600">{sources.error}</p>}{(sources.value?.data || []).map(s => <div key={s.id} className="mt-3 border-t divider py-3 text-sm"><strong>{s.serialNumber}</strong> · {s.asset?.assetTag || 'Warehouse stock'}<p>{s.supplier?.companyName || 'Unknown supplier'} · {s.status}</p><p className="text-xs subtle">{s.hasProvenance ? s.covered ? 'Recorded coverage is current' : 'Coverage is expired / future dated; submission will be blocked' : 'Missing exact receipt / warranty provenance'}</p><Button size="sm" disabled={!s.hasProvenance || !['AVAILABLE','ASSIGNED','QUARANTINE','DEFECTIVE','FOR_REPAIR'].includes(s.status)} onClick={() => { setOpen(false); setSelected(s) }}>Choose {s.serialNumber}</Button></div>)}{sources.value?.pagination && <div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="secondary" disabled={sourcePage <= 1} onClick={() => setSourcePage(v => v - 1)}>Previous sources</Button><Button size="sm" variant="secondary" disabled={sourcePage >= sources.value.pagination.totalPages} onClick={() => setSourcePage(v => v + 1)}>Next sources</Button><span className="text-xs subtle">{sources.value.pagination.total} matching serials</span></div>}</Modal>}
  {selected && <WorkflowForm title="Create warranty draft" description={`${selected.serialNumber} · ${selected.supplier?.companyName}. Creating a draft does not change custody or stock.`} fields={[text('issue', 'Warranty issue')]} submit={async v => { const r = await api.createClaim({ serialNumberId: selected.id, issue: v.issue }); navigate(`/assets/warranty-claims/${r.data.id}`) }} close={() => setSelected(null)}/>}</>
}

export function WarrantyClaimDetail() {
  const { id } = useParams(), { user, notify } = useInventory(), remote = useRemote(() => api.getClaim(id), [id]), [action, setAction] = useState(null), [supportError, setSupportError] = useState('')
  const row = remote.value?.data
  async function open(kind) {
    try {
      let maintenance = [], returns = []
      if (kind === 'resolve') {
        if (row.asset && can(user, 'assets.VIEW')) maintenance = (await api.getAsset(row.asset.id)).data.maintenanceRecords.filter(r => r.status === 'COMPLETED' && r.serialNumberId === row.serialNumberId)
        if (!row.asset && can(user, 'supplier_returns.VIEW')) returns = (await listSupplierReturns({ warehouse: row.warehouseId, limit: 100 })).data.filter(r => ['SHIPPED', 'COMPLETED'].includes(r.status) && r.receiptId === row.receiptId && r.supplierId === row.supplierId)
      }
      setAction({ kind, row, maintenance, returns }); setSupportError('')
    } catch (e) { setSupportError(e.message) }
  }
  if (!row) return <Unavailable {...remote}/>
  const editable = can(user, 'warranty_claims.EDIT'), approve = can(user, 'warranty_claims.APPROVE')
  const kinds = row.status === 'DRAFT' ? (editable ? ['edit', 'submit', 'cancel'] : []) : row.status === 'SUBMITTED' ? [...(editable ? ['cancel'] : []), ...(approve ? ['accept', 'reject'] : [])] : row.status === 'ACCEPTED' && approve ? ['resolve'] : []
  const fields = action?.kind === 'edit' ? [text('issue', 'Warranty issue', action.row.issue), evidence] : action?.kind === 'accept' ? [text('providerReference', 'Recorded supplier reference'), evidence] : action?.kind === 'resolve' ? [text('providerReference', 'Recorded supplier reference', action.row.providerReference), choices('outcome', 'Supplier outcome', ['REPAIRED', 'REPLACED', 'CREDIT', 'UNREPAIRED']), ...(action.maintenance.length ? [choices('maintenanceId', 'Supporting completed service', action.maintenance.map(r => ({ value: r.id, label: `${r.issue} · ${date(r.completedDate)}` })), '', false)] : []), ...(action.returns.length ? [choices('supplierReturnId', 'Supporting shipped return', action.returns.map(r => ({ value: r.id, label: r.returnNumber })), '', false)] : []), evidence] : [evidence]
  async function submit(values) { const body = Object.fromEntries(Object.entries(values).filter(([, v]) => v !== '')); await api.claimAction(id, action.kind, { ...body, ...av(action.row) }); notify('Supplier evidence recorded; physical workflows remain explicit.'); remote.reload() }
  async function reload() { const r = await api.getClaim(id); setAction(a => ({ ...a, row: r.data })); remote.reload() }
  return <><PageHeader eyebrow="Warranty claim" title={row.claimNumber} subtitle={`${row.serialNumber.serialNumber} · ${row.supplier.companyName}`}/><Card className="mb-4 space-y-3 p-5"><Badge>{row.status}</Badge><p>{row.issue}</p><p className="text-sm subtle">Claim owner: {row.warehouse.name} · Coverage through {date(row.warrantyEnd)} · {row.covered ? 'Within recorded coverage' : 'Outside recorded coverage'}</p><p className="text-sm subtle">Supplier outcome: {row.outcome || 'Awaiting decision'} · Reference: {row.providerReference || 'Unrecorded'}</p><p className="text-sm">Recording a supplier outcome does not release quarantine, change custody, create replacement serials or replenish stock. Record physical work and inspection separately.</p><div className="flex flex-wrap gap-3">{row.asset && <Link className="text-brand-600" to={`/assets/${row.asset.id}`}>Asset {row.asset.assetTag}</Link>}{row.receipt && <Link className="text-brand-600" to={`/procurement/purchase-orders/${row.receipt.purchaseOrderId}`}>Receipt {row.receipt.receiptNumber} / source PO</Link>}{row.maintenance && <Link className="text-brand-600" to="/assets/maintenance">Completed service: {row.maintenance.issue}</Link>}{row.supplierReturn && <Link className="text-brand-600" to={`/procurement/supplier-returns/${row.supplierReturn.id}`}>Return {row.supplierReturn.returnNumber}</Link>}</div><div className="flex flex-wrap gap-2">{kinds.map(kind => <Button key={kind} variant="secondary" onClick={() => open(kind)}>{kind} claim</Button>)}<Link to="/assets/warranty-claims"><Button variant="secondary">All claims</Button></Link></div>{supportError && <p role="alert" className="text-rose-600">{supportError}</p>}</Card><Card className="p-5"><h2 className="mb-3 font-bold">Decision evidence</h2>{row.events.map(e => <div key={e.id} className="border-t divider py-3 text-sm"><strong>{e.action}</strong> · {e.user.firstName} {e.user.lastName}<p>{e.notes}</p>{e.data.providerReference && <p>Supplier reference: {e.data.providerReference}</p>}{e.data.outcome && <p>Outcome: {e.data.outcome}</p>}<p className="text-xs subtle">{date(e.createdAt)}</p></div>)}</Card>{action && <WorkflowForm key={action.kind} title={`${action.kind} claim`} description="Record the actual supplier decision or evidence. This action does not send messages or perform physical stock operations." fields={fields} submit={submit} reload={reload} close={() => setAction(null)}/>}</>
}
