import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useInventory } from '../../context/InventoryContext.jsx'
import { can } from '../../lib/permissions.js'
import { Badge, Button, Card, EmptyState, Field, FilterBar, LoadingSkeleton, Modal, PageHeader, SearchInput, Select } from '../../components/ui.jsx'
import ServerTable from '../../components/ServerTable.jsx'
import * as api from '../../services/assetService.js'

export function Assets({ assigned = false }) {
  const { products, serials, warehouses, user, refreshData } = useInventory(), navigate = useNavigate()
  const [query, setQuery] = useState({ page: 1, search: '', warehouse: '', status: '', assigned: assigned ? 'true' : '' }), [result, setResult] = useState(null), [error, setError] = useState(''), [retry, setRetry] = useState(0)
  const [open, setOpen] = useState(false), [form, setForm] = useState({ productId: '', warehouseId: '', serialNumberId: '', notes: '' }), [pending, setPending] = useState(false), [formError, setFormError] = useState('')
  useEffect(() => { let active = true; setResult(null); setError(''); api.getAssets(query).then(r => { if (active) setResult(r) }).catch(e => { if (active) setError(e.message) }); return () => { active = false } }, [query, retry])
  const filter = (k, v) => setQuery(q => ({ ...q, [k]: v, ...(k === 'page' ? {} : { page: 1 }) }))
  async function save(e) { e.preventDefault(); setPending(true); setFormError(''); try { const r = await api.createAsset({ ...form, serialNumberId: form.serialNumberId || null }); setOpen(false); await refreshData(); navigate(`/assets/${r.data.id}`) } catch (e) { setFormError(e.message) } finally { setPending(false) } }
  return <><PageHeader eyebrow="Asset Management" title={assigned ? 'Assigned Equipment' : 'Assets'} subtitle="Custody and service history for company equipment." actions={!assigned && can(user, 'assets.CREATE') && <Button onClick={() => { setOpen(true); setFormError('') }}>Register asset</Button>}/><FilterBar><SearchInput value={query.search} onChange={v => filter('search', v)} placeholder="Search asset or serial"/><Select aria-label="Asset warehouse" value={query.warehouse} onChange={v => filter('warehouse', v)} options={warehouses.map(w => ({ value: w.id, label: w.name }))} placeholder="All accessible warehouses"/><Select aria-label="Asset status" value={query.status} onChange={v => filter('status', v)} options={['AVAILABLE', 'ASSIGNED', 'MAINTENANCE', 'QUARANTINE', 'RETIRED', 'LOST', 'DISPOSED']} placeholder="All statuses"/><Button variant="secondary" onClick={() => setRetry(v => v + 1)}>Refresh</Button></FilterBar>
  {error ? <Card><EmptyState title="Assets unavailable" description={error}/></Card> : !result ? <LoadingSkeleton/> : <ServerTable rows={result.data} pagination={result.pagination} onPage={v => filter('page', v)} emptyTitle="No assets found" columns={[{ key: 'assetTag', label: 'Asset', render: a => <Link className="font-bold text-brand-600" to={`/assets/${a.id}`}>{a.assetTag}</Link> }, { key: 'product', label: 'Equipment', render: a => <div>{a.product.name}<p className="text-xs subtle">{a.serialNumber?.serialNumber || 'Unserialized'}</p></div> }, { key: 'warehouse', label: 'Owner warehouse', render: a => a.warehouse?.name || 'Legacy unknown' }, { key: 'custodian', label: 'Current custodian', render: a => a.assignments.find(r => r.status === 'ACTIVE')?.assignedTo || 'Unassigned' }, { key: 'status', label: 'Condition', render: a => <Badge>{a.status}</Badge> }]}/>}
  <Modal open={open} onOpenChange={v => { if (!pending) setOpen(v) }} title="Register asset" description="Moves one available unit from warehouse stock to the company asset pool. Custody is assigned separately."><form className="space-y-4" onSubmit={save}><Field label="Product" required><Select aria-label="Asset product" required value={form.productId} onChange={v => setForm(f => ({ ...f, productId: v, serialNumberId: '' }))} options={products.filter(p => !p.inactive).map(p => ({ value: p.id, label: `${p.sku} · ${p.name}` }))} placeholder="Choose product"/></Field><Field label="Source warehouse" required><Select aria-label="Source warehouse" required value={form.warehouseId} onChange={v => setForm(f => ({ ...f, warehouseId: v, serialNumberId: '' }))} options={warehouses.filter(w => w.status === 'Operational').map(w => ({ value: w.id, label: w.name }))} placeholder="Choose warehouse"/></Field>{products.find(p => p.id === form.productId)?.serialTracking && <Field label="Exact serial" required><Select aria-label="Exact serial" required value={form.serialNumberId} onChange={v => setForm(f => ({ ...f, serialNumberId: v }))} options={serials.filter(s => s.productId === form.productId && s.status === 'Available' && s.warehouse === warehouses.find(w => w.id === form.warehouseId)?.name).map(s => ({ value: s.id, label: s.serial }))} placeholder="Choose available serial"/></Field>}<Field label="Registration notes"><textarea aria-label="Registration notes" className="field" maxLength={4000} value={form.notes} onChange={e => setForm(f => ({ ...f, notes: e.target.value }))}/></Field>{formError && <p role="alert" className="text-rose-600">{formError}</p>}<Button type="submit" loading={pending}>Register asset</Button></form></Modal></>
}
export function AssignedEquipment() { return <Assets assigned/> }
export function WarrantyTracking({ expiringOnly = false }) {
  const { assets, serials, products, user } = useInventory(), [search, setSearch] = useState('')
  const rows = [...assets.map(a => ({ id: a.id, serial: a.serial, productId: a.productId, end: a.warrantyEnd, path: `/assets/${a.id}` })), ...serials.filter(s => !assets.some(a => a.serial === s.serial)).map(s => ({ id: s.id, serial: s.serial, productId: s.productId, end: s.end, path: `/serial-numbers/${s.id}` }))].map(r => ({ ...r, days: r.end && r.end !== '—' ? Math.ceil((new Date(`${r.end.slice(0, 10)}T23:59:59.999Z`).getTime() - Date.now()) / 86400000) : null })).filter(r => (!expiringOnly || (r.days != null && r.days >= 0 && r.days <= 60)) && `${r.serial} ${products.find(p => p.id === r.productId)?.name}`.toLowerCase().includes(search.toLowerCase()))
  return <><PageHeader eyebrow="Asset Management" title={expiringOnly ? 'Expiring Warranty' : 'Warranty Tracking'} subtitle="Coverage dates are separate from supplier claim records." actions={can(user, 'warranty_claims.VIEW') && <Link to="/assets/warranty-claims"><Button>Warranty claims</Button></Link>}/><FilterBar><SearchInput value={search} onChange={setSearch} placeholder="Search product or serial"/></FilterBar><ServerTable rows={rows} pagination={{ total: rows.length, page: 1, totalPages: 1 }} onPage={() => {}} emptyTitle="No warranty records found" columns={[{ key: 'serial', label: 'Equipment', render: r => <Link className="text-brand-600" to={r.path}>{r.serial || 'Unserialized asset'}</Link> }, { key: 'productId', label: 'Product', render: r => products.find(p => p.id === r.productId)?.name }, { key: 'end', label: 'Coverage through (UTC)' }, { key: 'days', label: 'Coverage', render: r => r.days == null ? 'Unknown' : r.days < 0 ? 'Expired' : `${r.days} days remaining` }]}/></>
}
