import { apiRequest } from '../lib/api.js'

export const getAssets = (params = {}) => apiRequest('/assets', { params })
export const getAsset = id => apiRequest(`/assets/${id}`)
export const updateAsset = (id, data) => apiRequest(`/assets/${id}`, { method: 'PUT', body: data })
export const createAsset = data => apiRequest('/assets', { method: 'POST', body: data })
export const assetAction = (id, action, data) => apiRequest(`/assets/${id}/${action}`, { method: 'POST', body: data })
export const getMaintenance = (params = {}) => apiRequest('/maintenance', { params })
export const createMaintenance = data => apiRequest('/maintenance', { method: 'POST', body: data })
export const getMaintenanceRecord = id => apiRequest(`/maintenance/${id}`)
export const updateMaintenance = (id, data) => apiRequest(`/maintenance/${id}`, { method: 'PUT', body: data })
export const maintenanceAction = (id, action, data) => apiRequest(`/maintenance/${id}/${action}`, { method: 'POST', body: data })
export const getPlans = (params = {}) => apiRequest('/preventive-maintenance', { params })
export const createPlan = data => apiRequest('/preventive-maintenance', { method: 'POST', body: data })
export const updatePlan = (id, data) => apiRequest(`/preventive-maintenance/${id}`, { method: 'PUT', body: data })
export const schedulePlan = (id, data) => apiRequest(`/preventive-maintenance/${id}/schedule`, { method: 'POST', body: data })
export const getClaims = (params = {}) => apiRequest('/warranty-claims', { params })
export const getClaim = id => apiRequest(`/warranty-claims/${id}`)
export const getClaimSources = (params = {}) => apiRequest('/warranty-claims/sources', { params })
export const createClaim = data => apiRequest('/warranty-claims', { method: 'POST', body: data })
export const claimAction = (id, action, data) => apiRequest(`/warranty-claims/${id}/${action}`, { method: 'POST', body: data })
