import { apiRequest } from '../lib/api.js'
export const getSessions=(userId,page=1)=>apiRequest(userId?`/sessions/users/${encodeURIComponent(userId)}`:'/sessions',{params:{page}})
export const revokeSession=id=>apiRequest(`/sessions/${encodeURIComponent(id)}/revoke`,{method:'POST',body:{}})
export const revokeUserSessions=(id,confirmation)=>apiRequest(`/sessions/users/${encodeURIComponent(id)}/revoke`,{method:'POST',body:{confirmation}})
export const unlockAccount=id=>apiRequest(`/sessions/users/${encodeURIComponent(id)}/unlock`,{method:'POST',body:{}})
export const getSystemHealth=()=>apiRequest('/system/health')
export const getBackups=(page=1)=>apiRequest('/system/backups',{params:{page}})
export const createBackup=()=>apiRequest('/system/backups',{method:'POST',body:{confirmation:'CREATE BACKUP'}})
export const verifyBackup=id=>apiRequest(`/system/backups/${encodeURIComponent(id)}/verify`,{method:'POST',body:{}})
export const planRestore=(id,targetSchema)=>apiRequest(`/system/backups/${encodeURIComponent(id)}/restore-plan`,{method:'POST',body:{targetSchema}})
export const confirmRestore=(id,confirmation)=>apiRequest(`/system/restores/${encodeURIComponent(id)}/confirm`,{method:'POST',body:{confirmation}})
export const getRestorePlans=()=>apiRequest('/system/restores')
export const getRetention=()=>apiRequest('/system/retention')
export const saveRetention=body=>apiRequest('/system/retention',{method:'PUT',body})
export const archiveHistory=expectedRevision=>apiRequest('/system/retention/archive',{method:'POST',body:{expectedRevision,confirmation:'ARCHIVE HISTORY'}})
export const getOpenApi=()=>apiRequest('/docs')
export const getSchedules=()=>apiRequest('/report-schedules')
export const createSchedule=body=>apiRequest('/report-schedules',{method:'POST',body})
export const updateSchedule=(id,body)=>apiRequest(`/report-schedules/${encodeURIComponent(id)}`,{method:'PUT',body})
export const getScheduleRuns=(id,page=1)=>apiRequest(`/report-schedules/${encodeURIComponent(id)}/runs`,{params:{page}})
export const getScheduledResult=id=>apiRequest(`/report-schedules/runs/${encodeURIComponent(id)}`)
