import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useInventory } from '../../context/InventoryContext.jsx'
import { can } from '../../lib/permissions.js'
import { Button, Card, EmptyState, Field, FilterBar, LoadingSkeleton, Modal, PageHeader, SearchInput, Select } from '../../components/ui.jsx'
import ServerTable from '../../components/ServerTable.jsx'
import * as api from '../../services/replenishmentService.js'

const message = error => error.errors?.[0]?.message || error.message
const percent = value => value == null ? 'No data' : `${value.toFixed(1)}%`
const page = { total: 0, page: 1, totalPages: 1 }
export function ReorderSuggestions() {
  const { user, warehouses, notify, refreshData } = useInventory(), navigate = useNavigate()
  const [query, setQuery] = useState({ warehouse: '', search: '', page: 1 }), [result, setResult] = useState(null), [error, setError] = useState(''), [loading, setLoading] = useState(false), [retry, setRetry] = useState(0)
  const [selection, setSelection] = useState(null), [notes, setNotes] = useState(''), [supplier, setSupplier] = useState(''), [pending, setPending] = useState(false), [formError, setFormError] = useState('')
  useEffect(() => { let active = true; setResult(null); setError(''); if (!query.warehouse) return; setLoading(true)
    api.suggestions(query).then(value => { if (active) setResult(value) }).catch(error => { if (active) setError(message(error)) }).finally(() => { if (active) setLoading(false) }); return () => { active = false }
  }, [query, retry])
  const filter = (key, value) => { setResult(null); setQuery(current => ({ ...current, [key]: value, ...(key === 'page' ? {} : { page: 1 }) })) }
  function open(row, kind) { setSelection({ row, kind, warehouseId: query.warehouse }); setNotes(''); setSupplier(row.defaultSupplier?.status === 'ACTIVE' ? row.defaultSupplier.id : ''); setFormError('') }
  async function save(event) {
    event.preventDefault(); setPending(true); setFormError('')
    try { const value = await api.createDocument({ warehouseId: selection.warehouseId, productId: selection.row.product.id, snapshot: selection.row.snapshot, kind: selection.kind, supplierId: supplier || undefined, notes }); setSelection(null); notify('Draft created. Review and submit it through the existing approval workflow.'); await refreshData(); navigate(`/procurement/${value.data.kind === 'ORDER' ? 'purchase-orders' : 'purchase-requests'}/${value.data.document.id}`) }
    catch (error) { setFormError(message(error)) } finally { setPending(false) }
  }
  async function reload() {
    setPending(true); setFormError('')
    try { const value = await api.suggestions({ warehouse: selection.warehouseId, search: selection.row.product.sku, pageSize: 100 }); const row = value.data.find(row => row.product.id === selection.row.product.id); if (!row) throw Error('This SKU is no longer below its threshold. Close this form and refresh.'); setSelection(current => ({ ...current, row })); setResult(value); setRetry(current => current + 1) }
    catch (error) { setFormError(message(error)) } finally { setPending(false) }
  }
  return <><PageHeader eyebrow="Procurement" title="Reorder Suggestions" subtitle="Review warehouse availability and existing procurement before explicitly creating a draft."/>
    <Card className="mb-4 p-4 text-sm leading-relaxed subtle">Available = physical − all unavailable holds, including reservations and conditions. Incoming = remaining approved, ordered and partial POs. Planned = draft/pending POs and draft/submitted/approved PRs, counted once when converted through RFQ/PO. Trigger = reorder point (or minimum stock); target = the greater of maximum stock and trigger. Suggested = target − available − incoming − planned when availability reaches the trigger. Drafts need review; no order is placed automatically. Transfers are not counted as usable incoming stock until physically received.</Card>
    <FilterBar><Select aria-label="Reorder warehouse" className="w-full sm:w-56" value={query.warehouse} onChange={value => filter('warehouse', value)} options={warehouses.filter(row => row.status === 'Operational').map(row => ({ value: row.id, label: row.name }))} placeholder="Choose warehouse"/><SearchInput className="w-full sm:w-64" value={query.search} onChange={value => filter('search', value)} placeholder="Search SKU or product"/><Button variant="secondary" onClick={() => setRetry(value => value + 1)}>Refresh</Button></FilterBar>
    {!query.warehouse ? <Card><EmptyState title="Choose a warehouse" description="Suggestions include active catalog products even when no stock row exists."/></Card> : error ? <Card><EmptyState title="Suggestions unavailable" description={error} action={<Button onClick={() => setRetry(value => value + 1)}>Retry</Button>}/></Card> : loading || !result ? <LoadingSkeleton/> : <ServerTable rows={result.data.map(row => ({ ...row, id: row.product.id }))} pagination={result.meta} onPage={value => filter('page', value)} emptyTitle="No products at their reorder threshold" columns={[
      { key: 'product', label: 'Product', render: row => <div className="min-w-40"><Link className="font-semibold text-brand-600" to={`/products/${row.product.id}`}>{row.product.sku}</Link><p className="text-xs subtle">{row.product.name}</p><p className="text-xs subtle">{row.defaultSupplier?.companyName || 'No default supplier'}</p></div> },
      { key: 'available', label: 'Available', render: row => <div>{row.available}<p className="text-xs subtle">{row.quantity} physical · {row.unavailable} unavailable</p><p className="text-xs subtle">Q {row.quarantine} · Defect {row.defective} · Repair {row.forRepair} · Return {row.returnPending}</p></div> },
      { key: 'incoming', label: 'Incoming / planned', render: row => <div>{row.incoming} / {row.planned}<details className="mt-1 text-xs"><summary className="cursor-pointer text-brand-600">Source documents</summary>{[...row.orders.map(record => ({ ...record, number: record.poNumber, path: 'purchase-orders' })), ...row.requests.map(record => ({ ...record, number: record.prNumber, path: 'purchase-requests' }))].map(record => <p key={record.id}><Link className="text-brand-600" to={`/procurement/${record.path}/${record.id}`}>{record.number}</Link> · {record.quantity} · {record.status}</p>)}</details></div> },
      { key: 'target', label: 'Trigger / target', render: row => `${row.threshold} / ${row.target}` }, { key: 'suggestedQuantity', label: 'Suggested units', render: row => <strong>{row.suggestedQuantity || 'Covered'}</strong> },
      { key: 'actions', label: 'Create draft', render: row => <div className="flex flex-wrap gap-2">{can(user, 'purchase_requests.CREATE') && <Button size="sm" variant="secondary" disabled={!row.suggestedQuantity} aria-label={`Create PR ${row.product.sku}`} onClick={() => open(row, 'REQUEST')}>PR</Button>}{can(user, 'purchasing.CREATE') && <Button size="sm" variant="secondary" disabled={!row.suggestedQuantity} aria-label={`Create PO ${row.product.sku}`} onClick={() => open(row, 'ORDER')}>PO</Button>}</div> }
    ]}/>}
    <Modal open={Boolean(selection)} onOpenChange={open => { if (!open && !pending) setSelection(null) }} title={selection?.kind === 'ORDER' ? 'Create draft purchase order' : 'Create draft purchase request'} description="Review the current suggestion before creating a document.">
      {selection && <form className="space-y-4" onSubmit={save}><p className="text-sm"><strong>{selection.row.product.sku}</strong> · {selection.row.suggestedQuantity} {selection.row.product.unit} · Catalog unit cost {selection.row.product.purchaseCost}</p><p className="text-xs subtle">Available {selection.row.available} + incoming {selection.row.incoming} + planned {selection.row.planned}; target {selection.row.target}. Prices, taxes and delivery can be reviewed in the draft before approval.</p>{selection.kind === 'ORDER' && <Field label="Supplier" required><Select required aria-label="Reorder supplier" value={supplier} onChange={setSupplier} options={(result?.suppliers || []).map(row => ({ value: row.id, label: row.companyName }))} placeholder="Choose active supplier"/></Field>}<Field label="Replenishment reason" required><textarea className="field min-h-24" aria-label="Replenishment reason" required minLength={5} maxLength={3000} value={notes} onChange={event => setNotes(event.target.value)}/></Field>{formError && <p role="alert" className="text-sm text-rose-600">{formError}</p>}<div className="flex flex-wrap gap-2"><Button type="submit" loading={pending} disabled={!selection.row.suggestedQuantity}>Create draft</Button><Button type="button" variant="secondary" disabled={pending} onClick={reload}>Reload suggestion</Button></div></form>}
    </Modal></>
}

export function SupplierPerformance() {
  const { warehouses } = useInventory(), today = new Date().toISOString().slice(0, 10)
  const [draft, setDraft] = useState({ warehouse: '', dateFrom: `${today.slice(0, 4)}-01-01`, dateTo: today }), [query, setQuery] = useState(draft), [result, setResult] = useState(null), [loading, setLoading] = useState(true), [error, setError] = useState(''), [retry, setRetry] = useState(0)
  useEffect(() => { let active = true; setLoading(true); setError(''); setResult(null); api.performance(query).then(value => { if (active) setResult(value) }).catch(error => { if (active) setError(message(error)) }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [query, retry])
  const updateDate = (key, event) => { const next = event.currentTarget.value; setDraft(value => ({ ...value, [key]: next })) }
  return <><PageHeader eyebrow="Procurement" title="Supplier Performance" subtitle="Actual purchasing, receiving and physically shipped returns within your warehouse access."/>
    <form onSubmit={event => { event.preventDefault(); setQuery({ ...draft }); setRetry(value => value + 1) }}><FilterBar><Select aria-label="Performance warehouse" className="w-full sm:w-56" value={draft.warehouse} onChange={warehouse => setDraft(value => ({ ...value, warehouse }))} options={warehouses.map(row => ({ value: row.id, label: row.name }))} placeholder="All accessible warehouses"/><Field label="PO date from"><input aria-label="PO date from" className="field" type="date" required value={draft.dateFrom} onInput={event => updateDate('dateFrom', event)} onChange={event => updateDate('dateFrom', event)}/></Field><Field label="Through date"><input aria-label="Through date" className="field" type="date" required value={draft.dateTo} onInput={event => updateDate('dateTo', event)} onChange={event => updateDate('dateTo', event)}/></Field><Button type="submit">Apply window</Button></FilterBar></form>
    <Card className="mb-4 p-4 text-sm leading-relaxed subtle">Window selects POs by order date, then counts their actual receipts and shipped returns through the window end (UTC). Draft/pending orders are excluded; cancelled orders count only when they have receipts. On-time = fully received orders completed by promised delivery day / fully received orders with a promised date. First receipt days = elapsed days from order date to first receipt; its sample count excludes missing/invalid dates. Return rate = physically shipped units from cohort receipts / received units; pending or cancelled returns are excluded. Received value uses exact PO line cost, excluding tax/shipping. This is historical performance, not a supplier rating or guaranteed lead time.</Card>
    {error ? <Card><EmptyState title="Performance unavailable" description={error} action={<Button onClick={() => setRetry(value => value + 1)}>Retry</Button>}/></Card> : loading || !result ? <LoadingSkeleton/> : <><p className="mb-3 text-xs subtle">{result.window.dateFrom} – {result.window.dateTo} · {result.window.basis}</p><ServerTable rows={result.data.map(row => ({ ...row, id: row.supplier.id }))} pagination={{ ...page, total: result.data.length }} onPage={() => {}} emptyTitle="No actual orders in this window" emptyDescription="Choose a different period or warehouse. Missing samples are never reported as perfect performance." columns={[
      { key: 'supplier', label: 'Supplier', render: row => <div className="min-w-40"><Link className="font-semibold text-brand-600" to={`/procurement/suppliers/${row.supplier.id}`}>{row.supplier.companyName}</Link><p className="text-xs subtle">{row.supplier.supplierCode}</p><details className="text-xs"><summary className="cursor-pointer text-brand-600">{row.orders} source POs</summary>{row.documents.map(doc => <p key={doc.id}><Link className="text-brand-600" to={`/procurement/purchase-orders/${doc.id}`}>{doc.poNumber}</Link> · {doc.status}</p>)}</details></div> },
      { key: 'units', label: 'Ordered / received', render: row => `${row.orderedUnits} / ${row.receivedUnits}` }, { key: 'receivedValue', label: 'Received value' },
      { key: 'onTime', label: 'On time', render: row => <div>{percent(row.onTimePercent)}<p className="text-xs subtle">{row.onTimeOrders} / {row.completedDueOrders} dated completions</p><p className="text-xs subtle">{row.openOverdueOrders} open overdue</p></div> },
      { key: 'lead', label: 'First receipt days', render: row => <div>{row.averageFirstReceiptDays == null ? 'No data' : row.averageFirstReceiptDays.toFixed(1)}<p className="text-xs subtle">{row.firstReceiptSamples} samples</p></div> },
      { key: 'returns', label: 'Return rate', render: row => <div>{percent(row.returnPercent)}<p className="text-xs subtle">{row.returnedUnits} / {row.receivedUnits} units</p></div> }
    ]}/></>}
  </>
}
