import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { Plus } from 'lucide-react'
import { useInventory } from '../../context/InventoryContext.jsx'
import { can } from '../../lib/permissions.js'
import { shortDate } from '../../lib/format.js'
import { Badge, Button, Card, EmptyState, Field, FilterBar, LoadingSkeleton, Modal, PageHeader, SearchInput, Select } from '../../components/ui.jsx'
import ServerTable from '../../components/ServerTable.jsx'
import * as api from '../../services/supplierReturnService.js'

const label = value => value.toLowerCase().replaceAll('_', ' ').replace(/^./, char => char.toUpperCase())
const reasons = ['DEFECTIVE', 'WRONG_ITEM', 'DAMAGED', 'WARRANTY', 'OVER_DELIVERY', 'OTHER']
const options = values => values.map(value => ({ value, label: label(value) }))
const statuses = ['DRAFT', 'PENDING', 'APPROVED', 'SHIPPED', 'COMPLETED', 'CANCELLED']
const message = error => error.errors?.[0]?.message || error.message
const emptyPage = { page: 1, total: 0, totalPages: 1 }

export function SupplierReturns() {
  const { user, warehouses } = useInventory(), navigate = useNavigate()
  const [rows, setRows] = useState([]), [pagination, setPagination] = useState(emptyPage), [loading, setLoading] = useState(true), [error, setError] = useState('')
  const [query, setQuery] = useState({ page: 1, search: '', warehouse: '', status: '' }), [retry, setRetry] = useState(0)
  useEffect(() => { let active = true; setLoading(true); setError(''); api.listReturns(query).then(result => { if (active) { setRows(result.data); setPagination(result.pagination) } }).catch(error => { if (active) setError(message(error)) }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [query, retry])
  const filter = (key, value) => setQuery(current => ({ ...current, [key]: value, page: 1 }))
  return <><PageHeader eyebrow="Procurement" title="Supplier Returns" subtitle="Return received goods with approval, exact serials and physical shipment history." actions={can(user, 'supplier_returns.CREATE') && <Button icon={Plus} onClick={() => navigate('/procurement/supplier-returns/new')}>Create return</Button>}/>
    <FilterBar><SearchInput value={query.search} onChange={value => filter('search', value)} placeholder="Search returns or suppliers"/><Select aria-label="Return status" value={query.status} onChange={value => filter('status', value)} options={options(statuses)} placeholder="All statuses"/><Select aria-label="Return warehouse" value={query.warehouse} onChange={value => filter('warehouse', value)} options={warehouses.map(row => ({ value: row.id, label: row.name }))} placeholder="All warehouses"/></FilterBar>
    {error ? <Card><EmptyState title="Returns unavailable" description={error} action={<Button onClick={() => setRetry(value => value + 1)}>Retry</Button>}/></Card> : loading ? <LoadingSkeleton/> : <ServerTable rows={rows} pagination={pagination} onPage={page => setQuery(current => ({ ...current, page }))} emptyTitle="No supplier returns" emptyDescription="Create a return from a recorded purchase receipt." columns={[
      { key: 'returnNumber', label: 'Return', render: row => <Link className="font-semibold text-brand-600" to={`/procurement/supplier-returns/${row.id}`}>{row.returnNumber}</Link> },
      { key: 'supplier', label: 'Supplier', render: row => row.supplier.companyName }, { key: 'receipt', label: 'Receipt', render: row => row.receipt.receiptNumber },
      { key: 'warehouse', label: 'Warehouse', render: row => row.warehouse.name }, { key: 'status', label: 'Status', render: row => <Badge>{label(row.status)}</Badge> }, { key: 'createdAt', label: 'Created', render: row => shortDate(row.createdAt) }
    ]}/>}</>
}

export function SupplierReturnForm() {
  const { id } = useParams(), [params] = useSearchParams(), navigate = useNavigate(), { notify } = useInventory()
  const [record, setRecord] = useState(null), [receiptId, setReceiptId] = useState(params.get('receiptId') || ''), [source, setSource] = useState(null)
  const [sources, setSources] = useState([]), [pagination, setPagination] = useState(emptyPage), [query, setQuery] = useState({ page: 1, search: '' })
  const [items, setItems] = useState([]), [reason, setReason] = useState('DEFECTIVE'), [notes, setNotes] = useState(''), [loading, setLoading] = useState(true), [pending, setPending] = useState(false), [error, setError] = useState(''), [retry, setRetry] = useState(0)
  useEffect(() => { if (!id) return; let active = true; setLoading(true); api.getReturn(id).then(result => { if (active) { const row = result.data; setRecord(row); setReason(row.reason); setNotes(row.notes || ''); setReceiptId(row.receiptId) } }).catch(error => { if (active) setError(message(error)) }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [id, retry])
  useEffect(() => {
    if (id && !record) return
    let active = true; setLoading(true); setError('')
    const request = receiptId ? api.getSource(receiptId) : api.listSources(query)
    request.then(result => { if (!active) return; if (receiptId) { setSource(result.data); setItems(result.data.items.map(line => { const existing = record?.items.find(item => item.receiptItemId === line.id); return { receiptItemId: line.id, selected: Boolean(existing), quantity: existing?.quantity || 1, reason: existing?.reason || reason, condition: existing?.condition || 'DEFECTIVE', stockCondition: existing?.stockCondition || 'AVAILABLE', serialNumberIds: existing?.serialSelections.map(selection => selection.serialNumberId) || [] } })) } else { setSources(result.data); setPagination(result.pagination) } }).catch(error => { if (active) setError(message(error)) }).finally(() => { if (active) setLoading(false) })
    return () => { active = false }
  }, [receiptId, query, record, retry])
  const update = (index, patch) => setItems(current => current.map((item, position) => index === position ? { ...item, ...patch } : item))
  async function save(event) {
    event.preventDefault(); setPending(true); setError('')
    try { const result = await api.saveReturn(id, { receiptId, reason, notes, expectedUpdatedAt: record?.updatedAt, items: items.filter(item => item.selected).map(({ selected, ...item }) => item) }); notify('Draft supplier return saved.'); navigate(`/procurement/supplier-returns/${result.data.id}`) } catch (error) { setError(message(error)) } finally { setPending(false) }
  }
  return <><PageHeader eyebrow="Procurement · Supplier returns" title={id ? 'Edit draft return' : 'Create supplier return'} subtitle="Choose a receipt, quantities and exact serials. Stock is held only when you submit."/>
    {error && <div className="mb-4 flex flex-wrap items-center gap-3"><p role="alert" className="text-sm text-rose-600">{error}</p><Button variant="secondary" onClick={() => setRetry(value => value + 1)}>Reload source</Button></div>}
    {loading ? <LoadingSkeleton/> : record && record.status !== 'DRAFT' ? <Card><EmptyState title="This return is no longer editable" action={<Button onClick={() => navigate(`/procurement/supplier-returns/${id}`)}>Open return</Button>}/></Card> : !receiptId ? <>
      <FilterBar><SearchInput value={query.search} onChange={search => setQuery({ page: 1, search })} placeholder="Find receipt or purchase order"/></FilterBar>
      <ServerTable rows={sources} pagination={pagination} onPage={page => setQuery(current => ({ ...current, page }))} emptyTitle="No purchase receipts" emptyDescription="Receive goods on a purchase order before creating a supplier return." columns={[
        { key: 'receiptNumber', label: 'Receipt' }, { key: 'purchaseOrder', label: 'Purchase order', render: row => row.purchaseOrder.poNumber }, { key: 'supplier', label: 'Supplier', render: row => row.purchaseOrder.supplier.companyName }, { key: 'warehouse', label: 'Warehouse', render: row => row.warehouse.name }, { key: 'choose', label: 'Action', render: row => <Button size="sm" onClick={() => setReceiptId(row.id)}>Use {row.receiptNumber}</Button> }
      ]}/></> : source && <form onSubmit={save} className="space-y-5">
      <Card className="space-y-4 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">{source.receiptNumber} · {source.purchaseOrder.poNumber}</h2><p className="mt-1 text-sm subtle">{source.purchaseOrder.supplier.companyName} · {source.warehouse.name}</p></div>{!id && <Button type="button" variant="secondary" onClick={() => { setReceiptId(''); setSource(null) }}>Choose another receipt</Button>}</div>
        <Field label="Return reason" required><Select aria-label="Return reason" required value={reason} onChange={setReason} options={options(reasons)}/></Field><Field label="Notes"><textarea aria-label="Return notes" className="field" maxLength={4000} rows={3} value={notes} onChange={event => setNotes(event.target.value)}/></Field></Card>
      {source.items.map((line, index) => { const item = items[index]; if (!item) return null; return <Card key={line.id} className="space-y-4 p-5"><label className="flex items-start gap-3 font-semibold"><input type="checkbox" className="mt-1" checked={item.selected} onChange={event => update(index, { selected: event.target.checked })}/><span>{line.product.name}<span className="mt-1 block text-xs font-normal subtle">{line.product.sku} · Received {line.quantity} · Unclaimed {line.returnableQuantity}</span></span></label>
        {item.selected && <><div className="grid gap-4 sm:grid-cols-3"><Field label="Quantity" required><input aria-label={`Return quantity ${line.product.sku}`} className="field" type="number" min={1} max={line.quantity} required value={item.quantity} onChange={event => update(index, { quantity: Number(event.target.value) })}/></Field><Field label="Item reason" required><Select aria-label={`Item reason ${line.product.sku}`} required value={item.reason} onChange={reason => update(index, { reason })} options={options(reasons)}/></Field><Field label="Observed condition" required><Select aria-label={`Condition ${line.product.sku}`} required value={item.condition} onChange={condition => update(index, { condition })} options={options(['AVAILABLE', 'DEFECTIVE', 'DAMAGED', 'FOR_REPAIR'])}/></Field></div>
          {!line.product.trackSerialNumbers && <Field label="Source stock condition" required><Select aria-label={`Source stock condition ${line.product.sku}`} required value={item.stockCondition} onChange={stockCondition => update(index, { stockCondition })} options={options(['AVAILABLE', 'QUARANTINE', 'DEFECTIVE', 'FOR_REPAIR'])}/><p className="mt-2 text-xs subtle">Available {line.stockBalances?.availableQuantity || 0} · Quarantine {line.stockBalances?.quarantineQuantity || 0} · Defective {line.stockBalances?.defectiveQuantity || 0} · For repair {line.stockBalances?.forRepairQuantity || 0}. Held units move to return pending on submission.</p></Field>}
          {line.product.trackSerialNumbers && <fieldset><legend className="mb-2 text-sm font-semibold">Exact receipt serials · {item.serialNumberIds.length} selected / {item.quantity} required</legend>{line.serials.length ? <div className="grid max-h-64 gap-2 overflow-y-auto rounded-xl border divider p-3 sm:grid-cols-2">{line.serials.map(serial => <label key={serial.id} className="flex items-start gap-2 break-all text-sm"><input type="checkbox" aria-label={`Return serial ${serial.serialNumber}`} checked={item.serialNumberIds.includes(serial.id)} onChange={event => update(index, { serialNumberIds: event.target.checked ? [...item.serialNumberIds, serial.id] : item.serialNumberIds.filter(id => id !== serial.id) })}/><span>{serial.serialNumber} <span className="subtle">· {label(serial.status)}</span></span></label>)}</div> : <p className="text-sm subtle">No eligible receipt serials remain at this warehouse.</p>}</fieldset>}
        </>}</Card> })}
      <div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={() => navigate('/procurement/supplier-returns')}>Back to returns</Button><Button type="submit" loading={pending} disabled={!items.some(item => item.selected)}>Save draft return</Button></div>
    </form>}</>
}

export function SupplierReturnDetail() {
  const { id } = useParams(), navigate = useNavigate(), { user, notify, refreshData } = useInventory()
  const [record, setRecord] = useState(null), [loading, setLoading] = useState(true), [error, setError] = useState(''), [retry, setRetry] = useState(0)
  const [decision, setDecision] = useState(''), [notes, setNotes] = useState(''), [shipment, setShipment] = useState(''), [pending, setPending] = useState(false)
  useEffect(() => { let active = true; setLoading(true); setError(''); api.getReturn(id).then(result => { if (active) setRecord(result.data) }).catch(error => { if (active) setError(message(error)) }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [id, retry])
  const choose = action => { setDecision(action); setNotes(''); setShipment(''); setError('') }
  async function act(event) {
    event.preventDefault(); setPending(true); setError('')
    try { const result = await api.returnAction(id, decision, { expectedUpdatedAt: record.updatedAt, shipmentReference: shipment, notes }); setRecord(result.data); setDecision(''); notify('Supplier return updated.'); await refreshData() } catch (error) { setError(message(error)) } finally { setPending(false) }
  }
  if (loading) return <LoadingSkeleton/>
  if (!record) return <Card><EmptyState title="Return unavailable" description={error} action={<Button onClick={() => setRetry(value => value + 1)}>Retry</Button>}/></Card>
  const actions = [['DRAFT', 'submit', 'EDIT', 'Submit and hold stock'], ['PENDING', 'approve', 'APPROVE', 'Approve return'], ['APPROVED', 'ship', 'SHIP', 'Confirm physical shipment'], ['SHIPPED', 'complete', 'COMPLETE', 'Record supplier outcome']]
  return <><PageHeader eyebrow="Procurement · Supplier return" title={record.returnNumber} subtitle={`${record.supplier.companyName} · ${record.warehouse.name}`} actions={<div className="flex flex-wrap gap-2">{record.status === 'DRAFT' && can(user, 'supplier_returns.EDIT') && <Button variant="secondary" onClick={() => navigate(`/procurement/supplier-returns/${id}/edit`)}>Edit draft</Button>}{actions.filter(([status, , permission]) => record.status === status && can(user, `supplier_returns.${permission}`)).map(([, action, , title]) => <Button key={action} onClick={() => choose(action)}>{title}</Button>)}{['DRAFT', 'PENDING', 'APPROVED'].includes(record.status) && can(user, 'supplier_returns.EDIT') && <Button variant="secondary" onClick={() => choose('cancel')}>Cancel return</Button>}</div>}/>
    {error && !decision && <div className="mb-4 flex flex-wrap items-center gap-3"><p role="alert" className="text-sm text-rose-600">{error}</p><Button variant="secondary" onClick={() => setRetry(value => value + 1)}>Reload return</Button></div>}
    <Card className="mb-5 space-y-3 p-5"><div className="flex flex-wrap gap-4"><Badge>{label(record.status)}</Badge><span className="text-sm">Reason: {label(record.reason)}</span></div><p className="text-sm">Source receipt: {record.receipt.receiptNumber} · {can(user, 'purchasing.VIEW') ? <Link className="font-semibold text-brand-600" to={`/procurement/purchase-orders/${record.purchaseOrder.id}`}>{record.purchaseOrder.poNumber}</Link> : record.purchaseOrder.poNumber}</p><p className="text-sm subtle">Created by {record.createdBy.firstName} {record.createdBy.lastName} · {shortDate(record.createdAt)}</p><p className="text-sm">{record.status === 'DRAFT' ? 'Draft: no stock held or removed.' : ['PENDING', 'APPROVED'].includes(record.status) ? 'Stock held at the warehouse until confirmed shipment or cancellation.' : record.status === 'CANCELLED' ? 'Cancelled: any return holds were released.' : 'Stock physically returned to the supplier. Completion records the supplier outcome.'}</p>{record.notes && <p className="whitespace-pre-wrap text-sm">{record.notes}</p>}{record.approvedBy && <p className="text-sm">Approved by {record.approvedBy.firstName} {record.approvedBy.lastName} · {shortDate(record.approvedAt)}</p>}{record.returnedAt && <p className="break-words text-sm">Shipped {shortDate(record.returnedAt)} · {record.shipmentReference}</p>}{record.completionNotes && <p className="whitespace-pre-wrap text-sm">Supplier outcome: {record.completionNotes} · {shortDate(record.completedAt)}</p>}</Card>
    <ServerTable rows={record.items} pagination={{ page: 1, total: record.items.length, totalPages: 1 }} onPage={() => {}} emptyTitle="No return items" columns={[
      { key: 'product', label: 'Product', render: item => <div className="min-w-48"><strong>{item.product.name}</strong><p className="text-xs subtle">{item.product.sku}</p></div> }, { key: 'quantity', label: 'Quantity' }, { key: 'reason', label: 'Reason', render: item => label(item.reason) }, { key: 'condition', label: 'Observed condition', render: item => label(item.condition) },
      { key: 'stockCondition', label: 'Source stock condition', render: item => item.product.trackSerialNumbers ? 'Exact serial conditions' : label(item.stockCondition) },
      { key: 'serials', label: 'Exact serials', render: item => <div className="min-w-48">{item.serialSelections.length ? item.serialSelections.map(selection => <p key={selection.serialNumberId} className="mb-1 break-all">{can(user, 'inventory.VIEW') ? <Link className="text-brand-600" to={`/serial-numbers/${selection.serialNumberId}`}>{selection.serialNumber.serialNumber}</Link> : selection.serialNumber.serialNumber}<span className="text-xs subtle"> · {label(selection.serialNumber.status)}</span></p>) : 'Quantity tracked'}</div> }
    ]}/>
    <Modal open={Boolean(decision)} onOpenChange={open => { if (!open && !pending) setDecision('') }} title={`${label(decision || 'review')} supplier return`} description={decision === 'ship' ? 'Confirm the goods have physically left this warehouse. This removes stock and cannot be cancelled.' : decision === 'submit' ? 'This holds the selected units without removing physical stock.' : `Confirm ${decision} for ${record.returnNumber}.`}><form onSubmit={act} className="space-y-4">{decision === 'ship' && <Field label="Shipment reference" required><input aria-label="Return shipment reference" className="field" required minLength={2} maxLength={191} value={shipment} onChange={event => setShipment(event.target.value)}/></Field>}<Field label={decision === 'complete' ? 'Supplier acknowledgement / credit outcome' : 'Action notes'} required={decision === 'complete'}><textarea aria-label="Return action notes" className="field" rows={3} required={decision === 'complete'} minLength={decision === 'complete' ? 3 : undefined} maxLength={4000} value={notes} onChange={event => setNotes(event.target.value)}/></Field>{error && <p role="alert" className="text-sm text-rose-600">{error}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="secondary" disabled={pending} onClick={() => setDecision('')}>Keep return</Button><Button type="submit" loading={pending}>Confirm {decision}</Button></div></form></Modal>
  </>
}
