import { testAccessToken } from './sessionFixture.js'
import { beforeAll, afterAll, describe, expect, it } from 'vitest'
import crypto from 'node:crypto'
import fs from 'node:fs/promises'
import path from 'node:path'

const bytes=Buffer.from('%PDF-1.4\n1 0 obj<</Type/Catalog>>endobj\n%%EOF\n')
describe.skipIf(!process.env.TEST_DATABASE_URL)('private attachments in disposable MySQL',()=>{
  let db, service, server, origin, f, folder, priorFolder
  const key=Date.now().toString(36), targets={}
  const req=user=>({user:f.users[user],get:()=>null}), input=(type,id,requestKey=crypto.randomUUID())=>({entityType:type,entityId:id,requestKey}), upload=(fileName='evidence.pdf',buffer=bytes)=>({originalname:fileName,mimetype:'application/pdf',buffer})
  const http=async(user,endpoint,body,method=body?'POST':'GET')=>{const r=await fetch(`${origin}/api/attachments${endpoint}`,{method,headers:{Authorization:`Bearer ${f.tokens[user]||''}`,...(body&&!(body instanceof FormData)?{'Content-Type':'application/json'}:{})},body:body instanceof FormData?body:body?JSON.stringify(body):undefined});return {status:r.status,headers:r.headers,body:r.headers.get('content-type')?.includes('application/json')?await r.json():Buffer.from(await r.arrayBuffer())}}
  const multipart=(requestKey=crypto.randomUUID(),fileName='evidence.pdf',buffer=bytes)=>{const form=new FormData();form.append('file',new Blob([buffer],{type:'application/pdf'}),fileName);form.append('requestKey',requestKey);return form}
  beforeAll(async()=>{
    const schema=new URL(process.env.TEST_DATABASE_URL).pathname.slice(1);if(!/^techstock_test_warehouse_[a-z0-9]+$/.test(schema))throw Error('Unsafe test schema');process.env.DATABASE_URL=process.env.TEST_DATABASE_URL
    db=(await import('../src/config/prisma.js')).prisma;service=await import('../src/services/attachmentService.js')
    folder=path.resolve('.test-runtime',`attachments-${schema}-${key}`);priorFolder=process.env.ATTACHMENT_STORAGE_DIR;process.env.ATTACHMENT_STORAGE_DIR=folder
    const a=await db.warehouse.create({data:{name:`Attachment A ${key}`,code:`AT-A-${key}`}}),b=await db.warehouse.create({data:{name:`Attachment B ${key}`,code:`AT-B-${key}`}}),c=await db.warehouse.create({data:{name:`Attachment C ${key}`,code:`AT-C-${key}`}})
    const modules=['attachments','products','suppliers','purchase_requests','rfqs','purchasing','supplier_returns','inventory','assets','warranty_claims'],full=modules.flatMap(m=>['VIEW','CREATE','EDIT','DELETE'].map(a=>`${m}.${a}`)),users={},tokens={}
    for(const [name,warehouses,grants] of [['writer',[a],full],['reader',[a],modules.map(m=>`${m}.VIEW`)],['outsider',[c],full],['destination',[b],full],['noSource',[a],['attachments.VIEW','attachments.CREATE','attachments.EDIT','attachments.DELETE']],['noAttachment',[a],['assets.VIEW','assets.EDIT']],['unassigned',[],full]]) {
      const role=await db.role.create({data:{name:`Attachment ${name} ${key}`}})
      for(const grant of grants){const [module,action]=grant.split('.'),p=await db.permission.upsert({where:{module_action:{module,action}},create:{module,action},update:{}});await db.rolePermission.create({data:{roleId:role.id,permissionId:p.id}})}
      const u=await db.user.create({data:{firstName:name,lastName:'Attachment',email:`attachment-${name}-${key}@test.invalid`,passwordHash:'unused',roleId:role.id,warehouseAssignments:{create:warehouses.map(w=>({warehouseId:w.id}))}}});users[name]={id:u.id,role:role.name,warehouseIds:warehouses.map(w=>w.id),permissions:grants};tokens[name]=await testAccessToken(db,u.id,process.env.JWT_ACCESS_SECRET)
    }
    f={a,b,c,users,tokens}
    const category=await db.category.create({data:{name:`Attachment ${key}`,slug:`at-${key}`}}),brand=await db.brand.create({data:{name:`Attachment ${key}`,slug:`at-${key}`}})
    const product=await db.product.create({data:{name:`Attachment equipment ${key}`,sku:`AT-${key}`,categoryId:category.id,brandId:brand.id}}),supplier=await db.supplier.create({data:{companyName:`Attachment supplier ${key}`,supplierCode:`AT-${key}`}})
    const order=await db.purchaseOrder.create({data:{poNumber:`AT-PO-${key}`,supplierId:supplier.id,warehouseId:a.id,createdById:users.writer.id,subtotal:0,total:0}}),receipt=await db.purchaseReceipt.create({data:{receiptNumber:`AT-RCV-${key}`,purchaseOrderId:order.id,warehouseId:a.id,receivedById:users.writer.id}})
    const pr=await db.purchaseRequest.create({data:{prNumber:`AT-PR-${key}`,warehouseId:a.id,requestedById:users.writer.id,department:'Acceptance',justification:'Attachment fixture'}}),rfq=await db.rFQ.create({data:{rfqNumber:`AT-RFQ-${key}`,warehouseId:a.id,createdById:users.writer.id}}),quote=await db.supplierQuotation.create({data:{quotationNumber:`AT-Q-${key}`,rfqId:rfq.id,supplierId:supplier.id,quotationDate:new Date(),subtotal:0,total:0}})
    const rtv=await db.supplierReturn.create({data:{returnNumber:`AT-RTV-${key}`,supplierId:supplier.id,purchaseOrderId:order.id,receiptId:receipt.id,warehouseId:a.id,createdById:users.writer.id,reason:'DEFECTIVE'}}),transfer=await db.stockTransfer.create({data:{transferNumber:`AT-TR-${key}`,sourceWarehouseId:a.id,destinationWarehouseId:b.id,requestedById:users.writer.id}}),asset=await db.asset.create({data:{assetTag:`AT-ASSET-${key}`,productId:product.id,warehouseId:a.id}}),maintenance=await db.maintenanceRecord.create({data:{assetId:asset.id,issue:`Inspection ${key}`,warehouseId:a.id}})
    const serial=await db.serialNumber.create({data:{serialNumber:`AT-SN-${key}`,productId:product.id,warehouseId:a.id}}),claim=await db.warrantyClaim.create({data:{claimNumber:`AT-WC-${key}`,serialNumberId:serial.id,activeSerialId:serial.id,warehouseId:a.id,supplierId:supplier.id,receiptId:receipt.id,warrantyStart:new Date(),warrantyEnd:new Date(Date.now()+86400000),issue:'Attachment fixture'}})
    Object.assign(targets,{Product:product.id,Supplier:supplier.id,PurchaseRequest:pr.id,RFQ:rfq.id,SupplierQuotation:quote.id,PurchaseOrder:order.id,PurchaseReceipt:receipt.id,SupplierReturn:rtv.id,StockTransfer:transfer.id,Asset:asset.id,MaintenanceRecord:maintenance.id,WarrantyClaim:claim.id})
    const {app}=await import('../src/app.js');server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));origin=`http://127.0.0.1:${server.address().port}`
  },30000)
  afterAll(async()=>{if(server)await new Promise(r=>server.close(r));if(db)await db.$disconnect();if(folder){const resolved=path.resolve(folder),root=path.resolve('.test-runtime');if(!resolved.startsWith(root+path.sep))throw Error('Unsafe fixture cleanup');await fs.rm(resolved,{recursive:true,force:true})}if(priorFolder===undefined)delete process.env.ATTACHMENT_STORAGE_DIR;else process.env.ATTACHMENT_STORAGE_DIR=priorFolder})
  it('uploads, lists and downloads every supported parent with audit and no storage keys',async()=>{
    for(const [type,id] of Object.entries(targets)){const row=await service.createAttachment(input(type,id),upload(),req('writer'));expect(row).not.toHaveProperty('storageKey');expect(row).not.toHaveProperty('sha256');expect((await service.listAttachments(type,id,{page:1},f.users.reader)).data.some(r=>r.id===row.id)).toBe(true);expect((await service.downloadAttachment(row.id,f.users.reader)).buffer.equals(bytes)).toBe(true)}
    expect(await db.activityLog.count({where:{userId:f.users.writer.id,action:'ATTACHMENT_UPLOADED'}})).toBe(12)
  })
  it('retains one row, one file and one audit on competing retries',async()=>{const data=input('Asset',targets.Asset),before=(await fs.readdir(folder)).length;const rows=await Promise.all([service.createAttachment(data,upload(),req('writer')),service.createAttachment(data,upload(),req('writer'))]);expect(rows[0].id).toBe(rows[1].id);expect((await fs.readdir(folder)).length).toBe(before+1);await expect(service.createAttachment(data,upload('other.pdf'),req('writer'))).rejects.toHaveProperty('status',409)})
  it('archives with retained bytes, rejects stale competition and restores exact download',async()=>{const row=await service.createAttachment(input('Asset',targets.Asset),upload(),req('writer')),body={expectedUpdatedAt:row.updatedAt.toISOString(),notes:'Archive superseded evidence'};const results=await Promise.allSettled([service.archiveAttachment(row.id,body,req('writer')),service.archiveAttachment(row.id,body,req('writer'))]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(results.find(r=>r.status==='rejected').reason.status).toBe(409);await expect(service.downloadAttachment(row.id,f.users.reader)).rejects.toHaveProperty('status',409);const current=await db.attachment.findUnique({where:{id:row.id}});expect((await fs.readFile(path.join(folder,current.storageKey))).equals(bytes)).toBe(true);expect((await service.listAttachments('Asset',targets.Asset,{page:1},f.users.reader)).data.some(r=>r.id===row.id)).toBe(false);await service.archiveAttachment(row.id,{expectedUpdatedAt:current.updatedAt.toISOString(),notes:'Restore retained evidence'},req('writer'),true);expect((await service.downloadAttachment(row.id,f.users.reader)).buffer.equals(bytes)).toBe(true)})
  it('requires attachment and parent VIEW and parent EDIT, independently of warehouse',async()=>{for(const user of ['noSource','noAttachment']){await expect(service.listAttachments('Asset',targets.Asset,{page:1},f.users[user])).rejects.toHaveProperty('status',403);await expect(service.createAttachment(input('Asset',targets.Asset),upload(),req(user))).rejects.toHaveProperty('status',403)}await expect(service.createAttachment(input('Asset',targets.Asset),upload(),req('reader'))).rejects.toHaveProperty('status',403)})
  it('enforces exact source warehouse, quote parent and transfer either-end access',async()=>{for(const type of Object.keys(targets).filter(t=>!['Product','Supplier'].includes(t)))for(const user of ['outsider','unassigned'])await expect(service.listAttachments(type,targets[type],{page:1},f.users[user])).rejects.toHaveProperty('status',403);expect((await service.listAttachments('StockTransfer',targets.StockTransfer,{page:1},f.users.destination)).data.length).toBeGreaterThan(0);await expect(service.listAttachments('SupplierQuotation',targets.SupplierQuotation,{page:1},f.users.destination)).rejects.toHaveProperty('status',403)})
  it('authorizes authenticated HTTP uploads before multipart parsing and downloads privately',async()=>{expect((await http('missing','/Asset/'+targets.Asset)).status).toBe(401);expect((await http('outsider','/Asset/'+targets.Asset,multipart())).status).toBe(403);expect((await http('writer','/Asset/'+targets.Asset,multipart(crypto.randomUUID(),'fake.pdf',Buffer.from('<html/>')))).status).toBe(400);const r=await http('writer','/Asset/'+targets.Asset,multipart());expect(r.status,JSON.stringify(r.body)).toBe(201);const downloaded=await http('reader','/files/'+r.body.data.id);expect(downloaded.status).toBe(200);expect(downloaded.headers.get('content-disposition')).toMatch(/^attachment;/);expect(downloaded.headers.get('cache-control')).toBe('private, no-store');expect(downloaded.headers.get('x-content-type-options')).toBe('nosniff');expect(downloaded.body.equals(bytes)).toBe(true);expect((await http('noSource','/files/'+r.body.data.id)).status).toBe(403)})
  it('supports scoped search, correct pagination and rejects unknown/missing targets',async()=>{const sources=await service.listAttachmentSources('Asset',{page:1,search:key},f.users.reader);expect(sources.data.map(r=>r.entityId)).toContain(targets.Asset);expect((await service.listAttachmentSources('Asset',{page:1,search:key},f.users.outsider)).data).toEqual([]);await expect(service.createAttachment(input('User',f.users.writer.id),upload(),req('writer'))).rejects.toHaveProperty('status',400);await expect(service.listAttachments('Asset','missing',{page:1},f.users.reader)).rejects.toHaveProperty('status',404);for(let i=0;i<21;i++)await service.createAttachment(input('Product',targets.Product),upload(`page-${i}.pdf`),req('writer'));const page=await service.listAttachments('Product',targets.Product,{page:2},f.users.reader);expect(page.pagination.total).toBe(22);expect(page.data).toHaveLength(2)})
  it('resolves the storage adapter URL through the real authorized download route',async()=>{
    const storage=await import('../src/services/storageService.js'),row=await service.createAttachment(input('Asset',targets.Asset),upload(),req('writer'))
    const url=storage.storageFor().getUrl(row.id)
    const response=await fetch(origin+url,{headers:{Authorization:'Bearer '+f.tokens.reader}})
    expect(response.status).toBe(200);expect(Buffer.from(await response.arrayBuffer()).equals(bytes)).toBe(true)
    const denied=await fetch(origin+url,{headers:{Authorization:'Bearer '+f.tokens.noSource}})
    expect(denied.status).toBe(403)
  })
  it('cleans its own file if metadata transaction fails',async()=>{const before=(await fs.readdir(folder)).length;await expect(service.createAttachment(input('Product',targets.Product),upload(),{...req('writer'),user:{...f.users.writer,id:'missing-user'}})).rejects.toHaveProperty('code','P2003');expect((await fs.readdir(folder)).length).toBe(before)})
  it('does not mutate inventory, custody, source documents or counters',async()=>{expect(await db.stockMovement.count({where:{productId:targets.Product}})).toBe(0);expect(await db.assetAssignment.count({where:{assetId:targets.Asset}})).toBe(0);expect((await db.asset.findUnique({where:{id:targets.Asset}})).status).toBe('AVAILABLE');expect((await db.purchaseOrder.findUnique({where:{id:targets.PurchaseOrder}})).status).toBe('DRAFT')})
  it('withholds unknown closed legacy service ownership from normal users',async()=>{const row=await db.maintenanceRecord.create({data:{assetId:targets.Asset,issue:'Unknown closed legacy service',status:'COMPLETED'}});await expect(service.listAttachments('MaintenanceRecord',row.id,{page:1},f.users.reader)).rejects.toHaveProperty('status',403)})
  it('preserves attachment parents when catalog deletion is requested, even after archive',async()=>{const catalog=await import('../src/services/catalogService.js'),source=await db.product.findUnique({where:{id:targets.Product}}),p=await db.product.create({data:{sku:`AT-DELETE-${key}`,name:'Retained attachment parent',categoryId:source.categoryId,brandId:source.brandId}}),supplier=await db.supplier.create({data:{supplierCode:`AT-DELETE-${key}`,companyName:`Retained attachment supplier ${key}`}});for(const [type,id] of [['Product',p.id],['Supplier',supplier.id]]){const row=await service.createAttachment(input(type,id),upload(),req('writer'));await service.archiveAttachment(row.id,{expectedUpdatedAt:row.updatedAt.toISOString(),notes:'Retain archived supporting evidence'},req('writer'))}expect((await catalog.deleteProduct(p.id,req('writer'))).archived).toBe(true);await expect(catalog.deleteCatalog('suppliers',supplier.id,req('writer'))).rejects.toHaveProperty('status',409);expect(await db.attachment.count({where:{entityId:{in:[p.id,supplier.id]}}})).toBe(2)})
  it('rejects oversized HTTP multipart bodies and unexpected fields before storing documents',async()=>{const tooBig=Buffer.alloc(10485761);bytes.copy(tooBig);expect((await http('writer','/Asset/'+targets.Asset,multipart(crypto.randomUUID(),'large.pdf',tooBig))).status).toBe(413);const form=multipart();form.append('unexpected','value');expect((await http('writer','/Asset/'+targets.Asset,form)).status).toBe(400)})
  it('rechecks revoked source-module permissions independently of warehouse access',async()=>{const row=await service.createAttachment(input('Asset',targets.Asset),upload(),req('writer'));expect((await http('writer','/files/'+row.id)).status).toBe(200);const user=await db.user.findUnique({where:{id:f.users.writer.id}}),permission=await db.permission.findUnique({where:{module_action:{module:'assets',action:'VIEW'}}});await db.rolePermission.delete({where:{roleId_permissionId:{roleId:user.roleId,permissionId:permission.id}}});expect((await http('writer','/files/'+row.id)).status).toBe(403)})
  it('rechecks current warehouse assignments on the next HTTP download',async()=>{const row=await service.createAttachment(input('Asset',targets.Asset),upload(),req('writer'));expect((await http('reader','/files/'+row.id)).status).toBe(200);await db.userWarehouse.deleteMany({where:{userId:f.users.reader.id}});expect((await http('reader','/files/'+row.id)).status).toBe(403)})
})
