import { testAccessToken } from './sessionFixture.js'
import { beforeAll,afterAll,describe,it,expect } from 'vitest'
import crypto from 'node:crypto'

describe.skipIf(!process.env.TEST_DATABASE_URL)('validated imports in disposable MySQL',()=>{
  let db,s,server,origin,f
  const stamp=Date.now().toString(36),req=(name='writer')=>({user:f.users[name],get:()=>null})
  const file=text=>({originalname:'records.csv',mimetype:'text/csv',buffer:Buffer.from(text)})
  const preview=(type,text,warehouseId)=>s.previewImport(type,{requestKey:crypto.randomUUID(),...(warehouseId?{warehouseId}:{})},file(text),req())
  const confirm=batch=>s.confirmImport(batch.id,{expectedRevision:batch.revision,notes:'Reviewed disposable import evidence'},req())
  const http=async(name,path,body)=>{const r=await fetch(`${origin}/api/imports${path}`,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${f.tokens[name]||''}`,...(body&&!(body instanceof FormData)?{'Content-Type':'application/json'}:{})},body:body instanceof FormData?body:body?JSON.stringify(body):undefined});return {status:r.status,headers:r.headers,body:r.headers.get('content-type')?.includes('application/json')?await r.json():await r.text()}}
  const productCsv=(sku,cost='12.34',extra='')=>`sku,name,categorySlug,brandSlug,purchaseCost\n${sku},${sku},${f.category.slug},${f.brand.slug},${cost}${extra}`
  const supplierCsv=(code,name=code)=>`supplierCode,companyName\n${code},${name}`
  const makeProduct=(suffix,serialized=false)=>db.product.create({data:{sku:`IM-${stamp}-${suffix}`,name:`Import ${stamp} ${suffix}`,categoryId:f.category.id,brandId:f.brand.id,trackSerialNumbers:serialized}})
  const stock=(product,quantity)=>db.warehouseStock.create({data:{productId:product.id,warehouseId:f.a.id,quantity}})
  beforeAll(async()=>{
    const schema=new URL(process.env.TEST_DATABASE_URL).pathname.slice(1);if(!/^techstock_test_warehouse_[a-z0-9]+$/.test(schema))throw Error('Unsafe schema');process.env.DATABASE_URL=process.env.TEST_DATABASE_URL
    db=(await import('../src/config/prisma.js')).prisma;s=await import('../src/services/importService.js')
    const a=await db.warehouse.create({data:{name:`Import A ${stamp}`,code:`IM-A-${stamp}`}}),b=await db.warehouse.create({data:{name:`Import B ${stamp}`,code:`IM-B-${stamp}`}}),category=await db.category.create({data:{name:`Import ${stamp}`,slug:`im-${stamp}`}}),brand=await db.brand.create({data:{name:`Import ${stamp}`,slug:`im-${stamp}`}}),users={},tokens={}
    const full=['imports.VIEW','imports.CREATE','imports.CONFIRM','products.VIEW','products.CREATE','suppliers.VIEW','suppliers.CREATE','inventory.VIEW','inventory.EDIT','assets.VIEW','assets.CREATE']
    for(const [name,warehouses,grants] of [['writer',[a],full],['reader',[a],full.filter(g=>g.endsWith('.VIEW'))],['other',[a],full],['outsider',[b],full],['noSource',[a],['imports.VIEW','imports.CREATE','imports.CONFIRM']],['noConfirm',[a],full.filter(g=>g!=='imports.CONFIRM')]]){
      const role=await db.role.create({data:{name:`Import ${name} ${stamp}`}})
      for(const grant of grants){const [module,action]=grant.split('.'),p=await db.permission.upsert({where:{module_action:{module,action}},create:{module,action},update:{}});await db.rolePermission.create({data:{roleId:role.id,permissionId:p.id}})}
      const u=await db.user.create({data:{firstName:name,lastName:'Import',email:`import-${name}-${stamp}@test.invalid`,passwordHash:'unused',roleId:role.id,warehouseAssignments:{create:warehouses.map(w=>({warehouseId:w.id}))}}});users[name]={id:u.id,role:role.name,permissions:grants,warehouseIds:warehouses.map(w=>w.id)};tokens[name]=await testAccessToken(db,u.id,process.env.JWT_ACCESS_SECRET)
    }
    f={a,b,category,brand,users,tokens}
    const {app}=await import('../src/app.js');server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));origin=`http://127.0.0.1:${server.address().port}`
  },30000)
  afterAll(async()=>{if(server)await new Promise(r=>server.close(r));if(db)await db.$disconnect()})
  it('stages valid product rows without masters, stock, movements or counter writes',async()=>{const sku=`PREVIEW-${stamp}`,before=await db.stockMovement.count(),counters=await db.counter.findMany();const b=await preview('Products',productCsv(sku));expect(b.summary).toEqual({totalRows:1,validRows:1,invalidRows:0});expect(await db.product.count({where:{sku}})).toBe(0);expect(await db.stockMovement.count()).toBe(before);expect(await db.counter.findMany()).toEqual(counters);expect(b).not.toHaveProperty('sha256');expect(b.rows[0]).not.toHaveProperty('fingerprint');const done=await confirm(b);expect(done.status).toBe('IMPORTED');expect((await db.product.findUnique({where:{sku}})).purchaseCost.toString()).toBe('12.34');expect(await db.warehouseStock.count({where:{productId:done.result[0].id}})).toBe(0)})
  it('creates suppliers with exact unique codes and refuses duplicate company names',async()=>{const code=`SUP-IM-${stamp}`,b=await preview('Suppliers',supplierCsv(code));await confirm(b);expect(await db.supplier.count({where:{supplierCode:code}})).toBe(1);const bad=await preview('Suppliers',supplierCsv(`SECOND-${stamp}`,code));expect(bad.summary.invalidRows).toBe(1)})
  it('reports invalid references, duplicate SKUs, money precision, boolean flags and missing fields without partial writes',async()=>{const sku=`BAD-${stamp}`,text=`sku,name,categorySlug,brandSlug,purchaseCost,trackSerialNumbers\n${sku},One,${f.category.slug},${f.brand.slug},1.001,false\n${sku},Two,${f.category.slug},${f.brand.slug},1,true\nREF-${stamp},Three,missing,${f.brand.slug},1,false\nBOOL-${stamp},Four,${f.category.slug},${f.brand.slug},1,yes\nEMPTY-${stamp},,${f.category.slug},${f.brand.slug},1,false`,b=await preview('Products',text);expect(b.summary.invalidRows).toBe(5);await expect(confirm(b)).rejects.toHaveProperty('status',409);expect(await db.product.count({where:{sku:{in:[sku,`REF-${stamp}`,`BOOL-${stamp}`,`EMPTY-${stamp}`]}}})).toBe(0);expect(await s.rejectedImportCsv(b.id,f.users.writer)).toContain('purchaseCost')})
  it('applies serialized opening stock through adjustments, movements and serial history',async()=>{const p=await makeProduct('opening',true),serials=[`IM-S1-${stamp}`,`IM-S2-${stamp}`],b=await preview('OpeningStock',`sku,warehouseCode,quantity,serialNumbers\n${p.sku},${f.a.code},2,${serials.join(';')}`,f.a.id);expect(b.summary.invalidRows).toBe(0);await confirm(b);expect((await db.warehouseStock.findUnique({where:{productId_warehouseId:{productId:p.id,warehouseId:f.a.id}}})).quantity).toBe(2);expect(await db.serialNumber.count({where:{productId:p.id}})).toBe(2);expect(await db.stockAdjustment.count({where:{productId:p.id,type:'OPENING_STOCK'}})).toBe(1);expect((await db.stockMovement.findFirst({where:{productId:p.id}})).quantity).toBe(2);expect(await db.serialEvent.count({where:{serial:{productId:p.id}}})).toBe(2)})
  it('rejects opening stock for existing stock/history and duplicate or mismatched serials',async()=>{const p=await makeProduct('opening-invalid',true);await stock(p,2);for(const [quantity,serials] of [['2','same;same'],['2','single'],['-2',''],['1.5','one'],['2',`A-${stamp};B-${stamp}`]]){const b=await preview('OpeningStock',`sku,warehouseCode,quantity,serialNumbers\n${p.sku},${f.a.code},${quantity},${serials}`,f.a.id);expect(b.summary.invalidRows).toBe(1)}})
  it('backfills serials into unreserved units without inventing quantity, receipts or warranties',async()=>{const p=await makeProduct('backfill',true);await stock(p,2);const b=await preview('SerialNumbers',`sku,warehouseCode,serialNumber\n${p.sku},${f.a.code},BF1-${stamp}\n${p.sku},${f.a.code},BF2-${stamp}`,f.a.id);expect(b.summary.invalidRows).toBe(0);const done=await confirm(b);const rows=await db.serialNumber.findMany({where:{productId:p.id}});expect(rows).toHaveLength(2);for(const serial of rows){expect(serial.warrantyStart).toBeNull();expect(serial.warrantyEnd).toBeNull();expect(serial.receiptId).toBeNull();expect(serial.purchaseOrderItemId).toBeNull()}expect((await db.warehouseStock.findFirst({where:{productId:p.id}})).quantity).toBe(2);expect(await db.stockMovement.count({where:{productId:p.id,quantity:0}})).toBe(2);expect(await db.serialEvent.count({where:{referenceType:'ImportBatch',referenceId:done.id}})).toBe(2);const invalid=await preview('SerialNumbers',`sku,warehouseCode,serialNumber\n${p.sku},${f.a.code},BF3-${stamp}`,f.a.id);expect(invalid.summary.invalidRows).toBe(1)})
  it('rejects backfill of held stock, foreign warehouses, duplicate serials and excessive allocation',async()=>{const p=await makeProduct('backfill-invalid',true);const balance=await stock(p,1);await db.warehouseStock.update({where:{id:balance.id},data:{reservedQuantity:1}});const b=await preview('SerialNumbers',`sku,warehouseCode,serialNumber\n${p.sku},${f.a.code},HOLD-${stamp}\n${p.sku},${f.b.code},FOREIGN-${stamp}`,f.a.id);expect(b.summary.invalidRows).toBe(2);await db.warehouseStock.update({where:{id:balance.id},data:{reservedQuantity:0}});const excess=await preview('SerialNumbers',`sku,warehouseCode,serialNumber\n${p.sku},${f.a.code},E1-${stamp}\n${p.sku},${f.a.code},E2-${stamp}\n${p.sku},${f.a.code},E2-${stamp}`,f.a.id);expect(excess.summary.invalidRows).toBe(2)})
  it('registers imported assets with original stock consumption and asset/serial events',async()=>{const p=await makeProduct('asset',true);await stock(p,1);const serial=await db.serialNumber.create({data:{serialNumber:`AS-${stamp}`,productId:p.id,warehouseId:f.a.id}}),b=await preview('Assets',`sku,warehouseCode,serialNumber,purchaseDate,notes\n${p.sku},${f.a.code},${serial.serialNumber},2026-09-30,Company equipment`,f.a.id);expect(b.summary.invalidRows).toBe(0);const done=await confirm(b),asset=await db.asset.findUnique({where:{id:done.result[0].id}});expect(asset.serialNumberId).toBe(serial.id);expect(asset.status).toBe('AVAILABLE');expect((await db.warehouseStock.findFirst({where:{productId:p.id}})).quantity).toBe(0);expect((await db.serialNumber.findUnique({where:{id:serial.id}})).warehouseId).toBeNull();expect(await db.assetEvent.count({where:{assetId:asset.id,type:'ASSET_CREATED'}})).toBe(1);expect(await db.assetAssignment.count({where:{assetId:asset.id}})).toBe(0)})
  it('rejects unavailable asset units, missing serials, bad dates and allocations beyond stock',async()=>{const p=await makeProduct('plain-asset',false);await stock(p,1);const b=await preview('Assets',`sku,warehouseCode,purchaseDate\n${p.sku},${f.a.code},2026-02-30\n${p.sku},${f.a.code},2026-02-28\n${p.sku},${f.a.code},2026-02-28`,f.a.id);expect(b.summary.invalidRows).toBe(2);await expect(confirm(b)).rejects.toHaveProperty('status',409);expect((await db.warehouseStock.findFirst({where:{productId:p.id}})).quantity).toBe(1)})
  it('rejects stale catalog dependencies and requires explicit revalidation and fresh revision',async()=>{const sku=`STALE-${stamp}`,b=await preview('Products',productCsv(sku));await db.brand.update({where:{id:f.brand.id},data:{description:'Changed after preview'}});await expect(confirm(b)).rejects.toHaveProperty('status',409);const fresh=await s.revalidateImport(b.id,{expectedRevision:b.revision},req());expect(fresh.revision).toBe(b.revision+1);await expect(confirm(b)).rejects.toHaveProperty('status',409);expect((await confirm(fresh)).status).toBe('IMPORTED')})
  it('deduplicates competing uploads and confirmations without duplicate rows or audits',async()=>{const input={requestKey:crypto.randomUUID()},sku=`RETRY-${stamp}`,csv=file(productCsv(sku)),previews=await Promise.all([s.previewImport('Products',input,csv,req()),s.previewImport('Products',input,csv,req())]);expect(previews[0].id).toBe(previews[1].id);await expect(s.previewImport('Suppliers',input,file(supplierCsv(`WRONG-${stamp}`)),req())).rejects.toHaveProperty('status',409);const results=await Promise.all([confirm(previews[0]),confirm(previews[0])]);expect(results[0].result).toEqual(results[1].result);expect(await db.product.count({where:{sku}})).toBe(1);expect(await db.activityLog.count({where:{entityId:previews[0].id,action:'IMPORTED'}})).toBe(1)})
  it('rolls back earlier row writes, counters and audit records if any later write fails',async()=>{const codes=[`ROLL1-${stamp}`,`ROLL2-${stamp}`],b=await preview('Suppliers',`supplierCode,companyName\n${codes[0]},${codes[0]}\n${codes[1]},${codes[1]}`),before=await db.activityLog.count();let calls=0;await expect(s.confirmImport(b.id,{expectedRevision:b.revision,notes:'Rollback evidence'}, {...req(),get:()=>{if(++calls===2)throw Error('Disposable injected second audit failure');return null}})).rejects.toThrow('Disposable injected');expect(await db.supplier.count({where:{supplierCode:{in:codes}}})).toBe(0);expect(await db.activityLog.count()).toBe(before);expect((await db.importBatch.findUnique({where:{id:b.id}})).status).toBe('PREVIEW');await confirm(b)})
  it('allows only one of competing batches to consume the same existing unit',async()=>{const p=await makeProduct('race',true);await stock(p,1);const a=await preview('SerialNumbers',`sku,warehouseCode,serialNumber\n${p.sku},${f.a.code},RACE1-${stamp}`,f.a.id),b=await preview('SerialNumbers',`sku,warehouseCode,serialNumber\n${p.sku},${f.a.code},RACE2-${stamp}`,f.a.id),results=await Promise.allSettled([confirm(a),confirm(b)]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(results.find(r=>r.status==='rejected').reason.status).toBe(409);expect(await db.serialNumber.count({where:{productId:p.id}})).toBe(1)})
  it('enforces owner, source, warehouse and confirmation permission independently',async()=>{const p=await makeProduct('scope'),b=await preview('OpeningStock',`sku,warehouseCode,quantity\n${p.sku},${f.a.code},1`,f.a.id);for(const name of ['reader','other','outsider','noSource','noConfirm'])await expect(s.confirmImport(b.id,{expectedRevision:b.revision,notes:'Scope verification'},req(name))).rejects.toHaveProperty('status',403);await expect(s.previewImport('OpeningStock',{warehouseId:f.b.id,requestKey:crypto.randomUUID()},file(`sku,warehouseCode,quantity\n${p.sku},${f.b.code},1`),req())).rejects.toHaveProperty('status',403);expect((await s.listImports({page:1},f.users.other)).data).toEqual([]);expect((await s.listImports({page:1},f.users.noSource)).data).toEqual([])})
  it('blocks expired previews without business writes',async()=>{const code=`EXPIRED-${stamp}`,b=await preview('Suppliers',supplierCsv(code));await db.importBatch.update({where:{id:b.id},data:{expiresAt:new Date(Date.now()-1000)}});await expect(confirm(b)).rejects.toHaveProperty('status',409);expect(await db.supplier.count({where:{supplierCode:code}})).toBe(0)})
  it('provides permission-aware reference codes without private contact fields',async()=>{const refs=await s.importReferenceCodes('Products','categories',{search:stamp,page:1},f.users.writer);expect(refs.data).toContainEqual({code:f.category.slug,name:f.category.name});const result=await http('writer','/reference-codes/Products/brands?search='+stamp);expect(result.status).toBe(200);expect(result.body.data).toContainEqual({code:f.brand.slug,name:f.brand.name});expect((await http('noSource','/reference-codes/Products/brands')).status).toBe(403);expect((await http('writer','/reference-codes/Products/users')).status).toBe(400)})
  it('checks serial uniqueness and count for new opening stock, case-insensitive duplicate SKUs, and scoped access revocation',async()=>{const p=await makeProduct('new-invalid-opening',true);for(const serials of ['same;same','single']){const b=await preview('OpeningStock',`sku,warehouseCode,quantity,serialNumbers\n${p.sku},${f.a.code},2,${serials}`,f.a.id);expect(b.summary.invalidRows).toBe(1)}const duplicate=await preview('Products',productCsv(`CASE-${stamp}`)+`\ncase-${stamp},Other,${f.category.slug},${f.brand.slug},1`);expect(duplicate.summary.invalidRows).toBe(1);const staged=await preview('OpeningStock',`sku,warehouseCode,quantity,serialNumbers\n${p.sku},${f.a.code},1,REVOKED-${stamp}`,f.a.id);await db.userWarehouse.deleteMany({where:{userId:f.users.writer.id}});expect((await http('writer',`/${staged.id}`)).status).toBe(403);expect((await http('writer',`/${staged.id}/confirm`,{expectedRevision:staged.revision,notes:'Warehouse revocation verification'})).status).toBe(403);await db.userWarehouse.create({data:{userId:f.users.writer.id,warehouseId:f.a.id}})})
  it('exposes authenticated HTTP staging, confirmation, paged rows and private downloads',async()=>{expect((await http('missing','/')).status).toBe(401);const form=new FormData();form.append('file',new Blob([supplierCsv(`HTTP-${stamp}`)],{type:'text/csv'}),'http.csv');form.append('requestKey',crypto.randomUUID());const response=await http('writer','/preview/Suppliers',form);expect(response.status,JSON.stringify(response.body)).toBe(201);const b=response.body.data;expect((await http('writer',`/${b.id}`)).body.data.status).toBe('PREVIEW');const result=await http('writer',`/${b.id}/confirm`,{expectedRevision:b.revision,notes:'HTTP explicit confirmation'});expect(result.status,JSON.stringify(result.body)).toBe(200);expect(result.body.data.status).toBe('IMPORTED');const report=await http('writer',`/${b.id}/rejected.csv`);expect(report.status).toBe(200);expect(report.headers.get('cache-control')).toBe('private, no-store');expect(report.headers.get('content-disposition')).toMatch(/^attachment;/);expect((await http('other',`/${b.id}/rejected.csv`)).status).toBe(403);expect((await http('noSource','/templates/Products')).status).toBe(403);expect((await http('reader','/preview/Suppliers',form)).status).toBe(403)})
  it('paginates staging rows and rejects permissions revoked on the next request',async()=>{const text='supplierCode,companyName\n'+Array.from({length:21},(_,i)=>`PAGE-${stamp}-${i},Import page ${stamp} ${i}`).join('\n'),b=await preview('Suppliers',text);expect(b.rows).toHaveLength(20);expect((await s.getImport(b.id,{page:2},f.users.writer)).rows).toHaveLength(1);const permission=await db.permission.findUnique({where:{module_action:{module:'imports',action:'CONFIRM'}}});const user=await db.user.findUnique({where:{id:f.users.writer.id}});await db.rolePermission.delete({where:{roleId_permissionId:{roleId:user.roleId,permissionId:permission.id}}});expect((await http('writer',`/${b.id}/confirm`,{expectedRevision:b.revision,notes:'Permission revocation evidence'})).status).toBe(403)})
})
