import { describe,it,expect } from 'vitest'
import { parseImportCsv,exportCsv,importDefinition } from '../src/services/importCsv.js'
import { importUpload,importConfirm } from '../src/validators/imports.js'
const file=text=>({originalname:'suppliers.csv',mimetype:'text/csv',buffer:Buffer.from(text)})
describe('bounded CSV import parsing',()=>{
  it('handles UTF-8 BOM, quoted commas, escaped quotes and newlines without dropping data',()=>{const rows=parseImportCsv('Suppliers',file('\ufeffsupplierCode,companyName,notes\r\nS1,"ACME, Inc","a ""quoted"" note\nand second line"\r\n'));expect(rows[0].values).toEqual({supplierCode:'S1',companyName:'ACME, Inc',notes:'a "quoted" note\nand second line'});expect(rows[0].rowNumber).toBe(2)})
  it('rejects duplicate, prototype, missing and unknown headers',()=>{for(const header of ['supplierCode,companyName,companyName','supplierCode,companyName,__proto__','companyName','supplierCode,companyName,stock'])expect(()=>parseImportCsv('Suppliers',file(header+'\n1,Name,x'))).toThrow();expect(()=>importDefinition('__proto__')).toThrow()})
  it('rejects malformed quoting and mismatched columns',()=>{for(const row of ['S1,"unterminated','S1,Name,extra','S1'])expect(()=>parseImportCsv('Suppliers',file('supplierCode,companyName\n'+row))).toThrow()})
  it('rejects empty, overlong, binary, invalid UTF-8, unsupported files and oversized content',()=>{for(const f of [file('supplierCode,companyName\n'),file(''),file('supplierCode,companyName\nS1,\0bad'),{...file('x'),originalname:'../e.csv'},{...file('x'),originalname:'e.xlsx'},{...file('x'),buffer:Buffer.from([0xc3,0x28])},{...file('x'),buffer:Buffer.alloc(1048577)}])expect(()=>parseImportCsv('Suppliers',f)).toThrow()})
  it('bounds data rows and cells without silently truncating a batch',()=>{expect(parseImportCsv('Suppliers',file('supplierCode,companyName\n'+Array.from({length:100},(_,i)=>`S${i},Name`).join('\n')))).toHaveLength(100);expect(()=>parseImportCsv('Suppliers',file('supplierCode,companyName\n'+Array.from({length:101},(_,i)=>`S${i},Name`).join('\n')))).toThrow();expect(()=>parseImportCsv('Suppliers',file('supplierCode,companyName\nS1,'+'x'.repeat(33000)))).toThrow()})
  it('escapes commas, quotes, newlines and spreadsheet formulas in rejected reports',()=>{const csv=exportCsv([['=HYPERLINK("x")','+1','-2','@SUM(A1)',' \t=CMD()','safe, text','a\nb']]);expect(csv).toContain('"\'=HYPERLINK(""x"")"');expect(csv).toContain('"\'+1"');expect(csv).toContain('"\'-2"');expect(csv).toContain('"\'@SUM(A1)"');expect(csv).toContain('"safe, text"');expect(csv).toContain('"a\nb"')})
  it('requires unique upload references, explicit integer revisions and confirmation reasons',()=>{expect(importUpload.safeParse({requestKey:'invalid'}).success).toBe(false);expect(importConfirm.safeParse({expectedRevision:1,notes:'yes'}).success).toBe(false);expect(importConfirm.safeParse({expectedRevision:'1',notes:'Import reviewed'}).success).toBe(false)})
})
