import { testAccessToken } from './sessionFixture.js'
import { beforeAll,afterAll,describe,it,expect } from 'vitest'
import { Prisma } from '@prisma/client'

describe.skipIf(!process.env.TEST_DATABASE_URL)('reports, preferences, audit and search in disposable MySQL',()=>{
  let db,reporting,saved,prefs,search,delivery,activity,notification,dashboard,server,origin,f
  const stamp=Date.now().toString(36),req=user=>({user,get:()=>null})
  async function http(user,path,body,method='PUT'){const r=await fetch(origin+'/api'+path,{method:body?method:'GET',headers:{Authorization:`Bearer ${f.tokens[user]||''}`,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});return {status:r.status,body:await r.json()}}
  beforeAll(async()=>{
    if(!/^\/techstock_test_warehouse_[a-z0-9]+$/.test(new URL(process.env.TEST_DATABASE_URL).pathname))throw Error('Unsafe disposable schema')
    process.env.DATABASE_URL=process.env.TEST_DATABASE_URL
    db=(await import('../src/config/prisma.js')).prisma
    ;[reporting,saved,prefs,search,delivery,activity,notification,dashboard]=await Promise.all(['enhancedReportService','savedReportService','preferenceService','searchService','notificationDelivery','activityService','notificationService','dashboardService'].map(name=>import(`../src/services/${name}.js`)))
    const a=await db.warehouse.create({data:{name:`Report A ${stamp}`,code:`RP-A-${stamp}`}}),b=await db.warehouse.create({data:{name:`Report B ${stamp}`,code:`RP-B-${stamp}`}}),category=await db.category.create({data:{name:`Report ${stamp}`,slug:`rp-${stamp}`}}),brand=await db.brand.create({data:{name:`Report ${stamp}`,slug:`rp-${stamp}`}}),supplier=await db.supplier.create({data:{companyName:`Report ${stamp}`,supplierCode:`RP-S-${stamp}`}})
    const full=['reports.VIEW','reports.EXPORT','inventory.VIEW','products.VIEW','products.EDIT','purchasing.VIEW','suppliers.VIEW','supplier_returns.VIEW','assets.VIEW','warranty_claims.VIEW','stock_counts.VIEW','purchase_requests.VIEW','rfqs.VIEW','users.VIEW','dashboard.VIEW'],users={},tokens={}
    for(const [name,grants,warehouses] of [['reader',full,[a]],['other',full,[a]],['foreign',full,[b]],['restricted',['reports.VIEW','inventory.VIEW'],[a]],['empty',full,[]]]){
      const role=await db.role.create({data:{name:`Reports ${name} ${stamp}`}})
      for(const key of grants){const [module,action]=key.split('.'),permission=await db.permission.upsert({where:{module_action:{module,action}},update:{},create:{module,action}});await db.rolePermission.create({data:{roleId:role.id,permissionId:permission.id}})}
      const u=await db.user.create({data:{firstName:name,lastName:'Reports',email:`rp-${name}-${stamp}@test.invalid`,passwordHash:'never-expose-report-credential',roleId:role.id,warehouseAssignments:{create:warehouses.map(w=>({warehouseId:w.id}))}}});users[name]={id:u.id,role:role.name,permissions:grants,warehouseIds:warehouses.map(w=>w.id)};tokens[name]=await testAccessToken(db,u.id,process.env.JWT_ACCESS_SECRET)
    }
    const p=await db.product.create({data:{sku:`RP-${stamp}`,barcode:`BAR-${stamp}`,name:`Report ${stamp}`,categoryId:category.id,brandId:brand.id,defaultSupplierId:supplier.id,purchaseCost:'0.10',reorderPoint:2}}),quiet=await db.product.create({data:{sku:`RP-QUIET-${stamp}`,name:`Quiet ${stamp}`,categoryId:category.id,brandId:brand.id,purchaseCost:'12.34'}})
    const adminRole=await db.role.upsert({where:{name:'Administrator'},update:{},create:{name:'Administrator'}})
    const admin=await db.user.create({data:{firstName:'Admin',lastName:'Reports',email:`rp-admin-${stamp}@test.invalid`,passwordHash:'never-expose-report-credential',roleId:adminRole.id}})
    users.admin={id:admin.id,role:'Administrator',permissions:[],warehouseIds:[]}
    await db.warehouseStock.createMany({data:[{productId:p.id,warehouseId:a.id,quantity:10},{productId:p.id,warehouseId:b.id,quantity:20},{productId:quiet.id,warehouseId:a.id,quantity:5}]})
    for(const [type,quantity,date] of [['OPENING_STOCK',10,'2026-01-01'],['CORRECTION',1,'2026-03-01'],['STOCK_OUT',-3,'2026-09-15'],['ASSET_ASSIGNMENT',-2,'2026-09-16'],['TRANSFER_OUT',-10,'2026-09-17'],['CORRECTION',-20,'2026-09-18']])await db.stockMovement.create({data:{productId:p.id,warehouseId:a.id,type,quantity,previousQuantity:10,newQuantity:10+quantity,referenceNumber:`RP-${type}-${stamp}`,userId:users.reader.id,createdAt:new Date(date)}})
    const po=await db.purchaseOrder.create({data:{poNumber:`RP-PO-${stamp}`,supplierId:supplier.id,warehouseId:a.id,createdById:users.reader.id,subtotal:1,total:1,orderDate:new Date('2026-09-01'),status:'APPROVED',items:{create:{productId:p.id,quantity:10,unitCost:'0.10',subtotal:1}}}})
    const receipt=await db.purchaseReceipt.create({data:{receiptNumber:`RP-RCV-${stamp}`,purchaseOrderId:po.id,warehouseId:a.id,receivedById:users.reader.id}})
    const line=await db.purchaseOrderItem.findFirstOrThrow({where:{purchaseOrderId:po.id}})
    const receiptItem=await db.purchaseReceiptItem.create({data:{receiptId:receipt.id,purchaseOrderItemId:line.id,productId:p.id,quantity:2}})
    await db.supplierReturn.create({data:{returnNumber:`RP-RTV-${stamp}`,supplierId:supplier.id,purchaseOrderId:po.id,receiptId:receipt.id,warehouseId:a.id,reason:'DEFECTIVE',createdById:users.reader.id,items:{create:{receiptItemId:receiptItem.id,productId:p.id,quantity:1,reason:'DEFECTIVE',condition:'DEFECTIVE'}}}})
    await db.purchaseRequest.create({data:{prNumber:`RP-PR-${stamp}`,warehouseId:a.id,requestedById:users.reader.id,department:'Reports',justification:'Disposable request'}})
    await db.stockCount.create({data:{countNumber:`RP-CNT-${stamp}`,warehouseId:a.id,createdById:users.reader.id,items:{create:{productId:p.id,expectedQuantity:10,countedQuantity:8,variance:-2}}}})
    const transfer=await db.stockTransfer.create({data:{transferNumber:`RP-TR-${stamp}`,sourceWarehouseId:a.id,destinationWarehouseId:b.id,requestedById:users.reader.id,items:{create:{productId:p.id,quantity:2}}},include:{items:true}})
    const arrival=await db.transferArrival.create({data:{referenceNumber:`RP-ARR-${stamp}`,transferId:transfer.id,receivedById:users.reader.id,notes:'Disposable discrepancy evidence',lines:[]}})
    await db.transferDiscrepancy.create({data:{transferId:transfer.id,transferItemId:transfer.items[0].id,arrivalId:arrival.id,kind:'MISSING',quantity:2,notes:'Disposable missing units'}})
    const rfq=await db.rFQ.create({data:{rfqNumber:`RP-RFQ-${stamp}`,warehouseId:a.id,createdById:users.reader.id}})
    const quote=await db.supplierQuotation.create({data:{quotationNumber:`RP-QUO-${stamp}`,rfqId:rfq.id,supplierId:supplier.id,subtotal:2,total:2,quotationDate:new Date('2026-09-01')}})
    const serial=await db.serialNumber.create({data:{serialNumber:`RP-SN-${stamp}`,productId:p.id,warehouseId:null,warrantyStart:new Date('2026-01-01'),warrantyEnd:new Date(Date.now()+5*86400000)}})
    const asset=await db.asset.create({data:{assetTag:`RP-AST-${stamp}`,productId:p.id,serialNumberId:serial.id,warehouseId:a.id}})
    await db.assetAssignment.createMany({data:[{assetId:asset.id,warehouseId:a.id,assignedTo:'Test custody',status:'RETURNED',returnedDate:new Date()},{assetId:asset.id,warehouseId:null,assignedTo:'Unknown historic custody',status:'RETURNED',returnedDate:new Date()}]})
    await db.maintenanceRecord.createMany({data:[{assetId:asset.id,warehouseId:a.id,issue:'Exact cost',cost:'19.99',status:'SCHEDULED',serviceDate:new Date(Date.now()-86400000)},{assetId:asset.id,warehouseId:null,issue:'Unknown historical warehouse',cost:99,status:'COMPLETED'}]})
    await db.preventiveMaintenancePlan.create({data:{assetId:asset.id,title:'Due plan',intervalDays:30,instructions:'Disposable inspection',nextDueAt:new Date(Date.now()-86400000)}})
    const claim=await db.warrantyClaim.create({data:{claimNumber:`RP-WC-${stamp}`,serialNumberId:serial.id,activeSerialId:serial.id,warehouseId:a.id,supplierId:supplier.id,receiptId:receipt.id,warrantyStart:new Date('2026-01-01'),warrantyEnd:new Date('2026-12-31'),issue:'Disposable issue'}})
    f={a,b,category,brand,supplier,p,quiet,users,tokens,po,receipt,rfq,quote,serial,asset,claim,transfer}
    server=(await import('../src/app.js')).app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));origin=`http://127.0.0.1:${server.address().port}`
  },30000)
  afterAll(async()=>{if(server)await new Promise(r=>server.close(r));if(db)await db.$disconnect()})
  const report=(kind,params={},user)=>reporting.enhancedReport(kind,{warehouse:f.a.id,...params},user||f.users.reader)
  it('serves all 23 report types and every supported ordering through real models',async()=>{const catalog=(await import('../src/services/reportCatalog.js')).reportCatalog;for(const [kind,spec]of Object.entries(catalog)){for(const sortBy of spec.sorts){const r=await report(kind,{sortBy});expect(r.pagination.total).toBeGreaterThanOrEqual(0);expect(r.columns).toEqual(spec.columns);expect(r.data.length).toBeLessThanOrEqual(20);expect(()=>JSON.stringify(r)).not.toThrow()}expect((await http('reader',`/reports/data/${kind}?warehouse=${f.a.id}`)).status).toBe(200)}},30000)
  it('calculates exact decimal values and applies warehouse filters to totals and pages',async()=>{const r=await report('inventory-valuation',{columns:'sku,value',sortBy:'sku',sortOrder:'asc',limit:1});expect(r.pagination.total).toBe(2);expect(r.data).toHaveLength(1);const all=await report('inventory-valuation');expect(all.data.find(r=>r.sku===f.p.sku).value).toBe('1.00');expect((await reporting.enhancedReport('warehouse-stock',{},f.users.empty)).data).toEqual([])})
  it('uses actual demand only, includes zero demand, and ranks globally before pagination',async()=>{const q={dateFrom:'2026-09-01',dateTo:'2026-09-30',limit:1};const fast=await report('fast-moving',q),slow=await report('slow-moving',q);expect(fast.data[0].sku).toBe(f.p.sku);expect(fast.data[0].demandUnits).toBe(5);expect(slow.data[0].sku).toBe(f.quiet.sku);expect(slow.data[0].demandUnits).toBe(0)})
  it('reports recorded count variances, supplier returns and endpoint-scoped discrepancies',async()=>{expect((await report('cycle-count-variance')).data[0].variance).toBe(-2);expect((await report('supplier-return')).data[0].units).toBe(1);const cases=await report('transfer-discrepancy');expect(cases.data[0].quantity).toBe(2);expect((await reporting.enhancedReport('transfer-discrepancy',{warehouse:f.b.id},f.users.foreign)).data[0].reference).toBe(f.transfer.transferNumber)})
  it('keeps unknown aging, warranties and historical warehouse snapshots unknown',async()=>{const aging=await report('inventory-aging');expect(aging.data.find(r=>r.sku===f.quiet.sku).ageDays).toBeNull();expect(aging.data.find(r=>r.sku===f.p.sku).lastInbound).toBe('2026-03-01');expect((await report('asset-assignment-history')).data.map(r=>r.assignedTo)).toEqual(['Test custody']);expect((await report('asset-maintenance-cost')).data.map(r=>r.cost)).toEqual(['19.99'])})
  it('requires both report and source access and rechecks HTTP permissions',async()=>{expect((await http('restricted','/reports/data/inventory-valuation')).status).toBe(403);expect((await http('restricted','/reports/data/supplier-performance')).status).toBe(403);expect((await http('reader','/reports/data/warehouse-stock?warehouse='+f.b.id)).status).toBe(403);expect((await http('missing','/reports/catalog')).status).toBe(401);expect((await http('reader','/reports/data/rfq?dateFrom=2026-02-30')).status).toBe(400)})
  it('enforces EXPORT independently of report viewing',async()=>{expect((await http('restricted','/reports/data/stock-movement')).status).toBe(200);expect((await http('restricted','/reports/export/stock-movement')).status).toBe(403);expect((await http('reader','/reports/export/stock-movement')).status).toBe(200)})
  it('owns saved configurations, validates their contracts and prevents lost updates',async()=>{const input={name:'Monthly warehouse',reportType:'stock-movement',filters:{warehouse:f.a.id},columns:['quantity','sku'],sortBy:'createdAt',sortOrder:'desc',expectedRevision:0},r=await saved.saveReport(null,input,f.users.reader);expect(r.revision).toBe(1);expect(await saved.savedReports(f.users.other)).toEqual([]);await expect(saved.saveReport(r.id,{...input,expectedRevision:1},f.users.other)).rejects.toHaveProperty('status',409);const next=await saved.saveReport(r.id,{...input,name:'Changed',expectedRevision:1},f.users.reader);expect(next.revision).toBe(2);await expect(saved.saveReport(r.id,{...input,expectedRevision:1},f.users.reader)).rejects.toHaveProperty('status',409);await saved.archiveReport(r.id,{expectedRevision:2},f.users.reader);expect(await saved.savedReports(f.users.reader)).toEqual([])})
  it('returns preference defaults without writing rows and scopes default warehouses',async()=>{const current=await prefs.getPreferences(f.users.reader);expect(current.revision).toBe(0);expect(await db.userPreference.count({where:{userId:f.users.reader.id}})).toBe(0);await expect(prefs.updatePreferences({notifications:current.notifications,expectedRevision:0,dashboard:{...current.dashboard,defaultWarehouseId:f.b.id}},f.users.reader)).rejects.toHaveProperty('status',403);const v={expectedRevision:0,notifications:current.notifications,dashboard:{...current.dashboard,defaultWarehouseId:f.a.id,cards:['low','value'],charts:['category','movement'],defaultPeriod:'7d'}};const savedPref=await prefs.updatePreferences(v,f.users.reader);expect(savedPref.dashboard).toEqual(v.dashboard);await expect(prefs.updatePreferences(v,f.users.reader)).rejects.toHaveProperty('status',409);expect((await prefs.getPreferences(f.users.other)).revision).toBe(0)})
  it('ignores unavailable saved defaults without granting scope',async()=>{const user={...f.users.reader,warehouseIds:[]},r=await prefs.getPreferences(user);expect(r.effectiveWarehouseId).toBeNull();expect(r.warehouseWarning).toMatch(/no longer available/);expect((await dashboard.summary(user)).totalInventoryUnits).toBe(0);await expect(dashboard.summary(user,f.a.id)).rejects.toHaveProperty('status',403)})
  it('suppresses disabled deliveries and hides retained history with current preferences',async()=>{const row={userId:f.users.reader.id,warehouseId:f.a.id,type:'LOW_STOCK',title:'Low',message:'Disposable',referenceType:'Product',referenceId:f.p.id};expect((await delivery.deliverNotifications(db,[row])).count).toBe(1);let current=await prefs.getPreferences(f.users.reader);await prefs.updatePreferences({expectedRevision:current.revision,notifications:{...current.notifications,lowStock:false},dashboard:current.dashboard},f.users.reader);expect((await delivery.deliverNotifications(db,[row])).count).toBe(0);expect(await db.notification.count({where:await delivery.notificationWhere(db,f.users.reader)})).toBe(0);expect(await db.notification.count({where:{userId:f.users.reader.id,type:'LOW_STOCK'}})).toBe(1);expect((await delivery.deliverNotifications(db,[{...row,userId:f.users.foreign.id}])).count).toBe(0)})
  it('delivers out-of-stock after an earlier low-stock alert and honors global delivery switches',async()=>{const inventory=await import('../src/services/inventoryService.js'),p=await db.product.create({data:{sku:`RP-ALERT-${stamp}`,name:'Alert test',categoryId:f.category.id,brandId:f.brand.id,reorderPoint:2}});await db.warehouseStock.create({data:{productId:p.id,warehouseId:f.a.id,quantity:3}});for(const [delta,referenceNumber]of [[-1,'RP-LOW-'+stamp],[-2,'RP-OUT-'+stamp]])await inventory.inventoryTransaction(tx=>inventory.changeStock(tx,{productId:p.id,warehouseId:f.a.id,delta,type:'STOCK_OUT',referenceNumber,userId:f.users.admin.id}));expect((await db.notification.findMany({where:{userId:f.users.admin.id,referenceId:p.id},orderBy:{createdAt:'asc'}})).map(r=>r.type)).toEqual(['LOW_STOCK','OUT_OF_STOCK']);await db.systemSetting.upsert({where:{key:'lowStockNotifications'},create:{key:'lowStockNotifications',value:'false'},update:{value:'false'}});expect((await delivery.deliverNotifications(db,[{userId:f.users.admin.id,warehouseId:f.a.id,type:'LOW_STOCK',title:'Disabled global alert',message:'Disposable'}])).count).toBe(0);await db.systemSetting.update({where:{key:'lowStockNotifications'},data:{value:'true'}})})
  it('deduplicates due maintenance and warranty reminders from real records',async()=>{await notification.ensureUserNotifications(f.users.reader);const before=await db.notification.count({where:{userId:f.users.reader.id}});await notification.ensureUserNotifications(f.users.reader);expect(await db.notification.count({where:{userId:f.users.reader.id}})).toBe(before);expect(await db.notification.count({where:{userId:f.users.reader.id,type:'MAINTENANCE_DUE'}})).toBe(2);expect(await db.notification.count({where:{userId:f.users.reader.id,type:'WARRANTY_EXPIRING'}})).toBe(1)})
  it('searches all requested document types and returns routes without private contact/auth fields',async()=>{const r=await search.search({q:stamp},f.users.reader);const types=r.groups.map(g=>g.type);for(const type of ['Product','Serial number','Asset','Supplier','Purchase request','RFQ','Quotation','Purchase order','Receipt','Transfer','Warranty claim'])expect(types).toContain(type);expect(r.data.find(r=>r.type==='Receipt').route).toBe('/procurement/receipts/'+f.receipt.id);expect(JSON.stringify(r)).not.toMatch(/passwordHash|test.invalid|never-expose/);expect((await search.search({q:stamp},f.users.restricted)).groups.map(g=>g.type)).toEqual(['Serial number','Transfer'])})
  it('withholds foreign search records and marks per-type result truncation explicitly',async()=>{expect((await search.search({q:'RP-PO-'+stamp},f.users.foreign)).data).toEqual([]);for(let i=0;i<4;i++)await db.product.create({data:{sku:`RP-PAGE-${stamp}-${i}`,name:`Pages ${stamp}`,categoryId:f.category.id,brandId:f.brand.id}});const r=await search.search({q:stamp,perType:1},f.users.reader);expect(r.groups.find(g=>g.type==='Product').hasMore).toBe(true);expect(r.groups.find(g=>g.type==='Product').results).toHaveLength(1);expect((await http('reader','/search?q=x')).status).toBe(400)})
  it('records safe product diffs and retains audit scope on list and detail',async()=>{const catalog=await import('../src/services/catalogService.js');await catalog.updateProduct(f.p.id,{purchaseCost:0.20,reorderPoint:10},req(f.users.reader));const log=await db.activityLog.findFirst({where:{entityId:f.p.id,action:'UPDATED'},orderBy:{createdAt:'desc'}});expect(log.changes).toContainEqual({field:'purchaseCost',before:'0.10',after:'0.20'});await expect(activity.activityDetail(log.id,f.users.reader)).rejects.toHaveProperty('status',404);const scoped=await db.activityLog.create({data:{userId:f.users.reader.id,warehouseId:f.a.id,action:'TEST',module:'Inventory',description:'Disposable safe audit',changes:[{field:'quantity',before:1,after:2}]}});expect((await activity.activityDetail(scoped.id,f.users.reader)).changes).toHaveLength(1);await expect(activity.activityDetail(scoped.id,f.users.foreign)).rejects.toHaveProperty('status',404);expect((await http('reader','/activity-logs?search=Disposable%20safe%20audit')).body.data).toHaveLength(1)})
  it('makes dashboard queries honor selected warehouses and receipt reads honor warehouse grants',async()=>{expect((await dashboard.summary(f.users.reader,f.a.id)).totalInventoryUnits).toBe(15);expect((await dashboard.movements('1y',f.users.reader,f.a.id)).reduce((n,r)=>n+r.stockOut,0)).toBe(38);expect((await http('reader','/receipts/'+f.receipt.id)).status).toBe(200);expect((await http('foreign','/receipts/'+f.receipt.id)).status).toBe(404)})
  it('applies revoked module and warehouse grants on the next HTTP request',async()=>{const u=await db.user.findUnique({where:{id:f.users.other.id}}),permission=await db.permission.findUnique({where:{module_action:{module:'rfqs',action:'VIEW'}}});await db.rolePermission.delete({where:{roleId_permissionId:{roleId:u.roleId,permissionId:permission.id}}});expect((await http('other','/reports/data/rfq')).status).toBe(403);expect((await http('other','/search?q='+stamp)).body.data.some(r=>r.type==='RFQ'||r.type==='Quotation')).toBe(false);await db.userWarehouse.deleteMany({where:{userId:u.id}});expect((await http('other','/receipts/'+f.receipt.id)).status).toBe(404);expect((await http('other','/reports/data/warehouse-stock')).body.data).toEqual([])})
})
