import { describe,it,expect } from 'vitest'
import { Prisma } from '@prisma/client'
import { safeAuditChanges } from '../src/utils/auditChanges.js'
import { reportOptions } from '../src/services/enhancedReportService.js'
import { accessibleReports } from '../src/services/reportCatalog.js'
import { defaultDashboard,defaultNotifications,preferencesSchema } from '../src/validators/preferences.js'
const admin={role:'Administrator'},reader={role:'Reader',permissions:['reports.VIEW','inventory.VIEW'],warehouseIds:['own']}
describe('report contracts and safe audit changes',()=>{
  it('captures exact decimal and threshold changes without credential fields',()=>{const diff=safeAuditChanges('Product',{purchaseCost:new Prisma.Decimal('4500'),reorderPoint:5,password:'old',passwordHash:'hash',token:'old'},{purchaseCost:new Prisma.Decimal('4750'),reorderPoint:10,password:'new',passwordHash:'hash2',token:'new'});expect(diff).toEqual([{field:'reorderPoint',before:5,after:10},{field:'purchaseCost',before:'4500.00',after:'4750.00'}])})
  it('never snapshots unknown objects, notes or authentication secrets',()=>{expect(safeAuditChanges('RefreshToken',{tokenHash:'a'},{tokenHash:'b'})).toEqual([]);expect(safeAuditChanges('User',{passwordHash:'a',email:'a',notes:'secret'},{passwordHash:'b',email:'b',notes:'secret2'})).toEqual([]);expect(safeAuditChanges('User',{status:'ACTIVE'},{status:'INACTIVE',passwordHash:'hidden'})).toEqual([{field:'status',before:'ACTIVE',after:'INACTIVE'}]);expect(safeAuditChanges('Product',undefined,{})).toBeNull()})
  it('lists only reports whose source permissions are granted',()=>{const names=accessibleReports(reader).map(r=>r.kind);expect(names).toContain('slow-moving');expect(names).not.toContain('inventory-valuation');expect(names).not.toContain('supplier-performance');expect(accessibleReports(admin)).toHaveLength(23)})
  it('rejects impossible calendar dates, backwards windows and unsupported filters',()=>{for(const q of [{dateFrom:'2026-02-30'},{dateFrom:'2026-10-02',dateTo:'2026-10-01'},{dateFrom:'not a date'},{supplier:'x'}])expect(()=>reportOptions('rfq',q,admin)).toThrow();expect(()=>reportOptions('inventory-valuation',{dateFrom:'2026-01-01'},admin)).toThrow()})
  it('rejects unassigned warehouses, unsupported sorts and duplicate or unknown columns',()=>{for(const q of [{warehouse:'foreign'},{sortBy:'passwordHash'},{columns:'sku,sku'},{columns:'passwordHash'}])expect(()=>reportOptions('slow-moving',q,reader)).toThrow()})
  it('uses a resolved 90-day default demand window and UTC boundaries',()=>{const {q}=reportOptions('slow-moving',{dateTo:'2026-10-01'},reader);expect(q.dateFrom).toBe('2026-07-04');expect(q.sortBy).toBe('demandUnits');expect(q.sortOrder).toBe('asc')})
  it('accepts selected column order and rejects pagination overflow',()=>{expect(reportOptions('stock-movement',{columns:'quantity,sku'},reader).columns).toEqual(['quantity','sku']);for(const q of [{limit:101},{page:0},{page:'1oops'},{sortOrder:'sideways'},{unexpected:'value'}])expect(()=>reportOptions('stock-movement',q,reader)).toThrow()})
  it('validates preferences strictly without adding email or arbitrary business data',()=>{const v={expectedRevision:0,notifications:defaultNotifications(),dashboard:defaultDashboard()};expect(preferencesSchema.parse(v)).toEqual(v);expect(()=>preferencesSchema.parse({...v,email:true})).toThrow();expect(()=>preferencesSchema.parse({...v,dashboard:{...v.dashboard,cards:['units','units']}})).toThrow();expect(()=>preferencesSchema.parse({...v,dashboard:{...v.dashboard,defaultPeriod:'forever'}})).toThrow();expect(()=>preferencesSchema.parse({...v,notifications:{...v.notifications,SMTP_PASSWORD:'hidden'}})).toThrow()})
})
