import { beforeAll,afterAll,describe,it,expect } from 'vitest'
import bcrypt from 'bcrypt'
import jwt from 'jsonwebtoken'
import crypto from 'node:crypto'
describe.skipIf(!process.env.TEST_DATABASE_URL)('session security with disposable MySQL',()=>{
  let db,auth,service,server,origin,users={}
  const req=user=>({user:{id:user.id,role:user.role.name},sessionId:null,ip:'127.0.0.1',get:()=> 'Integration browser'})
  const response=()=>{let cookie;return {cookie:(name,value)=>{cookie=value},clearCookie:()=>{},get token(){return cookie}}}
  async function sign(user){const res=response(),r=await auth.login({email:user.email,password:'SessionTest123!',remember:false},res,req(user));return {...r,refresh:res.token,sid:jwt.decode(r.accessToken).sid}}
  async function http(token,path,body){const r=await fetch(origin+'/api'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});return {status:r.status,body:await r.json()}}
  beforeAll(async()=>{
    process.env.DATABASE_URL=process.env.TEST_DATABASE_URL
    db=(await import('../src/config/prisma.js')).prisma;auth=await import('../src/services/authService.js');service=await import('../src/services/sessionService.js')
    const stamp=Date.now().toString(36),hash=await bcrypt.hash('SessionTest123!',4)
    for(const name of ['member','other','admin','locked','password','reset','deactivated']){
      const role=await db.role.upsert({where:{name:name==='admin'?'Administrator':`Session ${name} ${stamp}`},create:{name:name==='admin'?'Administrator':`Session ${name} ${stamp}`},update:{}})
      users[name]=await db.user.create({data:{firstName:name,lastName:'Session',email:`session-${name}-${stamp}@test.invalid`,passwordHash:hash,roleId:role.id},include:{role:true}})
    }
    server=(await import('../src/app.js')).app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));origin=`http://127.0.0.1:${server.address().port}`
  },30000)
  afterAll(async()=>{if(server)await new Promise(r=>server.close(r));if(db)await db.$disconnect()})
  it('lists metadata, current session and pagination without exposing token hashes',async()=>{const s=await sign(users.member),r=await http(s.accessToken,'/sessions');expect(r.status).toBe(200);expect(r.body.data[0]).toMatchObject({id:s.sid,current:true,userAgent:'Integration browser'});expect(JSON.stringify(r.body)).not.toMatch(/refreshTokenHash|passwordHash|authVersion/);expect((await http(s.accessToken,'/sessions?page=-1')).status).toBe(400)})
  it('keeps the same session during rotation and allows only one concurrent refresh',async()=>{const s=await sign(users.member),results=await Promise.allSettled([auth.refresh({cookies:{techstock_refresh:s.refresh}},response()),auth.refresh({cookies:{techstock_refresh:s.refresh}},response())]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(jwt.decode(results.find(r=>r.status==='fulfilled').value.accessToken).sid).toBe(s.sid);expect((await db.session.findUnique({where:{id:s.sid}})).refreshTokenHash).not.toBe(auth.refreshHash(s.refresh))})
  it('revocation invalidates both access and refresh immediately and enforces ownership',async()=>{const a=await sign(users.member),b=await sign(users.other);expect((await http(b.accessToken,`/sessions/${a.sid}/revoke`,{})).status).toBe(404);expect((await http(a.accessToken,`/sessions/${a.sid}/revoke`,{})).status).toBe(200);expect((await http(a.accessToken,'/auth/me')).status).toBe(401);await expect(auth.refresh({cookies:{techstock_refresh:a.refresh}},response())).rejects.toHaveProperty('status',401)})
  it('signs out others while preserving the current session, with administrator-only account controls',async()=>{const a=await sign(users.member),b=await sign(users.member);expect((await http(a.accessToken,'/sessions/others/revoke',{})).status).toBe(200);expect((await http(b.accessToken,'/auth/me')).status).toBe(401);expect((await http(a.accessToken,'/auth/me')).status).toBe(200);expect((await http(a.accessToken,`/sessions/users/${users.other.id}`)).status).toBe(403);const admin=await sign(users.admin);expect((await http(admin.accessToken,`/sessions/users/${users.member.id}/revoke`,{confirmation:'wrong'})).status).toBe(400);expect((await http(admin.accessToken,`/sessions/users/${users.member.id}/revoke`,{confirmation:'REVOKE ALL SESSIONS'})).status).toBe(200);expect((await http(a.accessToken,'/auth/me')).status).toBe(401)})
  it('commits failed attempts, locks after five, rejects correct passwords during lockout and allows admin unlock',async()=>{for(let i=0;i<5;i++)await expect(auth.login({email:users.locked.email,password:'wrong'},response())).rejects.toHaveProperty('status',401);const u=await db.user.findUnique({where:{id:users.locked.id}});expect(u.failedLoginCount).toBe(5);expect(u.lockedUntil>new Date()).toBe(true);await expect(sign(users.locked)).rejects.toHaveProperty('status',401);await service.unlockAccount(u.id,req(users.admin));expect((await sign(users.locked)).accessToken).toBeTruthy();expect((await db.user.findUnique({where:{id:u.id}})).failedLoginCount).toBe(0)})
  it('password change invalidates all existing sessions and does not expose credentials in audit',async()=>{const s=await sign(users.password);await auth.changePassword(users.password.id,'SessionTest123!','NewSessionTest123!',response());expect((await http(s.accessToken,'/auth/me')).status).toBe(401);await expect(auth.refresh({cookies:{techstock_refresh:s.refresh}},response())).rejects.toHaveProperty('status',401);expect(await db.session.count({where:{userId:users.password.id,revokedAt:null}})).toBe(0)})
  it('converts a legacy refresh once and rejects legacy access or wrong-purpose tokens',async()=>{const token=jwt.sign({sub:users.other.id,jti:crypto.randomUUID()},process.env.JWT_REFRESH_SECRET,{expiresIn:'1h'});await db.refreshToken.create({data:{userId:users.other.id,tokenHash:auth.refreshHash(token),expiresAt:new Date(Date.now()+3600000)}});const r=await auth.refresh({cookies:{techstock_refresh:token}},response());expect(jwt.decode(r.accessToken).type).toBe('access');await expect(auth.refresh({cookies:{techstock_refresh:token}},response())).rejects.toHaveProperty('status',401);expect((await http(jwt.sign({sub:users.other.id},process.env.JWT_ACCESS_SECRET,{expiresIn:'10m'}),'/auth/me')).status).toBe(401);expect((await http(jwt.sign({sub:users.other.id,sid:jwt.decode(r.accessToken).sid,ver:0,type:'refresh'},process.env.JWT_ACCESS_SECRET),'/auth/me')).status).toBe(401)})
  it('administrator reset and deactivation invalidate access even after reactivation',async()=>{const management=await import('../src/services/managementService.js'),a=await sign(users.reset),b=await sign(users.deactivated);await management.resetPassword(users.reset.id,'ResetSessionTest123!',req(users.admin));expect((await http(a.accessToken,'/auth/me')).status).toBe(401);await management.changeUserStatus(users.deactivated.id,'INACTIVE',req(users.admin));await management.changeUserStatus(users.deactivated.id,'ACTIVE',req(users.admin));expect((await http(b.accessToken,'/auth/me')).status).toBe(401);await expect(auth.refresh({cookies:{techstock_refresh:b.refresh}},response())).rejects.toHaveProperty('status',401)})
  it('logout using an earlier rotated cookie revokes the same current session',async()=>{const a=await sign(users.other),r=await auth.refresh({cookies:{techstock_refresh:a.refresh}},response());await auth.logout({cookies:{techstock_refresh:a.refresh}},response());expect((await http(r.accessToken,'/auth/me')).status).toBe(401)})
})
