import { HttpError } from '../utils/http.js'

const cols = text => text.split('|').map(part => { const [key, label] = part.split(':'); return { key, label } })
const stockColumns = 'sku:SKU|product:Product|warehouse:Warehouse|quantity:Units|available:Available|cost:Unit cost|value:Value'
const productFilters = ['warehouse','category','brand','supplier']
const dated = ['warehouse','dateFrom','dateTo']
const spec = (label, permissions, columns, filters, sorts, basis, defaultSort = sorts[0], defaultOrder = 'desc') => ({ label, permissions, columns: cols(columns), filters, sorts, basis, defaultSort, defaultOrder })
export const reportCatalog = {
  'inventory-summary': spec('Inventory Summary', ['inventory.VIEW'], stockColumns, productFilters, ['sku','quantity','value'], 'Current balances, one row per product and warehouse.', 'sku','asc'),
  'warehouse-stock': spec('Warehouse Stock', ['inventory.VIEW'], stockColumns, productFilters, ['sku','quantity','value'], 'Current physical and available balances.', 'sku','asc'),
  'inventory-valuation': spec('Inventory Valuation', ['inventory.VIEW','products.VIEW'], stockColumns, productFilters, ['sku','quantity','value'], 'Current physical units × current product purchase cost. This is not a historical valuation.', 'value'),
  'inventory-aging': spec('Inventory Aging', ['inventory.VIEW'], stockColumns+'|lastInbound:Last recorded inbound|ageDays:Days since inbound', productFilters, ['sku','quantity','ageDays'], 'Days since the most recent recorded positive stock movement; unknown when no inbound is recorded. This does not reconstruct lot age.', 'ageDays'),
  'slow-moving': spec('Slow Moving Items', ['inventory.VIEW'], stockColumns+'|demandUnits:Demand units', [...productFilters,'dateFrom','dateTo'], ['demandUnits','sku','quantity'], 'Demand is negative STOCK_OUT and ASSET_ASSIGNMENT only. Transfers, returns, corrections and damage are excluded. Includes stocked items with zero demand.', 'demandUnits','asc'),
  'fast-moving': spec('Fast Moving Items', ['inventory.VIEW'], stockColumns+'|demandUnits:Demand units', [...productFilters,'dateFrom','dateTo'], ['demandUnits','sku','quantity'], 'Demand is negative STOCK_OUT and ASSET_ASSIGNMENT in the selected UTC window. Transfers, returns, corrections and damage are excluded.', 'demandUnits'),
  'low-stock': spec('Low Stock', ['inventory.VIEW'], stockColumns, productFilters, ['sku','quantity'], 'Current available units above zero and at or below reorder point (or minimum stock).', 'sku','asc'),
  'out-of-stock': spec('Out of Stock', ['inventory.VIEW'], stockColumns, productFilters, ['sku','quantity'], 'Current available units equal to zero.', 'sku','asc'),
  'stock-movement': spec('Stock Movement', ['inventory.VIEW'], 'reference:Reference|sku:SKU|warehouse:Warehouse|type:Type|quantity:Change|previous:Before|current:After|createdAt:Recorded', [...productFilters,'dateFrom','dateTo'], ['createdAt','quantity','type'], 'Recorded physical movement ledger, signed quantities.'),
  'cycle-count-variance': spec('Cycle Count Variance', ['stock_counts.VIEW'], 'reference:Count|sku:SKU|warehouse:Warehouse|status:Status|expected:Expected|counted:Counted|variance:Variance|createdAt:Created', dated, ['createdAt','variance'], 'Stored count snapshots and counted results; uncounted rows remain unknown.'),
  'stock-adjustment': spec('Stock Adjustments', ['inventory.VIEW'], 'reference:Reference|sku:SKU|warehouse:Warehouse|type:Type|quantity:Quantity|reason:Reason|createdAt:Recorded', [...productFilters,'dateFrom','dateTo'], ['createdAt','quantity','type'], 'Recorded adjustment documents, including opening stock.'),
  'transfer-discrepancy': spec('Transfer Discrepancies', ['inventory.VIEW'], 'reference:Transfer|sku:SKU|source:Source|destination:Destination|kind:Discrepancy|quantity:Units|resolved:Resolved units|createdAt:Recorded', dated, ['createdAt','quantity','kind'], 'Recorded arrival discrepancies and resolution totals, visible from either accessible endpoint.'),
  'purchase-request': spec('Purchase Requests', ['purchase_requests.VIEW'], 'reference:Request|warehouse:Warehouse|department:Department|status:Status|lineCount:Lines|createdAt:Created', dated, ['createdAt','status'], 'Purchase request documents; counts include all line items.'),
  'rfq': spec('Requests for Quotation', ['rfqs.VIEW'], 'reference:RFQ|warehouse:Warehouse|status:Status|closingDate:Closing date|quotations:Quotations|createdAt:Created', dated, ['createdAt','status','closingDate'], 'RFQ documents and current quotation counts.'),
  'supplier-comparison': spec('Supplier Comparison', ['rfqs.VIEW','suppliers.VIEW'], 'reference:Quotation|rfq:RFQ|supplier:Supplier|warehouse:Warehouse|status:Status|total:Total|deliveryDays:Delivery days|quotationDate:Quotation date', [...dated,'supplier'], ['quotationDate','total','deliveryDays'], 'One row per supplier quotation. Compare quotations within the same RFQ; totals include tax and shipping. No inferred supplier ranking.', 'quotationDate'),
  'supplier-purchases': spec('Supplier Purchases', ['purchasing.VIEW','suppliers.VIEW'], 'reference:Order|supplier:Supplier|warehouse:Warehouse|status:Status|total:Total|orderDate:Order date', [...dated,'supplier'], ['orderDate','total','status'], 'Purchase orders by order date, including current status.', 'orderDate'),
  'supplier-return': spec('Supplier Returns', ['supplier_returns.VIEW','suppliers.VIEW'], 'reference:Return|supplier:Supplier|warehouse:Warehouse|status:Status|reason:Reason|units:Units|createdAt:Created', [...dated,'supplier'], ['createdAt','status'], 'Supplier return documents and requested units; status distinguishes drafts from shipped returns.'),
  'supplier-performance': spec('Supplier Performance', ['purchasing.VIEW','suppliers.VIEW','supplier_returns.VIEW'], 'supplier:Supplier|orders:Orders|orderedUnits:Ordered units|receivedUnits:Received units|returnedUnits:Returned units|receivedValue:Received value|onTimePercent:On-time %|averageFirstReceiptDays:First receipt days|returnPercent:Return %|openOverdueOrders:Open overdue orders', [...dated,'supplier'], ['supplier','orders','receivedUnits','onTimePercent'], 'PO order-date cohort; actual receipts and shipped returns through dateTo (UTC). Undefined rates remain unknown.', 'supplier','asc'),
  'assets': spec('Assets', ['assets.VIEW'], 'tag:Asset tag|product:Product|serial:Serial|warehouse:Warehouse|status:Status|purchaseDate:Purchase date', ['warehouse','category','brand'], ['assetTag','status','purchaseDate'], 'Current asset records and current custody warehouse.', 'assetTag','asc'),
  'asset-assignment-history': spec('Asset Assignment History', ['assets.VIEW'], 'tag:Asset tag|assignedTo:Assigned to|department:Department|warehouse:Issue warehouse|status:Status|assignedDate:Assigned|returnedDate:Returned', dated, ['assignedDate','status'], 'All assignment episodes scoped by recorded issue warehouse. Historical rows without a warehouse snapshot are administrator-only.', 'assignedDate'),
  'asset-maintenance-cost': spec('Asset Maintenance Cost', ['assets.VIEW'], 'tag:Asset tag|warehouse:Service warehouse|issue:Issue|status:Status|kind:Kind|cost:Recorded cost|serviceDate:Service date|completedDate:Completed|createdAt:Created', dated, ['createdAt','cost','serviceDate'], 'Recorded cost per maintenance record; includes open work. Scope uses service warehouse snapshots; unknown historical warehouses are administrator-only.'),
  'warranties': spec('Warranty Coverage', ['assets.VIEW'], 'serial:Serial|product:Product|warehouse:Warehouse|status:Status|warrantyStart:Warranty start|warrantyEnd:Warranty end', ['warehouse','category','brand'], ['warrantyEnd','serialNumber'], 'Recorded warranty dates only. Missing coverage is unknown.', 'warrantyEnd'),
  'warranty-claims': spec('Warranty Claims', ['warranty_claims.VIEW'], 'reference:Claim|serial:Serial|product:Product|warehouse:Claim warehouse|supplier:Supplier|status:Status|outcome:Outcome|createdAt:Created', [...dated,'supplier'], ['createdAt','status'], 'Claim documents with their recorded warehouse, status and resolution outcome.')
}
export const hasPermissions = (user, permissions) => user?.role === 'Administrator' || permissions.every(key => user?.permissions?.includes(key))
export function requireReport(user, kind) {
  const value = reportCatalog[kind]
  if (!value) throw new HttpError(404, 'Report not found.')
  if (!hasPermissions(user, ['reports.VIEW', ...value.permissions])) throw new HttpError(403, 'You do not have permission for this report and its source documents.')
  return value
}
export function accessibleReports(user) { return Object.entries(reportCatalog).filter(([,value]) => hasPermissions(user, ['reports.VIEW',...value.permissions])).map(([kind,value]) => ({ kind,...value })) }
