import { errorText } from '../lib/errors.js'
import { useEffect,useState } from 'react'
import { Button,Card,PageHeader,Modal } from '../components/ui.jsx'
import ServerPagination from '../components/ServerPagination.jsx'
import { getActivityPage,getActivityDetail } from '../services/workspaceService.js'
export default function ActivityLogs(){
  const [search,setSearch]=useState(''),[module,setModule]=useState(''),[dateFrom,setDateFrom]=useState(''),[dateTo,setDateTo]=useState(''),[page,setPage]=useState(1),[result,setResult]=useState(null),[detail,setDetail]=useState(null),[id,setId]=useState(null),[error,setError]=useState(''),[detailError,setDetailError]=useState(''),[loading,setLoading]=useState(false),[retry,setRetry]=useState(0)
  useEffect(()=>{let live=true;setLoading(true);setResult(null);setError('');const timer=setTimeout(()=>getActivityPage({search,module,dateFrom,dateTo,page}).then(r=>{if(live)setResult(r)}).catch(e=>{if(live)setError(errorText(e))}).finally(()=>{if(live)setLoading(false)}),200);return()=>{live=false;clearTimeout(timer)}},[search,module,dateFrom,dateTo,page,retry])
  useEffect(()=>{setDetail(null);setDetailError('');if(!id)return;let live=true;getActivityDetail(id).then(r=>{if(live)setDetail(r.data)}).catch(e=>{if(live)setDetailError(errorText(e))});return()=>{live=false}},[id,retry])
  function change(setter,value){setter(value);setPage(1)}
  return <><PageHeader eyebrow="Management" title="Activity logs" subtitle="Review recorded changes and safe before/after values."/><Card className="p-5"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label className="text-sm font-semibold">Search<input className="field mt-2" maxLength={100} value={search} onChange={e=>change(setSearch,e.target.value)} placeholder="User, action or description"/></label><label className="text-sm font-semibold">Module<input className="field mt-2" maxLength={60} value={module} onChange={e=>change(setModule,e.target.value)} placeholder="All modules"/></label><label className="text-sm font-semibold">From (UTC)<input type="date" className="field mt-2" value={dateFrom} onChange={e=>change(setDateFrom,e.target.value)}/></label><label className="text-sm font-semibold">To (UTC)<input type="date" className="field mt-2" value={dateTo} onChange={e=>change(setDateTo,e.target.value)}/></label></div></Card>
    {error&&<div role="alert" className="my-4 text-sm text-rose-600">{error}<Button variant="secondary" size="sm" className="ml-3" onClick={()=>setRetry(v=>v+1)}>Retry</Button></div>}{loading&&<p role="status" className="my-5 text-sm subtle">Loading activity…</p>}
    {result&&<Card className="mt-5 overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-xs"><thead className="table-head"><tr>{['Recorded','User','Module','Action','Description','Changes'].map(v=><th key={v} className="px-4 py-3">{v}</th>)}</tr></thead><tbody>{result.data.length?result.data.map(row=><tr key={row.id} className="table-row border-t divider"><td className="px-4 py-3">{new Date(row.createdAt).toLocaleString()}</td><td className="px-4 py-3">{row.user?`${row.user.firstName} ${row.user.lastName}`:'System'}</td><td className="px-4 py-3">{row.module}</td><td className="px-4 py-3">{row.action}</td><td className="max-w-sm whitespace-normal px-4 py-3">{row.description}</td><td className="px-4 py-3"><Button size="sm" variant="secondary" onClick={()=>setId(row.id)}>View details</Button></td></tr>):<tr><td colSpan={6} className="py-10 text-center subtle">No activity matches these filters.</td></tr>}</tbody></table></div><ServerPagination pagination={result.pagination} page={page} onChange={setPage} disabled={loading}/></Card>}
    <Modal open={Boolean(id)} onOpenChange={v=>{if(!v)setId(null)}} title="Activity details" description={detail?.description||'Read the retained audit entry.'} width="max-w-2xl">{detailError?<div role="alert" className="space-y-3 text-sm"><p>{detailError}</p><Button variant="secondary" onClick={()=>setRetry(v=>v+1)}>Retry detail</Button></div>:!detail?<p role="status" className="text-sm subtle">Loading details…</p>:<div className="space-y-4"><p className="text-xs subtle">{detail.module} · {detail.action} · {new Date(detail.createdAt).toLocaleString()}</p>{detail.archivedAt&&<p className="text-sm text-amber-600">Archived on {new Date(detail.archivedAt).toLocaleString()}. Historical evidence remains retained and searchable.</p>}{detail.changes===null?<p className="text-sm subtle">Detailed snapshots are unavailable for this historical event or event type.</p>:!detail.changes.length?<p className="text-sm subtle">No allowlisted fields changed.</p>:<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="table-head"><tr><th className="p-3">Field</th><th className="p-3">Before</th><th className="p-3">After</th></tr></thead><tbody>{detail.changes.map(c=><tr key={c.field} className="border-t divider"><td className="p-3">{c.field}</td><td className="max-w-48 break-words p-3">{c.before===null?'None':String(c.before)}</td><td className="max-w-48 break-words p-3">{c.after===null?'None':String(c.after)}</td></tr>)}</tbody></table></div>}<p className="text-xs subtle">Credential values and arbitrary record metadata are excluded from these snapshots.</p></div>}</Modal>
  </>
}
