import { useEffect, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { useInventory } from '../context/InventoryContext.jsx'
import { Button, Card, PageHeader } from '../components/ui.jsx'
import AttachmentPanel from '../components/AttachmentPanel.jsx'
import { attachmentTypes, searchAttachmentSources } from '../services/attachmentService.js'
import { can } from '../lib/permissions.js'
export default function Attachments() {
  const {user}=useInventory(), [params,setParams]=useSearchParams(), types=attachmentTypes.filter(([, , module])=>can(user,`${module}.VIEW`)), type=params.get('entityType')||types[0]?.[0], id=params.get('entityId'), [search,setSearch]=useState(''), [page,setPage]=useState(1), [result,setResult]=useState(null), [error,setError]=useState(''), [revision,setRevision]=useState(0)
  useEffect(()=>{ let active=true;setResult(null);setError(''); if(type)searchAttachmentSources(type,{search,page}).then(v=>{if(active)setResult(v)}).catch(e=>{if(active)setError(e.message)}); return()=>{active=false} },[type,search,page,revision])
  return <><PageHeader eyebrow="Documents" title="Attachments" subtitle="Choose a record to manage its documents. Access follows the record's permissions and warehouse."/><Card className="space-y-4 p-5"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Record type<select className="field mt-2" value={type||''} onChange={e=>{setParams({entityType:e.target.value});setSearch('');setPage(1)}}>{types.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="text-sm font-semibold">Find record<input className="field mt-2" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Search name, SKU or document reference"/></label></div>{error && <div><p role="alert" className="text-sm text-rose-600">{error}</p><Button className="mt-3" variant="secondary" onClick={()=>setRevision(v=>v+1)}>Retry records</Button></div>}{!types.length&&<p role="status" className="text-sm subtle">No record types are available with your current permissions.</p>}{type&&!result&&!error&&<p role="status" className="text-sm subtle">Loading accessible records…</p>}{result && <><div className="flex flex-wrap gap-2">{result.data.map(row=><Button key={row.entityId} size="sm" variant={id===row.entityId?'primary':'secondary'} onClick={()=>setParams({entityType:type,entityId:row.entityId})}>{row.label}</Button>)}</div>{!result.data.length&&<p className="text-sm subtle">No accessible records match this search.</p>}<div className="flex flex-wrap items-center gap-2"><Button size="sm" variant="secondary" disabled={page<=1} onClick={()=>setPage(v=>v-1)}>Previous records</Button><Button size="sm" variant="secondary" disabled={page>=result.pagination.totalPages} onClick={()=>setPage(v=>v+1)}>Next records</Button><span className="text-xs subtle">{result.pagination.total} records</span></div></>}</Card>{id&&type&&<AttachmentPanel key={`${type}-${id}`} entityType={type} entityId={id}/>}</>
}
