import { useEffect, useRef, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { Button, Card, Modal, PageHeader } from '../components/ui.jsx'
import { useInventory } from '../context/InventoryContext.jsx'
import { can } from '../lib/permissions.js'
import * as api from '../services/importService.js'
import ImportCodes from '../components/ImportCodes.jsx'

const resultPath=(type,id)=>({Products:`/products/${id}`,Suppliers:`/procurement/suppliers/${id}`,Assets:`/assets/${id}`,SerialNumbers:`/serial-numbers/${id}`})[type]
export default function Imports() {
  const {user,warehouses,refreshData,notify}=useInventory(),[params,setParams]=useSearchParams(),id=params.get('batch'),selectedId=useRef(id)
  selectedId.current=id
  const types=api.importTypes.filter(t=>can(user,`${t.module}.VIEW`)),[type,setType]=useState(types.some(t=>t.type===params.get('type'))?params.get('type'):types[0]?.type||''),spec=types.find(t=>t.type===type)
  const [warehouseId,setWarehouseId]=useState(''),[file,setFile]=useState(null),[requestKey,setRequestKey]=useState(null),[inputVersion,setInputVersion]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[batch,setBatch]=useState(null),[loading,setLoading]=useState(false),[rowPage,setRowPage]=useState(1),[reload,setReload]=useState(0),[recent,setRecent]=useState(null),[recentPage,setRecentPage]=useState(1),[recentError,setRecentError]=useState(''),[confirmOpen,setConfirmOpen]=useState(false),[notes,setNotes]=useState(''),[reviewed,setReviewed]=useState(false)
  useEffect(()=>{let active=true;setRecent(null);setRecentError('');api.listImports({page:recentPage}).then(v=>{if(active)setRecent(v)}).catch(e=>{if(active)setRecentError(e.message)});return()=>{active=false}},[recentPage,reload])
  useEffect(()=>{let active=true;setBatch(null);setError('');if(!id){setLoading(false);return}setLoading(true);api.getImport(id,{page:rowPage}).then(v=>{if(active)setBatch(v.data)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[id,rowPage,reload])
  const clearFile=()=>{setFile(null);setRequestKey(null);setInputVersion(v=>v+1);setError('')}
  const permitted=spec&&can(user,'imports.CREATE')&&can(user,`${spec.module}.${spec.action}`)
  const batchSpec=api.importTypes.find(t=>t.type===batch?.type),canChange=batchSpec&&can(user,'imports.CREATE')&&can(user,`${batchSpec.module}.${batchSpec.action}`),canConfirm=canChange&&can(user,'imports.CONFIRM')
  const download=async(path,name)=>{setBusy(true);setError('');try{await api.downloadImport(path,name)}catch(e){setError(e.message)}finally{setBusy(false)}}
  const preview=async()=>{setBusy(true);setError('');try{const v=await api.previewImport(type,file,requestKey,spec.scoped?warehouseId:undefined);setRowPage(1);setParams({batch:v.data.id});setBatch(v.data);setNotes('');setReviewed(false);setFile(null);setRequestKey(null);setInputVersion(n=>n+1);setReload(n=>n+1)}catch(e){setError(e.message)}finally{setBusy(false)}}
  const action=async(kind)=>{const target=batch.id;setBusy(true);setError('');try{const v=await api.importAction(target,kind,{expectedRevision:batch.revision,...(kind==='confirm'?{notes}:{})});if(selectedId.current===target){setBatch(v.data);setRowPage(1);setReviewed(false);setConfirmOpen(false)}setReload(n=>n+1);if(kind==='confirm'){notify('Import confirmed.');try{await refreshData()}catch{notify('Import succeeded. Refresh the affected records to load the latest data.','error')}}}catch(e){setError(e.message)}finally{setBusy(false)}}
  return <><PageHeader eyebrow="Data management" title="CSV imports" subtitle="Upload, validate, review and explicitly confirm. Each batch applies all rows together."/>
    <Card className="space-y-4 p-5">
      <h2 className="font-semibold">New import</h2><p className="text-sm subtle">UTF-8 CSV · up to 100 data rows · 1 MB. Export Excel sheets as CSV before uploading. Products and suppliers are created without stock; opening stock and asset registration record inventory movements.</p>
      {!types.length?<p role="status" className="text-sm subtle">No import types are available with your current permissions.</p>:<>
        <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Import type<select className="field mt-2" value={type} disabled={busy} onChange={e=>{setType(e.target.value);setWarehouseId('');clearFile()}}>{types.map(t=><option key={t.type} value={t.type}>{t.label}</option>)}</select></label>{spec?.scoped&&<label className="text-sm font-semibold">Warehouse<select className="field mt-2" value={warehouseId} disabled={busy} onChange={e=>{setWarehouseId(e.target.value);clearFile()}}><option value="">Select warehouse</option>{warehouses.filter(w=>['ACTIVE','Active','Operational'].includes(w.status)).map(w=><option key={w.id} value={w.id}>{w.name}{w.code?` (${w.code})`:''}</option>)}</select></label>}</div>
        <p className="text-sm subtle">{spec?.help}</p><ImportCodes key={type} type={type}/><Button size="sm" variant="secondary" disabled={busy} onClick={()=>download(`templates/${type}`,`${type}-template.csv`)}>Download CSV template</Button>
        {permitted?<div className="flex flex-wrap items-end gap-3"><label className="min-w-0 flex-1 text-sm font-semibold">Choose CSV file<input key={inputVersion} type="file" accept=".csv,text/csv" disabled={busy} className="field mt-2 w-full max-w-full" onChange={e=>{setFile(e.target.files?.[0]||null);setRequestKey(crypto.randomUUID());setError('')}}/></label><Button disabled={busy||!file||(spec.scoped&&!warehouseId)} onClick={preview}>{busy?'Working…':'Create preview'}</Button></div>:<p className="text-sm subtle">Your permissions allow viewing this import type. Creation requires import and source-module write access.</p>}
      </>}
    </Card>
    {error&&<div role="alert" className="mt-4 rounded-xl border border-rose-200 p-4 text-sm text-rose-600">{error}{id&&<Button size="sm" variant="secondary" className="mt-3" disabled={busy} onClick={()=>{setReload(v=>v+1);setReviewed(false)}}>Reload preview</Button>}</div>}
    {loading&&<p role="status" className="mt-5 text-sm subtle">Loading preview…</p>}
    {batch&&<Card className="mt-5 space-y-4 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="break-all font-semibold">{batch.fileName}</h2><p className="text-sm subtle">{batchSpec?.label} · {batch.status==='IMPORTED'?'Imported':'Preview'} · Revision {batch.revision}</p></div><Button size="sm" variant="secondary" disabled={busy} onClick={()=>download(`${batch.id}/rejected.csv`,`${batch.type}-rejected.csv`)}>Download rejected rows</Button></div>
      <div className="grid gap-3 sm:grid-cols-3">{[['Rows',batch.summary.totalRows],['Valid',batch.summary.validRows],['Rejected',batch.summary.invalidRows]].map(([label,value])=><div key={label} className="rounded-xl bg-[var(--surface-muted)] p-3"><span className="text-xs subtle">{label}</span><strong className="ml-3">{value}</strong></div>)}</div>
      {batch.status==='PREVIEW'&&<p className="text-sm subtle">No business records have been imported. Preview expires {new Date(batch.expiresAt).toLocaleString()}. {batch.summary.invalidRows?'Correct rejected rows and upload a new CSV.':'Review the rows, then confirm with an import reason.'}</p>}
      <div className="space-y-3">{batch.rows.map(row=><div key={row.rowNumber} className="rounded-xl border divider p-4"><div className="flex flex-wrap justify-between gap-2 text-sm"><strong>Data row {row.rowNumber-1}</strong><span className={row.errors.length?'text-rose-600':'text-emerald-600'}>{row.errors.length?'Rejected':'Valid'}</span></div><dl className="mt-3 grid gap-2 text-xs sm:grid-cols-2 lg:grid-cols-3">{Object.entries(row.values).map(([field,value])=><div key={field} className="min-w-0"><dt className="subtle">{field}</dt><dd className="break-words font-medium">{value||'—'}</dd></div>)}</dl>{row.errors.length>0&&<ul className="mt-3 list-inside list-disc space-y-1 text-sm text-rose-600">{row.errors.map((e,i)=><li key={i}>{e}</li>)}</ul>}</div>)}</div>
      <div className="flex flex-wrap items-center gap-2"><Button size="sm" variant="secondary" disabled={busy||rowPage<=1} onClick={()=>setRowPage(v=>v-1)}>Previous rows</Button><Button size="sm" variant="secondary" disabled={busy||rowPage>=batch.pagination.totalPages} onClick={()=>setRowPage(v=>v+1)}>Next rows</Button><span className="text-xs subtle">Page {batch.pagination.page} of {batch.pagination.totalPages}</span></div>
      {batch.status==='PREVIEW'&&canChange&&<div className="flex flex-wrap gap-2"><Button variant="secondary" disabled={busy} onClick={()=>action('revalidate')}>Revalidate against current data</Button>{canConfirm&&<Button disabled={busy||batch.summary.invalidRows>0||new Date(batch.expiresAt)<=new Date()} onClick={()=>{setConfirmOpen(true);setReviewed(false)}}>Review confirmation</Button>}</div>}
      {batch.status==='IMPORTED'&&<div><h3 className="font-semibold">Import result</h3><p className="mt-1 text-sm subtle">{batch.result.length} rows applied {new Date(batch.confirmedAt).toLocaleString()}. {batch.notes}</p><div className="mt-3 flex flex-wrap gap-3">{batch.result.map(r=>resultPath(batch.type,r.id)?<Link key={r.id} className="break-all text-sm font-semibold text-brand-600 underline" to={resultPath(batch.type,r.id)}>{r.reference}</Link>:<span key={r.id} className="text-sm">{r.reference}</span>)}</div></div>}
    </Card>}
    <Card className="mt-5 space-y-3 p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Recent imports</h2><Button size="sm" variant="secondary" disabled={busy} onClick={()=>setReload(v=>v+1)}>Refresh imports</Button></div>{recentError?<p role="alert" className="text-sm text-rose-600">{recentError}</p>:!recent?<p role="status" className="text-sm subtle">Loading imports…</p>:!recent.data.length?<p className="text-sm subtle">No accessible imports yet.</p>:<><div className="flex flex-wrap gap-2">{recent.data.map(r=><Button size="sm" variant={r.id===id?'primary':'secondary'} key={r.id} disabled={busy} onClick={()=>{setRowPage(1);setParams({batch:r.id});setNotes('');setReviewed(false)}}>{r.fileName} · {r.status==='IMPORTED'?'Imported':'Preview'}</Button>)}</div><div className="flex flex-wrap gap-2"><Button size="sm" variant="secondary" disabled={busy||recentPage<=1} onClick={()=>setRecentPage(v=>v-1)}>Previous imports</Button><Button size="sm" variant="secondary" disabled={busy||recentPage>=recent.pagination.totalPages} onClick={()=>setRecentPage(v=>v+1)}>Next imports</Button><span className="self-center text-xs subtle">{recent.pagination.total} imports</span></div></>}</Card>
    <Modal open={confirmOpen} onOpenChange={value=>{if(!busy)setConfirmOpen(value)}} title="Confirm import" description={`Apply all ${batch?.summary.validRows||0} validated rows together. Source data and your access will be checked again.`} footer={<><Button variant="secondary" disabled={busy} onClick={()=>setConfirmOpen(false)}>Cancel</Button><Button disabled={busy||!reviewed||notes.trim().length<5||!batch||batch.status!=='PREVIEW'} onClick={()=>action('confirm')}>{busy?'Importing…':'Confirm import'}</Button></>}>
      <label className="block text-sm font-semibold">Import reason<textarea className="field mt-2 min-h-24" maxLength={1000} value={notes} disabled={busy} onChange={e=>setNotes(e.target.value)}/></label><label className="mt-4 flex items-start gap-2 text-sm"><input type="checkbox" checked={reviewed} disabled={busy} onChange={e=>setReviewed(e.target.checked)}/>I reviewed all rows and the stock or asset changes this import will make.</label>{error&&<p role="alert" className="mt-3 text-sm text-rose-600">{error}</p>}<Button className="mt-3" size="sm" variant="secondary" disabled={busy} onClick={()=>{setConfirmOpen(false);setReviewed(false);setReload(v=>v+1)}}>Reload preview and keep reason</Button>
    </Modal>
  </>
}
