import { errorText } from '../lib/errors.js'
import { useEffect,useState } from 'react'
import { Button,Card,PageHeader } from '../components/ui.jsx'
import { useInventory } from '../context/InventoryContext.jsx'
import { getPreferences,savePreferences } from '../services/workspaceService.js'
const notificationLabels={lowStock:'Low stock',outOfStock:'Out of stock',purchaseApproval:'Purchase order and request approvals',transferApproval:'Transfer approvals',transferReceived:'Transfer arrivals',purchaseReceived:'Purchase receipts',warrantyExpiring:'Expiring warranties',maintenanceDue:'Maintenance due',warrantyClaimUpdate:'Warranty claim updates'}
const cards={products:'Total products',units:'Inventory units',value:'Inventory value',low:'Low stock',out:'Out of stock',suppliers:'Active suppliers'}
const charts={movement:'Inventory movement',category:'Stock by category',lowStock:'Low stock products',activity:'Recent activity'}
function OrderPicker({label,options,value,onChange,disabled}){
  function move(i,delta){const next=[...value];[next[i],next[i+delta]]=[next[i+delta],next[i]];onChange(next)}
  return <fieldset><legend className="font-semibold">{label}</legend><div className="mt-3 flex flex-wrap gap-4">{Object.entries(options).map(([key,title])=><label key={key} className="flex items-center gap-2 text-sm"><input type="checkbox" disabled={disabled} checked={value.includes(key)} onChange={e=>onChange(e.target.checked?[...value,key]:value.filter(v=>v!==key))}/>{title}</label>)}</div><ol className="mt-4 space-y-2">{value.map((key,i)=><li key={key} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border divider p-3 text-sm"><span>{i+1}. {options[key]}</span><span className="flex gap-2"><Button size="sm" variant="secondary" aria-label={`Move ${options[key]} earlier`} disabled={disabled||i===0} onClick={()=>move(i,-1)}>Earlier</Button><Button size="sm" variant="secondary" aria-label={`Move ${options[key]} later`} disabled={disabled||i===value.length-1} onClick={()=>move(i,1)}>Later</Button></span></li>)}</ol></fieldset>
}
export default function Preferences(){
  const {warehouses,refreshData}=useInventory(),[form,setForm]=useState(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0)
  useEffect(()=>{let live=true;setLoading(true);getPreferences().then(r=>{if(live){setForm(r.data);setError('')}}).catch(e=>{if(live)setError(errorText(e))}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[retry])
  const dashboard=(key,value)=>setForm(v=>({...v,dashboard:{...v.dashboard,[key]:value}}))
  async function save(){setBusy(true);setError('');setMessage('');try{const r=await savePreferences({expectedRevision:form.revision,notifications:form.notifications,dashboard:form.dashboard});setForm(r.data);setMessage('Preferences saved.');await refreshData()}catch(e){setError(errorText(e))}finally{setBusy(false)}}
  return <><PageHeader eyebrow="Account" title="My preferences" subtitle="Choose in-app notifications and your dashboard layout. Preferences are saved to your account."/>
    {loading&&<p role="status" className="text-sm subtle">Loading preferences…</p>}
    {error&&<div role="alert" className="my-4 space-y-3 rounded-xl border border-rose-200 p-4 text-sm text-rose-600"><p>{error}</p><Button size="sm" variant="secondary" disabled={busy} onClick={()=>setRetry(v=>v+1)}>Reload saved preferences</Button><p className="text-xs">Reload replaces unsaved selections with the latest saved revision.</p></div>}
    {message&&<p role="status" className="my-4 text-sm text-emerald-600">{message}</p>}
    {form&&!loading&&<div className="space-y-5">{form.warehouseWarning&&<p className="text-sm text-amber-600">{form.warehouseWarning}</p>}<Card className="space-y-4 p-5"><h2 className="font-semibold">In-app notifications</h2><p className="text-sm subtle">Delivery follows your module and warehouse access. Disabled categories are hidden from your notification list; their history is retained.</p><div className="grid gap-3 sm:grid-cols-2">{Object.entries(notificationLabels).map(([key,label])=><label key={key} className="flex items-center gap-3 rounded-xl border divider p-3 text-sm"><input type="checkbox" disabled={busy} checked={form.notifications[key]} onChange={e=>setForm(v=>({...v,notifications:{...v.notifications,[key]:e.target.checked}}))}/>{label}</label>)}</div></Card>
      <Card className="space-y-6 p-5"><h2 className="font-semibold">Dashboard</h2><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Default warehouse<select className="field mt-2" disabled={busy} value={form.dashboard.defaultWarehouseId||''} onChange={e=>dashboard('defaultWarehouseId',e.target.value||null)}><option value="">All accessible warehouses</option>{form.dashboard.defaultWarehouseId&&!warehouses.some(w=>w.id===form.dashboard.defaultWarehouseId)&&<option value={form.dashboard.defaultWarehouseId}>Unavailable saved warehouse — select a replacement</option>}{warehouses.filter(w=>['ACTIVE','Active','Operational'].includes(w.status)).map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label className="text-sm font-semibold">Default date range<select className="field mt-2" disabled={busy} value={form.dashboard.defaultPeriod} onChange={e=>dashboard('defaultPeriod',e.target.value)}>{[['7d','7 days'],['30d','30 days'],['3m','3 months'],['6m','6 months'],['1y','1 year']].map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div><OrderPicker label="Visible cards and order" options={cards} value={form.dashboard.cards} disabled={busy} onChange={v=>dashboard('cards',v)}/><OrderPicker label="Visible charts and sections" options={charts} value={form.dashboard.charts} disabled={busy} onChange={v=>dashboard('charts',v)}/></Card><Button disabled={busy} onClick={save}>{busy?'Saving…':'Save preferences'}</Button>
    </div>}
  </>
}
