import { errorText } from '../lib/errors.js'
import { useEffect,useState } from 'react'
import { useInventory } from '../context/InventoryContext.jsx'
import { Button,Card,PageHeader } from '../components/ui.jsx'
import ServerPagination from '../components/ServerPagination.jsx'
import { getReportCatalog,getReportPage,getReportExportPage,getSavedReports,saveReportConfig,archiveReportConfig } from '../services/workspaceService.js'
import { downloadXlsx,downloadPdf } from '../lib/export.js'

export default function Reports(){
  const {warehouses,categories,brands,suppliers}=useInventory()
  const [catalog,setCatalog]=useState([]),[saved,setSaved]=useState([]),[kind,setKind]=useState(''),[filters,setFilters]=useState({}),[columns,setColumns]=useState([]),[sortBy,setSortBy]=useState(''),[sortOrder,setSortOrder]=useState('desc'),[name,setName]=useState(''),[savedId,setSavedId]=useState('')
  const [request,setRequest]=useState(null),[page,setPage]=useState(1),[result,setResult]=useState(null),[loading,setLoading]=useState(true),[running,setRunning]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[retry,setRetry]=useState(0)
  const spec=catalog.find(r=>r.kind===kind),config=saved.find(r=>r.id===savedId)
  function choose(r){setKind(r.kind);setFilters({});setColumns(r.columns.map(c=>c.key));setSortBy(r.defaultSort);setSortOrder(r.defaultOrder);setRequest(null);setResult(null);setPage(1);setSavedId('');setName('');setError('')}
  useEffect(()=>{let live=true;setLoading(true);setError('');Promise.all([getReportCatalog(),getSavedReports()]).then(([c,s])=>{if(!live)return;setCatalog(c.data);setSaved(s.data);if(c.data.length){const first=c.data[0];setKind(k=>k||first.kind);setColumns(v=>v.length?v:first.columns.map(col=>col.key));setSortBy(v=>v||first.defaultSort);setSortOrder(v=>kind?v:first.defaultOrder)}}).catch(e=>{if(live)setError(errorText(e))}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[retry])
  useEffect(()=>{if(!request){setRunning(false);return;}let live=true;setRunning(true);setResult(null);setError('');getReportPage(request.kind,{...request.params,page,limit:20}).then(r=>{if(live)setResult(r)}).catch(e=>{if(live)setError(errorText(e))}).finally(()=>{if(live)setRunning(false)});return()=>{live=false}},[request,page])
  function generate(){setPage(1);setRequest({kind,params:{...filters,columns:columns.join(','),sortBy,sortOrder}})}
  function apply(id){const value=saved.find(r=>r.id===id);if(!value)return;setSavedId(id);setName(value.name);setKind(value.reportType);setFilters(value.filters);setColumns(value.columns);setSortBy(value.sortBy);setSortOrder(value.sortOrder);setRequest(null);setResult(null);setPage(1);setError('')}
  async function save(asNew=false){setBusy(true);setError('');try{const r=await saveReportConfig(asNew?null:savedId,{name,reportType:kind,filters,columns,sortBy,sortOrder,expectedRevision:!asNew&&config?config.revision:0});setSavedId(r.data.id);setSaved((await getSavedReports()).data)}catch(e){setError(errorText(e))}finally{setBusy(false)}}
  async function archive(){if(!config)return;setBusy(true);setError('');try{await archiveReportConfig(config.id,config.revision);setSavedId('');setSaved((await getSavedReports()).data)}catch(e){setError(errorText(e))}finally{setBusy(false)}}
  const options={warehouse:warehouses,category:categories,brand:brands,supplier:suppliers},labels={warehouse:'Warehouse',category:'Category',brand:'Brand',supplier:'Supplier',dateFrom:'Start date (UTC)',dateTo:'End date (UTC)'}
  async function download(pdf){if(!result)return;setBusy(true);setError('');try{const fresh=await getReportExportPage(request.kind,{...result.filters,columns:result.columns.map(c=>c.key).join(','),sortBy:result.sortBy,sortOrder:result.sortOrder,page,limit:20});const headers=fresh.columns.map(c=>c.label),rows=fresh.data.map(r=>fresh.columns.map(c=>r[c.key]??'Unknown')),label=catalog.find(c=>c.kind===request.kind)?.label||request.kind;pdf?downloadPdf(`${request.kind}-page-${page}.pdf`,`${label} � page ${page}`,headers,rows):downloadXlsx(`${request.kind}-page-${page}.xlsx`,headers,rows)}catch(e){setError(errorText(e))}finally{setBusy(false)}}
  return <><PageHeader eyebrow="Reports" title="Reports & saved configurations" subtitle="Generate reports from current records within your warehouse and document permissions."/>
    {loading?<p role="status" className="text-sm subtle">Loading available reports…</p>:<Card className="space-y-5 p-5">
      <div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold">Report type<select className="field mt-2" value={kind} disabled={busy} onChange={e=>choose(catalog.find(r=>r.kind===e.target.value))}>{catalog.map(r=><option key={r.kind} value={r.kind}>{r.label}</option>)}</select></label><label className="text-sm font-semibold">Saved configuration<select className="field mt-2" value={savedId} disabled={busy} onChange={e=>e.target.value?apply(e.target.value):setSavedId('')}><option value="">Choose a saved report</option>{saved.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label></div>
      {!catalog.length?<p className="text-sm subtle">No reports are available with your current source permissions.</p>:<><p className="text-sm subtle">{spec?.basis}</p><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{spec?.filters.map(key=><label key={key} className="text-sm font-semibold">{labels[key]}{key.startsWith('date')?<input type="date" className="field mt-2" value={filters[key]||''} disabled={busy} onChange={e=>setFilters(v=>{const n={...v};e.target.value?n[key]=e.target.value:delete n[key];return n})}/>:<select className="field mt-2" value={filters[key]||''} disabled={busy} onChange={e=>setFilters(v=>{const n={...v};e.target.value?n[key]=e.target.value:delete n[key];return n})}><option value="">All accessible {labels[key].toLowerCase()}s</option>{(options[key]||[]).map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select>}</label>)}</div>
      <fieldset><legend className="text-sm font-semibold">Visible columns</legend><div className="mt-3 flex flex-wrap gap-x-5 gap-y-3">{spec?.columns.map(c=><label key={c.key} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={columns.includes(c.key)} disabled={busy} onChange={e=>setColumns(v=>e.target.checked?[...v,c.key]:v.filter(k=>k!==c.key))}/>{c.label}</label>)}</div></fieldset>
      <div className="flex flex-wrap items-end gap-3"><label className="text-sm font-semibold">Sort by<select className="field mt-2" value={sortBy} disabled={busy} onChange={e=>setSortBy(e.target.value)}>{spec?.sorts.map(k=><option key={k} value={k}>{spec.columns.find(c=>c.key===k)?.label||({assetTag:'Asset tag',serialNumber:'Serial number'}[k]||k)}</option>)}</select></label><label className="text-sm font-semibold">Order<select className="field mt-2" value={sortOrder} disabled={busy} onChange={e=>setSortOrder(e.target.value)}><option value="asc">Ascending</option><option value="desc">Descending</option></select></label><Button disabled={busy||running||!columns.length} onClick={generate}>{running?'Generating…':'Generate report'}</Button></div>
      <div className="flex flex-wrap items-end gap-3 border-t divider pt-4"><label className="min-w-0 flex-1 text-sm font-semibold">Configuration name<input className="field mt-2" maxLength={100} value={name} disabled={busy} onChange={e=>setName(e.target.value)} placeholder="My monthly warehouse report"/></label><Button disabled={busy||!name.trim()||!columns.length} onClick={()=>save()}>{config?'Update saved report':'Save configuration'}</Button>{config&&<><Button variant="secondary" disabled={busy||!name.trim()||!columns.length} onClick={()=>save(true)}>Save as new</Button><Button variant="secondary" disabled={busy} onClick={archive}>Archive configuration</Button></>}</div></>}
    </Card>}
    {error&&<div role="alert" className="mt-4 space-y-3 rounded-xl border border-rose-200 p-4 text-sm text-rose-600"><p>{error}</p><Button variant="secondary" size="sm" disabled={busy} onClick={()=>setRetry(v=>v+1)}>Reload available reports and saved revisions</Button>{request&&<Button variant="secondary" size="sm" disabled={busy||running} onClick={()=>setRequest(v=>({...v}))}>Retry report</Button>}</div>}
    {running&&<p role="status" className="mt-5 text-sm subtle">Loading report page…</p>}
    {result&&<Card className="mt-5 overflow-hidden"><div className="space-y-3 p-5"><h2 className="font-semibold">{catalog.find(r=>r.kind===request.kind)?.label}</h2><p className="text-sm subtle">{result.basis}</p><p className="text-xs subtle">Generated {new Date(result.generatedAt).toLocaleString()} · {Object.entries(result.filters).map(([k,v])=>`${labels[k]}: ${options[k]?.find(o=>o.id===v)?.name||v}`).join(' · ')||'All accessible records'} · Sort {result.sortBy} {result.sortOrder}</p><div className="flex flex-wrap gap-2"><Button size="sm" variant="secondary" disabled={busy||!result.canExport||!result.data.length} onClick={()=>download(false)}>Export this page to Excel</Button><Button size="sm" variant="secondary" disabled={busy||!result.canExport||!result.data.length} onClick={()=>download(true)}>Export this page to PDF</Button></div><p className="text-xs subtle">Exports fetch the selected page and columns again with current permissions. Export access is required. Unknown historical values are kept as unknown.</p></div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="table-head"><tr>{result.columns.map(c=><th key={c.key} className="whitespace-nowrap px-4 py-3">{c.label}</th>)}</tr></thead><tbody>{result.data.length?result.data.map((r,i)=><tr key={i} className="table-row border-t divider">{result.columns.map(c=><td key={c.key} className="min-w-24 max-w-sm px-4 py-3 whitespace-normal break-words">{r[c.key]??'Unknown'}</td>)}</tr>):<tr><td className="px-5 py-10 text-center subtle" colSpan={result.columns.length}>No records match these filters.</td></tr>}</tbody></table></div><ServerPagination pagination={result.pagination} page={page} onChange={setPage} disabled={running}/></Card>}
  </>
}
