import { useEffect,useState } from 'react'
import { Link } from 'react-router-dom'
import { Button,Card,PageHeader,Modal } from '../components/ui.jsx'
import ServerPagination from '../components/ServerPagination.jsx'
import { getSavedReports } from '../services/workspaceService.js'
import * as api from '../services/systemService.js'
import { errorText } from '../lib/errors.js'
const date=v=>v?new Date(v).toLocaleString():'Unknown'
export default function ReportSchedules(){
  const [saved,setSaved]=useState([]),[schedules,setSchedules]=useState([]),[savedId,setSavedId]=useState(''),[days,setDays]=useState(7),[edits,setEdits]=useState({}),[selected,setSelected]=useState(null),[runs,setRuns]=useState(null),[result,setResult]=useState(null),[page,setPage]=useState(1),[loading,setLoading]=useState(true),[runLoading,setRunLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[retry,setRetry]=useState(0)
  useEffect(()=>{let live=true;setLoading(true);setError('');Promise.all([getSavedReports(),api.getSchedules()]).then(([r,s])=>{if(live){setSaved(r.data);setSchedules(s.data)}}).catch(e=>{if(live)setError(errorText(e))}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[retry])
  useEffect(()=>{if(!selected)return;let live=true;setRunLoading(true);setRuns(null);api.getScheduleRuns(selected.id,page).then(r=>{if(live)setRuns(r)}).catch(e=>{if(live)setError(errorText(e))}).finally(()=>{if(live)setRunLoading(false)});return()=>{live=false}},[selected,page,retry])
  async function create(){setBusy(true);setError('');try{await api.createSchedule({savedReportId:savedId,intervalDays:Number(days)});setMessage('Schedule saved. First run occurs after the selected interval.');setSchedules((await api.getSchedules()).data)}catch(e){setError(errorText(e))}finally{setBusy(false)}}
  async function change(row,enabled){setBusy(true);setError('');try{await api.updateSchedule(row.id,{expectedRevision:row.revision,intervalDays:Number(edits[row.id]??row.intervalDays),enabled});setMessage('Schedule updated. Next occurrence starts from this update.');setSchedules((await api.getSchedules()).data)}catch(e){setError(errorText(e))}finally{setBusy(false)}}
  async function view(id){setBusy(true);setError('');try{setResult((await api.getScheduledResult(id)).data)}catch(e){setError(errorText(e))}finally{setBusy(false)}}
  return <><PageHeader eyebrow="Account reports" title="Scheduled reports" subtitle="Generate a snapshot of the first 100 rows of your saved configuration. Permissions and warehouse access are checked again at generation and viewing."/>
    {error&&<p role="alert" className="my-4 text-sm text-rose-600">{error}</p>}{message&&<p role="status" className="my-4 text-sm text-emerald-600">{message}</p>}<Button size="sm" variant="secondary" disabled={busy||loading} onClick={()=>setRetry(v=>v+1)}>Reload saved schedules</Button>{loading?<p role="status" className="mt-5">Loading schedules…</p>:<div className="mt-5 space-y-4"><Card className="space-y-4 p-5"><h2 className="font-semibold">New schedule</h2>{!saved.length?<p className="text-sm subtle">Save a configuration on the <Link className="text-brand-600" to="/reports">Reports page</Link> first.</p>:<><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Saved report<select className="field mt-2" disabled={busy} value={savedId} onChange={e=>setSavedId(e.target.value)}><option value="">Select a configuration</option>{saved.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label className="text-sm font-semibold">Every N days<input className="field mt-2" type="number" min="1" max="365" disabled={busy} value={days} onChange={e=>setDays(e.target.value)}/></label></div><Button disabled={busy||!savedId} onClick={create}>Create schedule</Button></>}</Card>{!schedules.length&&<p className="text-sm subtle">No schedules yet.</p>}{schedules.map(row=><Card key={row.id} className="space-y-3 p-5"><h2 className="font-semibold">{row.savedReport.name} · {row.enabled?'Enabled':'Paused'}</h2>{row.savedReport.archivedAt&&<p className="text-sm text-amber-600">Source configuration is archived. Due runs will report unavailable.</p>}<p className="text-sm subtle">Next occurrence: {date(row.nextRunAt)}. Missed occurrences are coalesced into one current snapshot.</p><label className="block max-w-xs text-sm">Interval (days)<input className="field mt-2" type="number" min="1" max="365" disabled={busy} value={edits[row.id]??row.intervalDays} onChange={e=>setEdits(v=>({...v,[row.id]:e.target.value}))}/></label><div className="flex flex-wrap gap-2"><Button size="sm" variant="secondary" disabled={busy} onClick={()=>change(row,row.enabled)}>Save interval</Button><Button size="sm" variant="secondary" disabled={busy} onClick={()=>change(row,!row.enabled)}>{row.enabled?'Pause':'Enable'}</Button><Button size="sm" variant="secondary" disabled={busy} onClick={()=>{setSelected(row);setPage(1);setResult(null)}}>View runs</Button></div></Card>)}</div>}
    <Modal open={Boolean(selected)} onOpenChange={v=>{if(!v&&!busy){setSelected(null);setResult(null)}}} title={selected?.savedReport.name||'Scheduled report'} description="Generated snapshots are limited to 100 rows. No email delivery is configured.">
      {runLoading&&<p role="status">Loading run history…</p>}{runs&&<div className="space-y-3">{!runs.data.length&&<p className="text-sm subtle">No runs recorded yet.</p>}{runs.data.map(run=><div key={run.id} className="rounded-xl border divider p-3 text-sm"><p>{run.status} · {date(run.generatedAt)}</p>{run.errorSummary&&<p className="mt-2 text-rose-600">{run.errorSummary}</p>}{run.status==='COMPLETE'&&<Button className="mt-2" size="sm" variant="secondary" disabled={busy} onClick={()=>view(run.id)}>Read snapshot</Button>}</div>)}<ServerPagination pagination={runs.pagination} page={page} onChange={setPage} disabled={busy}/></div>}
      {error&&<p role="alert" className="my-3 text-sm text-rose-600">{error}</p>}{result?.result&&<div className="mt-4 space-y-3"><p className="text-sm subtle">{result.result.basis}</p><p className="text-xs subtle">{result.result.data.length} of {result.result.pagination.total} records at {date(result.generatedAt)}.</p><div className="overflow-auto"><table className="w-full text-left text-xs"><thead><tr>{result.result.columns.map(c=><th key={c.key} className="whitespace-nowrap border-b divider p-2">{c.label}</th>)}</tr></thead><tbody>{result.result.data.map((row,i)=><tr key={i}>{result.result.columns.map(c=><td key={c.key} className="border-b divider p-2">{row[c.key]??'Unknown'}</td>)}</tr>)}</tbody></table></div></div>}
    </Modal></>
}
