import { useEffect,useState } from 'react'
import { NavLink,useLocation } from 'react-router-dom'
import { Button,Card,PageHeader,Modal } from '../components/ui.jsx'
import ServerPagination from '../components/ServerPagination.jsx'
import * as api from '../services/systemService.js'
import { errorText } from '../lib/errors.js'
const date=v=>v?new Date(v).toLocaleString():'Not recorded'
const bytes=v=>`${(Number(v)/1024/1024).toFixed(2)} MB`
const fields={notificationDays:'Read notification archive age (days)',activityDays:'Activity archive age (days)',backupDays:'Backup retention target (days)',sessionDays:'Expired credential cleanup age (days)'}
function Status({label,value}){return <Card className="p-4"><div className="text-xs subtle">{label}</div><div className="mt-2 break-words text-lg font-semibold">{value??'Unknown'}</div></Card>}
export default function SystemAdministration(){
  const tab=useLocation().pathname.split('/').at(-1),[health,setHealth]=useState(null),[backups,setBackups]=useState(null),[plans,setPlans]=useState([]),[policy,setPolicy]=useState(null),[openapi,setOpenapi]=useState(null),[page,setPage]=useState(1),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[retry,setRetry]=useState(0),[action,setAction]=useState(null),[target,setTarget]=useState(''),[plan,setPlan]=useState(null),[confirmation,setConfirmation]=useState(''),[command,setCommand]=useState('')
  useEffect(()=>{let live=true;setLoading(true);setError('');setMessage('');const call=tab==='backups'?Promise.all([api.getBackups(page),api.getRestorePlans()]):tab==='retention'?api.getRetention():tab==='docs'?api.getOpenApi():api.getSystemHealth()
    call.then(r=>{if(!live)return;if(tab==='backups'){setBackups(r[0]);setPlans(r[1].data)}else if(tab==='retention')setPolicy(r.data);else if(tab==='docs')setOpenapi(r.data);else setHealth(r.data)}).catch(e=>{if(live)setError(errorText(e))}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[tab,page,retry])
  async function apply(){setBusy(true);setError('');setMessage('');try{
    if(action==='create'){await api.createBackup();setAction(null);setMessage('Backup queued. Refresh to review worker progress.');const r=await api.getBackups(page);setBackups(r)}
    else if(action==='archive'){const r=await api.archiveHistory(policy.revision);setAction(null);setMessage(`Archived ${r.data.notifications} notifications and ${r.data.activityLogs} activity records. All rows and file bytes retained.`);const p=await api.getRetention();setPolicy(p.data)}
    else if(action==='save'){const body={expectedRevision:policy.revision,archiveEnabled:policy.archiveEnabled,...Object.fromEntries(Object.keys(fields).map(k=>[k,Number(policy[k])]))};const r=await api.saveRetention(body);setPolicy({...policy,...r.data});setAction(null);setMessage('Retention policy saved.')}
    else if(action?.id){if(!plan){const r=await api.planRestore(action.id,target);setPlan(r.data)}else{const r=await api.confirmRestore(plan.id,confirmation);setCommand(r.data.command);setPlans((await api.getRestorePlans()).data)}}
  }catch(e){setError(errorText(e))}finally{setBusy(false)}}
  async function verify(id){setBusy(true);setError('');try{await api.verifyBackup(id);setMessage('Backup manifest and all files verified.')}catch(e){setError(errorText(e))}finally{setBusy(false)}}
  const close=()=>{setAction(null);setPlan(null);setTarget('');setConfirmation('');setCommand('')}
  return <><PageHeader eyebrow="Administration" title={tab==='backups'?'Backups & restore':tab==='retention'?'Retention & archival':tab==='docs'?'API documentation':'System health'} subtitle="Current operational state from the backend. Administrator access required."/>
    <nav aria-label="System administration" className="my-5 flex flex-wrap gap-2">{[['health','Health'],['backups','Backups'],['retention','Retention'],['docs','API docs']].map(([key,label])=><NavLink key={key} to={'/system/'+key} className={({isActive})=>`rounded-xl border divider px-4 py-2 text-sm ${isActive?'bg-brand-50 text-brand-700':''}`}>{label}</NavLink>)}</nav>
    <Button size="sm" variant="secondary" disabled={busy||loading} onClick={()=>setRetry(v=>v+1)}>Refresh{tab==='retention'?' saved policy':''}</Button>{tab==='retention'&&<p className="mt-2 text-xs subtle">Refresh replaces unsaved policy fields.</p>}
    {error&&<p role="alert" className="my-4 text-sm text-rose-600">{error}</p>}{message&&<p role="status" className="my-4 text-sm text-emerald-600">{message}</p>}{loading&&<p role="status" className="my-5 text-sm subtle">Loading current state…</p>}
    {!loading&&tab==='health'&&health&&<div className="mt-5 space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['API',health.api],['Database',health.database],['Uptime',`${health.uptimeSeconds}s`],['App version',health.appVersion],['Node',health.nodeVersion],['Environment',health.environment],['Upload storage',health.storage.status],['Worker',health.workerEnabled?'Enabled':'Disabled']].map(([label,value])=><Status key={label} label={label} value={value}/>)}</div><Card className="space-y-3 p-5"><h2 className="font-semibold">Background jobs</h2>{!health.jobs.length&&<p className="text-sm subtle">No worker runs recorded yet.</p>}{health.jobs.map(job=><div key={job.name} className="grid gap-2 rounded-xl border divider p-3 text-sm sm:grid-cols-2"><div><strong>{job.name}</strong><p className="subtle">{job.running?'Running':job.lastError?'Failed':'Idle'}</p></div><div><p>Last run: {date(job.lastRunAt)}</p><p>Last success: {date(job.lastSuccessAt)}</p>{job.lastError&&<p className="text-rose-600">{job.lastError}</p>}</div></div>)}</Card><Status label="Last backup" value={health.lastBackup?`${health.lastBackup.status} · ${date(health.lastBackup.startedAt)}`:'No managed backup recorded'}/></div>}
    {!loading&&tab==='backups'&&backups&&<div className="mt-5 space-y-4"><Card className="space-y-3 p-5"><h2 className="font-semibold">Database and uploaded files</h2><p className="text-sm subtle">{backups.configuration.configured?'Local MySQL backup tools are configured.':'Configure MySQL tools and private backup storage on this host.'} Scheduling: {backups.configuration.schedulingMinutes?`${backups.configuration.schedulingMinutes} minutes`:'manual only'}.</p><p className="text-sm subtle">Retention dates are review targets. Backup bytes are retained; automatic deletion is disabled.</p><Button disabled={busy||!backups.configuration.configured} onClick={()=>setAction('create')}>Create backup</Button></Card>{!backups.data.length&&<Card className="p-5 text-sm">No managed backups yet. Earlier development safety schemas are separate from this registry.</Card>}{backups.data.map(row=><Card key={row.id} className="space-y-3 p-5"><div className="flex flex-wrap justify-between gap-3"><strong>{row.status} · {date(row.startedAt)}</strong><span className="break-all text-xs subtle">{row.id}</span></div><div className="grid gap-3 text-sm sm:grid-cols-3"><p>Database: {row.databaseStatus} · {bytes(row.databaseBytes)}</p><p>Uploads: {row.uploadsStatus} · {bytes(row.uploadsBytes)} · {row.fileCount} files</p><p>Retain through: {date(row.retainedUntil)}</p></div>{row.errorSummary&&<p role="alert" className="text-sm text-rose-600">{row.errorSummary}</p>}{row.status==='COMPLETE'&&<div className="flex gap-2"><Button size="sm" variant="secondary" disabled={busy} onClick={()=>verify(row.id)}>Verify files</Button><Button size="sm" variant="secondary" disabled={busy} onClick={()=>{close();setAction(row)}}>Plan restore</Button></div>}</Card>)}<ServerPagination pagination={backups.pagination} page={page} onChange={setPage} disabled={busy}/><Card className="p-5"><h2 className="font-semibold">Recent restore plans</h2>{plans.map(p=><p key={p.id} className="mt-3 break-words text-sm">{p.status} · {p.targetSchema} · {date(p.createdAt)}</p>)}{!plans.length&&<p className="mt-2 text-sm subtle">No restore plans.</p>}</Card></div>}
    {!loading&&tab==='retention'&&policy&&<Card className="mt-5 space-y-5 p-5"><h2 className="font-semibold">Preserve historical evidence</h2><p className="text-sm subtle">Archive read notifications and activity logs by age. Activity history remains viewable and archived notifications leave the active feed. Products, disposed assets, completed orders and archived attachments retain their existing history and file bytes.</p><div className="grid gap-4 sm:grid-cols-2">{Object.entries(fields).map(([key,label])=><label key={key} className="text-sm font-semibold">{label}<input className="field mt-2" type="number" min={key==='activityDays'?90:key==='notificationDays'?30:7} max={key==='activityDays'?7300:key==='sessionDays'?365:3650} disabled={busy} value={policy[key]} onChange={e=>setPolicy(v=>({...v,[key]:e.target.value}))}/></label>)}</div><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={policy.archiveEnabled} disabled={busy} onChange={e=>setPolicy(v=>({...v,archiveEnabled:e.target.checked}))}/>Enable hourly history archival</label><p className="text-sm subtle">Last saved preview: {policy.eligible.notifications} read notifications; {policy.eligible.activityLogs} activity logs eligible. Save and refresh after changing ages.</p><div className="flex flex-wrap gap-2"><Button disabled={busy} onClick={()=>setAction('save')}>Save policy</Button><Button variant="secondary" disabled={busy} onClick={()=>setAction('archive')}>Archive using saved policy</Button></div></Card>}
    {!loading&&tab==='docs'&&openapi&&<Card className="mt-5 space-y-4 p-5"><h2 className="font-semibold">OpenAPI {openapi.openapi}</h2><p className="text-sm subtle">Authenticated API definitions, response envelopes, errors and pagination. Use your current Bearer token for protected endpoints; refresh cookies remain HTTP-only.</p><Button variant="secondary" onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(openapi,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='techstock-openapi.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}>Download specification</Button><div className="space-y-3">{Object.entries(openapi.paths).map(([route,methods])=><details key={route} className="rounded-xl border divider p-3"><summary className="cursor-pointer break-words text-sm font-semibold">{Object.keys(methods).join(', ').toUpperCase()} {route}</summary><pre className="mt-3 max-h-96 overflow-auto whitespace-pre-wrap break-words text-xs">{JSON.stringify(methods,null,2)}</pre></details>)}</div></Card>}
    <Modal open={Boolean(action)} onOpenChange={value=>{if(!value&&!busy)close()}} title={action==='create'?'Create a backup':action==='archive'?'Archive historical records':action==='save'?'Save retention policy':'Prepare offline restore'} description={action==='create'?'The worker will create a database dump and copy uploaded files to private storage.':action==='archive'?'Use the saved policy to mark eligible records archived. No records or file bytes are deleted.':action==='save'?'Automatic archival starts only when enabled.':'Restore into a new database and new file directory. Confirming records a plan; an operator runs the offline command, verifies the restored copy, and controls deployment cutover.'}>
      {action?.id&&!plan&&<label className="block text-sm font-semibold">New target schema<input className="field mt-2" disabled={busy} placeholder="techstock_restore_20261001" value={target} onChange={e=>setTarget(e.target.value)}/></label>}{plan&&!command&&<><p className="break-all text-sm">Type: {plan.confirmation}</p><label className="mt-3 block text-sm">Exact confirmation<input className="field mt-2" value={confirmation} disabled={busy} onChange={e=>setConfirmation(e.target.value)}/></label></>}{command&&<div><p className="text-sm">Plan confirmed. Run this on the backend host before the 30-minute plan expiry:</p><pre className="mt-3 overflow-auto rounded-xl bg-[var(--surface-muted)] p-3 text-xs">{command}</pre><p className="mt-3 text-sm subtle">The original database and uploaded files are retained.</p></div>}{error&&<p role="alert" className="mt-3 text-sm text-rose-600">{error}</p>}<div className="mt-5 flex gap-2">{!command&&<Button disabled={busy||(plan&&confirmation!==plan.confirmation)} onClick={apply}>{busy?'Applying…':action?.id&&!plan?'Create plan':'Confirm'}</Button>}<Button variant="secondary" disabled={busy} onClick={close}>{command?'Close':'Cancel'}</Button></div>
    </Modal></>
}
