import { errorText } from '../lib/errors.js'
import { useEffect,useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Search } from 'lucide-react'
import { Modal,Button } from './ui.jsx'
import { globalSearch } from '../services/workspaceService.js'
export default function GlobalSearch({open,onOpenChange}){
  const navigate=useNavigate(),[query,setQuery]=useState(''),[result,setResult]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[retry,setRetry]=useState(0)
  useEffect(()=>{if(!open){setQuery('');setResult(null);setError('')}},[open])
  useEffect(()=>{let live=true;setResult(null);setError('');if(!open||query.trim().length<2){setLoading(false);return()=>{live=false}}setLoading(true);const timer=setTimeout(()=>globalSearch(query.trim()).then(r=>{if(live)setResult(r)}).catch(e=>{if(live)setError(errorText(e))}).finally(()=>{if(live)setLoading(false)}),250);return()=>{live=false;clearTimeout(timer)}},[query,open,retry])
  return <Modal open={open} onOpenChange={onOpenChange} title="Search TechStock" description="Search catalog records and documents within your current access." width="max-w-2xl"><label className="relative block"><Search size={18} className="absolute left-3 top-1/2 -translate-y-1/2 subtle"/><input autoFocus aria-label="Search records" value={query} maxLength={100} onChange={e=>setQuery(e.target.value)} placeholder="SKU, barcode, serial, asset tag or document number" className="field h-11 pl-10"/></label><div className="mt-4 max-h-[45vh] overflow-y-auto">{loading?<p role="status" className="py-8 text-center text-sm subtle">Searching…</p>:error?<div role="alert" className="space-y-3 py-5 text-sm"><p className="text-rose-600">{error}</p><Button size="sm" variant="secondary" onClick={()=>setRetry(v=>v+1)}>Retry search</Button></div>:!result?<p className="py-8 text-center text-sm subtle">Enter at least two characters to search.</p>:!result.data.length?<p className="py-8 text-center text-sm subtle">No accessible records match this search.</p>:result.groups.map(group=><section key={group.type} className="mt-4"><h3 className="text-xs font-bold subtle">{group.type} · {group.total} matches{group.hasMore?` · showing ${group.results.length}; refine your search for more`:''}</h3>{group.results.map(r=><button key={r.id} onClick={()=>{navigate(r.route);onOpenChange(false)}} className="mt-1 flex w-full flex-col rounded-xl px-3 py-2.5 text-left hover:bg-[var(--hover)]"><span className="break-all text-sm font-semibold">{r.title}</span><span className="text-xs subtle">{r.subtitle}</span></button>)}</section>)}</div><p className="mt-4 border-t divider pt-3 text-xs subtle">Ctrl K to open · Esc to close · Tab to move through results</p></Modal>
}
