import { useEffect,useState } from 'react'
import { Button } from './ui.jsx'
import { referenceCodes } from '../services/importService.js'
export default function ImportCodes({type}) {
  const kinds=type==='Products'?['categories','brands','suppliers']:type==='Suppliers'?[]:['products']
  const [open,setOpen]=useState(false),[kind,setKind]=useState(kinds[0]||''),[search,setSearch]=useState(''),[page,setPage]=useState(1),[result,setResult]=useState(null),[error,setError]=useState(''),[retry,setRetry]=useState(0)
  useEffect(()=>{let active=true;setResult(null);setError('');if(open&&kind)referenceCodes(type,kind,{search,page}).then(v=>{if(active)setResult(v)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[type,kind,search,page,open,retry])
  if(!kinds.length)return null
  return <div><Button size="sm" variant="secondary" aria-expanded={open} onClick={()=>setOpen(v=>!v)}>{open?'Hide reference codes':'Look up reference codes'}</Button>{open&&<div className="mt-3 space-y-3 rounded-xl border divider p-4"><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Reference directory<select className="field mt-2" value={kind} onChange={e=>{setKind(e.target.value);setPage(1);setSearch('')}}>{kinds.map(k=><option key={k} value={k}>{k[0].toUpperCase()+k.slice(1)}</option>)}</select></label><label className="text-sm font-semibold">Find name or code<input className="field mt-2" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></label></div>{error?<div><p role="alert" className="text-sm text-rose-600">{error}</p><Button size="sm" variant="secondary" onClick={()=>setRetry(v=>v+1)}>Retry reference codes</Button></div>:!result?<p role="status" className="text-sm subtle">Loading reference codes…</p>:<><dl className="grid gap-2 sm:grid-cols-2">{result.data.map(row=><div key={row.code} className="min-w-0 text-sm"><dt className="break-words font-semibold">{row.name}</dt><dd className="break-all subtle">{row.code}</dd></div>)}</dl>{!result.data.length&&<p className="text-sm subtle">No active records match this search.</p>}<div className="flex flex-wrap items-center gap-2"><Button size="sm" variant="secondary" disabled={page<=1} onClick={()=>setPage(v=>v-1)}>Previous codes</Button><Button size="sm" variant="secondary" disabled={page>=result.pagination.totalPages} onClick={()=>setPage(v=>v+1)}>Next codes</Button><span className="text-xs subtle">{result.pagination.total} records</span></div></>}</div>}</div>
}
