import { useEffect, useState } from 'react'
import { useInventory } from '../context/InventoryContext.jsx'
import { Button, LoadingSkeleton, Modal } from './ui.jsx'
import ScanInput from './ScanInput.jsx'
import { getTransfer, transferAction } from '../services/inventoryService.js'

export default function TransferScanDialog({ transfer, onClose }) {
  const { notify, refreshData } = useInventory()
  const [record, setRecord] = useState(null), [serials, setSerials] = useState({}), [error, setError] = useState(''), [pending, setPending] = useState(false), [version, setVersion] = useState(0)
  const event = transfer.status === 'Approved' ? 'ship' : 'receive'
  useEffect(() => { let active = true; setRecord(null); setError(''); getTransfer(transfer.id).then(response => { if (active) setRecord(response.data) }).catch(err => { if (active) setError(err.message) }); return () => { active = false } }, [transfer.id, version])
  const lines = record?.items.filter(item => item.product.trackSerialNumbers) || []
  const scanned = id => (serials[id] || '').split(/\r?\n/).map(value => value.trim()).filter(Boolean)
  async function submit() { setPending(true); setError(''); try { await transferAction(transfer.id, event, { items: lines.map(item => ({ id: item.id, serialNumbers: scanned(item.id) })) }); await refreshData(); notify(event === 'ship' ? 'Transfer shipped with recorded serials.' : 'Transfer received with verified serials.'); onClose() } catch (err) { setError(err.message) } finally { setPending(false) } }
  return <Modal open onOpenChange={value => { if (!pending && !value) onClose() }} title={event === 'ship' ? 'Pack & ship transfer' : 'Scan & receive transfer'} description={`${transfer.number} · ${transfer.from} → ${transfer.to}`} width="max-w-2xl" footer={<><Button variant="secondary" disabled={pending} onClick={onClose}>Cancel</Button><Button loading={pending} disabled={!record || lines.some(item => scanned(item.id).length !== item.quantity)} onClick={submit}>{event === 'ship' ? 'Ship transfer' : 'Receive transfer'}</Button></>}>
    {!record ? error ? <div role="alert"><p className="text-sm text-rose-600">{error}</p><Button variant="secondary" onClick={() => setVersion(v => v + 1)}>Retry transfer</Button></div> : <LoadingSkeleton rows={2}/> : <div className="max-h-[50vh] space-y-4 overflow-auto">{lines.length ? lines.map(item => <div key={item.id} className="rounded-xl border border-[var(--border)] p-4"><h3 className="text-sm font-semibold">{item.product.name}</h3><p className="mb-3 mt-1 text-xs subtle">{scanned(item.id).length} / {item.quantity} serials scanned</p><ScanInput serial disabled={pending} label={`Scan transfer serial for ${item.product.sku}`} onScan={value => { if (scanned(item.id).includes(value)) { setError('Serial already scanned for this transfer line.'); return } setSerials(current => ({ ...current, [item.id]: [...scanned(item.id), value].join('\n') })) }}/><textarea aria-label={`Transfer serials for ${item.product.sku}`} disabled={pending} className="field mt-2 min-h-24" value={serials[item.id] || ''} onChange={event => setSerials(current => ({ ...current, [item.id]: event.target.value }))} placeholder="One serial per unit"/>{event === 'receive' && <details className="mt-3 text-xs"><summary className="cursor-pointer font-semibold text-brand-600">Shipped serials</summary>{item.serialSelections.map(selection => <p key={selection.id} className="mt-1">{selection.serialNumber.serialNumber}</p>)}</details>}</div>) : <p className="text-sm">This transfer contains no serialized items. Confirm {event === 'ship' ? 'shipping' : 'receipt'} of {record.items.reduce((sum, item) => sum + item.quantity, 0)} units.</p>}{error && <p role="alert" className="text-sm text-rose-600">{error}</p>}</div>}
  </Modal>
}
