import { useState } from 'react'
import { useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { ArrowLeft, ArrowLeftRight, Boxes, CalendarDays, Edit3, HardDrive, Package, SlidersHorizontal, Warehouse } from 'lucide-react'
import { useInventory } from '../../context/InventoryContext.jsx'
import { peso, productStatus, shortDate } from '../../lib/format.js'
import { Badge, Button, Card, DataTable, EmptyState, InfoGrid, PageHeader, ProductCell, ProductVisual, Tabs } from '../../components/ui.jsx'
import { StockAdjustmentDialog, TransferDialog } from '../../components/InventoryDialogs.jsx'

const tabs=['Overview','Inventory','Serial Numbers','Purchasing','History','Documents']
export default function ProductDetails() { const {id}=useParams(),navigate=useNavigate(),[params,setParams]=useSearchParams(),{products,serials,orders,movements,warehouses,stockLocations}=useInventory(); const product=products.find(p=>p.id===id); const [adjustOpen,setAdjustOpen]=useState(false),[transferOpen,setTransferOpen]=useState(false); const tab=tabs.includes(params.get('tab'))?params.get('tab'):'Overview'; const setTab=t=>setParams(t==='Overview'?{}:{tab:t})
  if(!product)return <><PageHeader title="Product not found" subtitle="This product may have been removed from the demo catalog."/><Button variant="secondary" icon={ArrowLeft} onClick={()=>navigate('/products')}>Back to products</Button></>
  const productSerials=serials.filter(s=>s.productId===id), productOrders=orders.filter(o=>o.lines?.some(l=>l.productId===id)), productMovements=movements.filter(m=>m.productId===id)
  return <><div className="mb-5"><button onClick={()=>navigate('/products')} className="flex items-center gap-1.5 text-xs font-semibold subtle hover:text-brand-600"><ArrowLeft size={14}/>Back to products</button></div><Card className="overflow-hidden"><div className="flex flex-col gap-5 p-5 sm:flex-row sm:items-center sm:justify-between sm:p-6"><div className="flex min-w-0 items-center gap-4"><ProductVisual product={product} size="lg"/><div className="min-w-0"><div className="mb-1.5 flex flex-wrap items-center gap-2"><span className="text-[10px] font-bold uppercase tracking-[.12em] text-brand-600">Product profile</span><Badge>{productStatus(product)}</Badge></div><h1 className="font-display text-xl font-extrabold tracking-[-.04em] sm:text-[24px]">{product.name}</h1><div className="mt-1.5 flex flex-wrap gap-x-3 gap-y-1 text-xs subtle"><span>{product.sku}</span><span>·</span><span>{product.brand}</span><span>·</span><span>{product.category}</span></div></div></div><div className="flex flex-wrap gap-2"><Button variant="secondary" icon={Edit3} onClick={()=>navigate(`/products/${id}/edit`)}>Edit Product</Button><Button variant="secondary" icon={SlidersHorizontal} onClick={()=>setAdjustOpen(true)}>Adjust Stock</Button><Button icon={ArrowLeftRight} onClick={()=>setTransferOpen(true)}>Transfer Stock</Button></div></div><div className="px-4 sm:px-6"><Tabs items={tabs} active={tab} onChange={setTab}/></div></Card>
    <div className="mt-5">{tab==='Overview'&&<div className="grid gap-5 xl:grid-cols-[minmax(0,1.8fr)_minmax(280px,1fr)]"><Card className="p-5 sm:p-6"><h2 className="mb-6 font-display text-base font-bold">Product information</h2><InfoGrid items={[["SKU",product.sku],["Model",product.model],["Brand",product.brand],["Category",product.category],["Supplier",product.supplier],["Unit",product.unit||'pcs'],["Barcode",product.barcode],["Minimum stock",product.min],["Maximum stock",product.max],["Reorder point",product.reorder],["Purchase cost",peso(product.cost)],["Warranty period",product.warranty],["Created date",shortDate(product.created)]]}/><div className="mt-7 border-t divider pt-6"><h3 className="mb-2 text-sm font-bold">Description</h3><p className="max-w-3xl text-[13px] leading-7 subtle">{product.description||'No description has been added for this product.'}</p></div></Card><div className="space-y-5"><Card className="p-5 sm:p-6"><h2 className="font-display text-base font-bold">Stock summary</h2><div className="mt-5 grid grid-cols-3 gap-2 text-center"><div className="rounded-xl bg-brand-50 p-3 dark:bg-brand-500/10"><div className="font-display text-2xl font-extrabold text-brand-600">{product.stock}</div><div className="mt-1 text-[11px] subtle">On hand</div></div><div className="rounded-xl bg-[var(--surface-muted)] p-3"><div className="font-display text-2xl font-extrabold">{product.reserved}</div><div className="mt-1 text-[11px] subtle">Reserved</div></div><div className="rounded-xl bg-emerald-50 p-3 dark:bg-emerald-500/10"><div className="font-display text-2xl font-extrabold text-emerald-600">{Math.max(0,product.stock-product.reserved)}</div><div className="mt-1 text-[11px] subtle">Available</div></div></div><div className="mt-5 flex items-center justify-between border-t divider pt-4 text-xs"><span className="subtle">Inventory value</span><strong className="text-sm">{peso(product.stock*product.cost)}</strong></div></Card><Card className="p-5 sm:p-6"><h2 className="font-display text-base font-bold">Tracking</h2><div className="mt-4 flex items-center justify-between text-xs"><span className="flex items-center gap-2 subtle"><HardDrive size={15}/>Serial number tracking</span><Badge>{product.serialTracking?'Enabled':'Disabled'}</Badge></div><div className="mt-4 flex items-center justify-between text-xs"><span className="flex items-center gap-2 subtle"><Warehouse size={15}/>Primary warehouse</span><span className="font-semibold">{product.warehouse}</span></div></Card></div></div>}
      {tab==='Inventory'&&<Card className="p-5 sm:p-6"><h2 className="mb-4 font-display text-base font-bold">Inventory by warehouse</h2><p className="mb-5 text-xs subtle">Live demo balances for this product across warehouse locations.</p><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{warehouses.filter(w=>(stockLocations[id]?.[w.name]||0)>0||w.name===product.warehouse).map(w=>{const stock=stockLocations[id]?.[w.name]||0;const reserved=w.name===product.warehouse?Math.min(product.reserved,stock):0;return <div key={w.id} className="rounded-xl border border-[var(--border)] p-4"><div className="flex items-center gap-2 font-semibold"><Warehouse size={16} className="text-brand-600"/>{w.name}</div><div className="mt-1 text-xs subtle">{w.location}</div><div className="mt-4 grid grid-cols-3 gap-2 border-t divider pt-4 text-center text-xs"><div><strong className="block text-base">{stock}</strong><span className="subtle">Stock</span></div><div><strong className="block text-base">{reserved}</strong><span className="subtle">Reserved</span></div><div><strong className="block text-base">{Math.max(0,stock-reserved)}</strong><span className="subtle">Available</span></div></div></div>})}</div></Card>}
      {tab==='Serial Numbers'&&<DataTable rows={productSerials} columns={[{key:'serial',label:'Serial Number',render:s=><span className="font-bold text-brand-600">{s.serial}</span>},{key:'warehouse',label:'Warehouse'},{key:'po',label:'Purchase Order'},{key:'start',label:'Warranty Start',render:s=>shortDate(s.start)},{key:'end',label:'Warranty End',render:s=>shortDate(s.end)},{key:'status',label:'Status',render:s=><Badge>{s.status}</Badge>},{key:'assignedTo',label:'Assigned To'}]} emptyTitle="No serial numbers recorded" emptyDescription={product.serialTracking?'Serialized units will appear here when received against a purchase order.':'Enable serial tracking when editing this product to track individual units.'}/>}
      {tab==='Purchasing'&&<DataTable rows={productOrders} columns={[{key:'number',label:'PO Number',render:o=><button className="font-bold text-brand-600" onClick={()=>navigate(`/procurement/purchase-orders/${o.id}`)}>{o.number}</button>},{key:'supplier',label:'Supplier'},{key:'date',label:'Order Date',render:o=>shortDate(o.date)},{key:'expected',label:'Expected',render:o=>shortDate(o.expected)},{key:'status',label:'Status',render:o=><Badge>{o.status}</Badge>},{key:'amount',label:'Amount',render:o=>peso(o.amount)}]} emptyTitle="No purchase orders yet" emptyDescription="Purchase orders containing this product will appear here."/>}
      {tab==='History'&&<DataTable rows={productMovements} columns={[{key:'date',label:'Date'},{key:'reference',label:'Reference'},{key:'movement',label:'Movement',render:m=><Badge>{m.movement}</Badge>},{key:'quantity',label:'Quantity',render:m=><span className={m.quantity<0?'font-bold text-rose-600':'font-bold text-emerald-600'}>{m.quantity>0?'+':''}{m.quantity}</span>},{key:'from',label:'From'},{key:'to',label:'To'},{key:'by',label:'Processed By'},{key:'notes',label:'Notes'}]} emptyTitle="No stock history yet" emptyDescription="Adjustments and receipts for this product will appear here."/>}
      {tab==='Documents'&&<Card><EmptyState icon={Package} title="No documents attached" description="Product manuals, spec sheets, and warranty files can be added when document storage is connected."/></Card>}
    </div><StockAdjustmentDialog open={adjustOpen} onOpenChange={setAdjustOpen} productId={id}/><TransferDialog open={transferOpen} onOpenChange={setTransferOpen} productId={id}/></>
}
