import { useMemo, useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { Archive, ArrowLeftRight, Download, Edit3, Eye, FileUp, HardDrive, PackagePlus, Plus, SlidersHorizontal } from 'lucide-react'
import { useInventory } from '../../context/InventoryContext.jsx'
import Can from '../../components/Can.jsx'
import { downloadCsv, parseCsv, peso, productStatus } from '../../lib/format.js'
import { ActionMenu, Badge, Button, DataTable, Field, FilterBar, Modal, PageHeader, ProductCell, SearchInput, Select } from '../../components/ui.jsx'
import { ConfirmDialog, StockAdjustmentDialog, TransferDialog } from '../../components/InventoryDialogs.jsx'

export default function Products() {
  const navigate=useNavigate(),[params]=useSearchParams(),{products,categories,brands,suppliers,warehouses,serials,archiveProduct,importProducts,notify}=useInventory()
  const [search,setSearch]=useState(''),[filters,setFilters]=useState({category:params.get('category')||'',brand:params.get('brand')||'',supplier:'',warehouse:'',stock:'',status:''}),[action,setAction]=useState(null),[importOpen,setImportOpen]=useState(false),[csv,setCsv]=useState(null)
  const setFilter=(key,value)=>setFilters(f=>({...f,[key]:value}))
  const filtered=useMemo(()=>products.filter(p=>{const q=search.toLowerCase().trim();const matches=!q||[p.name,p.sku,p.model,...serials.filter(s=>s.productId===p.id).map(s=>s.serial)].some(v=>String(v||'').toLowerCase().includes(q));return matches&&(!filters.category||p.category===filters.category)&&(!filters.brand||p.brand===filters.brand)&&(!filters.supplier||p.supplier===filters.supplier)&&(!filters.warehouse||p.warehouse===filters.warehouse)&&(!filters.stock||productStatus(p)===filters.stock)&&(!filters.status||(filters.status==='Active'?!p.inactive:p.inactive))}),[products,search,filters,serials])
  const exportRows=()=>downloadCsv('techstock-products.csv',['Product','SKU','Category','Brand','Model','Stock','Reserved','Available','Warehouse','Cost','Status'],filtered.map(p=>[p.name,p.sku,p.category,p.brand,p.model,p.stock,p.reserved,p.stock-p.reserved,p.warehouse,p.cost,productStatus(p)]))
  const onFile=async file=>{if(!file)return;try{const records=parseCsv(await file.text());const valid=records.filter(r=>r.name&&r.sku&&r.category&&r.brand);if(!valid.length)throw new Error('No valid rows found. CSV needs name, sku, category and brand columns.');setCsv(valid)}catch(e){notify(e.message,'error')}}
  const columns=[
    {key:'name',label:'Product',render:p=><button className="text-left" onClick={()=>navigate(`/products/${p.id}`)}><ProductCell product={p}/></button>},
    {key:'sku',label:'SKU',render:p=><span className="font-medium subtle">{p.sku}</span>},
    {key:'category',label:'Category'}, {key:'brand',label:'Brand'}, {key:'model',label:'Model',render:p=><span className="subtle">{p.model}</span>},
    {key:'stock',label:'Stock',render:p=><span className="font-bold">{p.stock}</span>}, {key:'reserved',label:'Reserved'}, {key:'available',label:'Available',sortValue:p=>p.stock-p.reserved,render:p=><span className="font-semibold">{Math.max(0,p.stock-p.reserved)}</span>},
    {key:'warehouse',label:'Warehouse'}, {key:'cost',label:'Cost',render:p=>peso(p.cost)}, {key:'status',label:'Status',sortValue:productStatus,render:p=><Badge>{productStatus(p)}</Badge>},
    {key:'actions',label:'',sortable:false,render:p=><ActionMenu items={[{label:'View details',icon:Eye,onSelect:()=>navigate(`/products/${p.id}`)},{label:'Edit product',icon:Edit3,onSelect:()=>navigate(`/products/${p.id}/edit`)},{label:'Stock adjustment',icon:SlidersHorizontal,onSelect:()=>setAction({kind:'adjust',product:p})},{label:'Serial numbers',icon:HardDrive,onSelect:()=>navigate(`/products/${p.id}?tab=Serial%20Numbers`)},{label:'Transfer stock',icon:ArrowLeftRight,onSelect:()=>setAction({kind:'transfer',product:p})},{separator:true},{label:p.inactive?'Reactivate product':'Archive product',icon:Archive,danger:!p.inactive,onSelect:()=>setAction({kind:'archive',product:p})}]}/>}
  ]
  return <>
    <PageHeader eyebrow="Inventory" title="Products" subtitle="Manage all products and IT equipment stored in the inventory." actions={<><Can permission="products.CREATE"><Button variant="secondary" icon={FileUp} onClick={()=>setImportOpen(true)}>Import</Button></Can><Button variant="secondary" icon={Download} onClick={exportRows}>Export</Button><Can permission="products.CREATE"><Button icon={Plus} onClick={()=>navigate('/products/new')}>Add Product</Button></Can></>}/>
    <FilterBar onReset={()=>{setSearch('');setFilters({category:'',brand:'',supplier:'',warehouse:'',stock:'',status:''})}}><SearchInput value={search} onChange={setSearch} placeholder="Search name, SKU, model or serial..." className="w-full lg:w-[300px]"/><Select value={filters.category} onChange={v=>setFilter('category',v)} options={categories.map(c=>c.name)} placeholder="All categories" className="w-full sm:w-[155px]"/><Select value={filters.brand} onChange={v=>setFilter('brand',v)} options={brands.map(b=>b.name)} placeholder="All brands" className="w-full sm:w-[130px]"/><Select value={filters.supplier} onChange={v=>setFilter('supplier',v)} options={suppliers.map(s=>s.name)} placeholder="All suppliers" className="w-full sm:w-[150px]"/><Select value={filters.warehouse} onChange={v=>setFilter('warehouse',v)} options={warehouses.map(w=>w.name)} placeholder="All warehouses" className="w-full sm:w-[165px]"/><Select value={filters.stock} onChange={v=>setFilter('stock',v)} options={['In Stock','Low Stock','Out of Stock']} placeholder="Stock status" className="w-full sm:w-[145px]"/><Select value={filters.status} onChange={v=>setFilter('status',v)} options={['Active','Inactive']} placeholder="Product status" className="w-full sm:w-[145px]"/></FilterBar>
    <DataTable rows={filtered} columns={columns} selectable emptyTitle="No products found" emptyDescription="Adjust your filters or add your first product." emptyAction={<Button icon={Plus} onClick={()=>navigate('/products/new')}>Add Product</Button>} bulkActions={(ids,clear)=><Button size="sm" variant="secondary" icon={Download} onClick={()=>{downloadCsv('techstock-selected-products.csv',['Product','SKU','Stock'],products.filter(p=>ids.includes(p.id)).map(p=>[p.name,p.sku,p.stock]));clear()}}>Export selected</Button>}/>
    <StockAdjustmentDialog key={`adjust-${action?.product?.id||''}`} open={action?.kind==='adjust'} onOpenChange={()=>setAction(null)} productId={action?.product?.id}/>
    <TransferDialog key={`transfer-${action?.product?.id||''}`} open={action?.kind==='transfer'} onOpenChange={()=>setAction(null)} productId={action?.product?.id}/>
    <ConfirmDialog open={action?.kind==='archive'} onOpenChange={()=>setAction(null)} title={action?.product?.inactive?'Reactivate product':'Archive product'} description={`Are you sure you want to ${action?.product?.inactive?'reactivate':'archive'} ${action?.product?.name||'this product'}?`} confirmLabel={action?.product?.inactive?'Reactivate':'Archive product'} danger={!action?.product?.inactive} onConfirm={()=>archiveProduct(action.product.id)}/>
    <Modal open={importOpen} onOpenChange={setImportOpen} title="Import products" description="Upload a CSV file to add products to your catalog."><div className="space-y-4"><div className="rounded-xl border-2 border-dashed border-[var(--border)] bg-[var(--surface-muted)] p-7 text-center"><FileUp className="mx-auto mb-3 text-brand-600" size={25}/><label className="cursor-pointer text-sm font-semibold text-brand-600">Choose a CSV file<input type="file" accept=".csv,text/csv" className="sr-only" onChange={e=>onFile(e.target.files?.[0])}/></label><p className="mt-2 text-xs subtle">Required columns: name, sku, category, brand. Optional: model, stock, min, max, reorder, cost, warehouse, supplier.</p></div>{csv&&<div className="rounded-xl bg-brand-50 px-4 py-3 text-xs text-brand-700 dark:bg-brand-500/10">Ready to import {csv.length} products. First record: {csv[0].name}</div>}<div className="flex justify-end gap-2"><Button variant="secondary" onClick={()=>setImportOpen(false)}>Cancel</Button><Button disabled={!csv} onClick={()=>{importProducts(csv).then(imported=>{if(imported===csv.length){setCsv(null);setImportOpen(false)}})}}>Import products</Button></div></div></Modal>
  </>
}

