import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { Plus } from 'lucide-react'
import { useInventory } from '../../context/InventoryContext.jsx'
import { can } from '../../lib/permissions.js'
import { Badge, Button, Card, EmptyState, Field, FilterBar, InfoGrid, LoadingSkeleton, Modal, PageHeader, SearchInput, Select } from '../../components/ui.jsx'
import ServerTable from '../../components/ServerTable.jsx'
import * as api from '../../services/reservationService.js'

const statuses = ['ACTIVE', 'FULFILLED', 'RELEASED', 'EXPIRED', 'CANCELLED']
const label = status => status[0] + status.slice(1).toLowerCase()
const date = value => value ? new Date(value).toLocaleString() : '—'
const splitSerials = value => value.split(/\r?\n/).map(serial => serial.trim()).filter(Boolean)
function ErrorState({ error, retry }) { return <Card><EmptyState title={error.status === 403 ? 'Access denied' : error.status === 404 ? 'Reservation not found' : 'Unable to load reservations'} description={error.message} action={<Button variant="secondary" onClick={retry}>Try again</Button>}/></Card> }

function CreateReservation({ open, onClose }) {
  const { user, warehouses, products, notify, refreshData } = useInventory(), navigate = useNavigate()
  const [warehouseId, setWarehouse] = useState(user.defaultWarehouseId || ''), [lines, setLines] = useState([{ productId: '', quantity: '1', serialText: '' }])
  const [referenceType, setReferenceType] = useState('Project'), [referenceId, setReferenceId] = useState(''), [expiresAt, setExpiry] = useState(''), [notes, setNotes] = useState('')
  const [pending, setPending] = useState(false), [error, setError] = useState(''), [balances, setBalances] = useState(null), [balanceError, setBalanceError] = useState(null), [search, setSearch] = useState(''), [page, setPage] = useState(1), [version, setVersion] = useState(0)
  useEffect(() => { if (!open || !warehouseId) return; let active = true; setBalances(null); setBalanceError(null); api.availability({ warehouse: warehouseId, page, limit: 50, search }).then(result => { if (active) setBalances(result) }).catch(err => { if (active) setBalanceError(err) }); return () => { active = false } }, [open, warehouseId, page, search, version])
  const edit = (index, key, value) => setLines(current => current.map((line, i) => i === index ? { ...line, [key]: value } : line))
  async function create(event) {
    event.preventDefault(); setPending(true); setError('')
    try {
      const items = lines.map(line => ({ productId: line.productId, quantity: Number(line.quantity), serialNumbers: splitSerials(line.serialText) }))
      if (items.some(item => !item.productId || !Number.isSafeInteger(item.quantity) || item.quantity <= 0)) throw new Error('Choose a product and a positive whole quantity for every line.')
      const result = await api.createReservation({ warehouseId, referenceType, referenceId, notes, expiresAt: expiresAt ? new Date(expiresAt).toISOString() : null, items })
      await refreshData(); notify('Inventory reserved.'); navigate(`/inventory/reservations/${result.data.id}`)
    } catch (err) { setError(err.message) } finally { setPending(false) }
  }
  return <Modal open={open} onOpenChange={value => { if (!pending && !value) onClose() }} title="Reserve inventory" description="Stock remains on hand while the reserved quantity is held for your reference." width="max-w-3xl"><form onSubmit={create} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Warehouse" required><Select aria-label="Reservation warehouse" required disabled={pending} value={warehouseId} onChange={value => { setWarehouse(value); setPage(1); setLines([{ productId: '', quantity: '1', serialText: '' }]) }} options={warehouses.filter(w => w.status === 'Operational').map(w => ({ value: w.id, label: w.name }))} placeholder="Select warehouse"/></Field><Field label="Expiry (optional)"><input type="datetime-local" aria-label="Reservation expiry" disabled={pending} className="field" value={expiresAt} onChange={event => setExpiry(event.target.value)}/></Field><Field label="Reference type"><input aria-label="Reservation reference type" disabled={pending} className="field" maxLength={100} value={referenceType} onChange={event => setReferenceType(event.target.value)}/></Field><Field label="Reference"><input aria-label="Reservation reference" disabled={pending} className="field" maxLength={191} value={referenceId} onChange={event => setReferenceId(event.target.value)} placeholder="Project or deployment identifier"/></Field></div>
    <SearchInput value={search} onChange={value => { setSearch(value); setPage(1) }} placeholder="Search available products or SKU"/>
    {balanceError ? <div role="alert" className="text-sm text-rose-600">{balanceError.message}<Button type="button" variant="ghost" size="sm" onClick={() => setVersion(v => v + 1)}>Retry availability</Button></div> : warehouseId && !balances ? <p className="text-xs subtle">Loading warehouse availability…</p> : balances && !balances.data.length ? <p className="text-xs subtle">No matching stock records in this warehouse.</p> : null}
    <div className="max-h-[35vh] space-y-3 overflow-y-auto">{lines.map((line, index) => {
      const product = products.find(product => product.id === line.productId), options = (balances?.data || []).map(stock => ({ value: stock.productId, label: `${stock.product.name} · ${stock.availableQuantity} available` }))
      if (line.productId && !options.some(option => option.value === line.productId)) options.push({ value: line.productId, label: product?.name || line.productId })
      return <div key={index} className="rounded-xl border border-[var(--border)] p-4"><div className="flex items-end gap-3"><Field label={`Product ${index + 1}`} required className="min-w-0 flex-1"><Select aria-label={`Reservation product ${index + 1}`} required disabled={pending || !warehouseId || !balances} value={line.productId} onChange={value => { edit(index, 'productId', value); edit(index, 'serialText', '') }} options={options} placeholder="Choose stocked product"/></Field><Field label="Quantity" className="w-24"><input aria-label={`Reserve quantity ${index + 1}`} required disabled={pending} type="number" min="1" step="1" className="field" value={line.quantity} onChange={event => edit(index, 'quantity', event.target.value)}/></Field>{lines.length > 1 && <Button type="button" variant="ghost" disabled={pending} onClick={() => setLines(current => current.filter((_, i) => i !== index))}>Remove</Button>}</div>{product?.serialTracking && <Field label="Exact serials (optional)" className="mt-3"><textarea aria-label={`Reservation serials ${index + 1}`} disabled={pending} className="field min-h-20" value={line.serialText} onChange={event => edit(index, 'serialText', event.target.value)} placeholder="One serial per line. Leave blank for automatic selection."/></Field>}</div>
    })}</div>
    <div className="flex flex-wrap justify-between gap-2"><Button type="button" variant="secondary" disabled={pending || lines.length >= 100} onClick={() => setLines(current => [...current, { productId: '', quantity: '1', serialText: '' }])}>Add product</Button>{balances && <div className="flex gap-2"><Button type="button" variant="ghost" size="sm" disabled={pending || page <= 1} onClick={() => setPage(p => p - 1)}>Previous products</Button><Button type="button" variant="ghost" size="sm" disabled={pending || page >= balances.pagination.totalPages} onClick={() => setPage(p => p + 1)}>More products</Button></div>}</div>
    <Field label="Notes"><textarea aria-label="Reservation notes" disabled={pending} className="field" maxLength={4000} value={notes} onChange={event => setNotes(event.target.value)}/></Field>{error && <p role="alert" className="text-sm text-rose-600">{error}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="secondary" disabled={pending} onClick={onClose}>Cancel</Button><Button type="submit" loading={pending} disabled={!warehouseId || lines.some(line => !line.productId)}>Reserve stock</Button></div></form></Modal>
}

export function Reservations() {
  const { user, warehouses } = useInventory()
  const [query, setQuery] = useState({ page: 1, limit: 20, search: '', warehouse: '', status: '' }), [result, setResult] = useState(null), [error, setError] = useState(null), [loading, setLoading] = useState(true), [version, setVersion] = useState(0), [open, setOpen] = useState(false)
  useEffect(() => { let active = true; setLoading(true); setError(null); api.listReservations(query).then(result => { if (active) setResult(result) }).catch(err => { if (active) setError(err) }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [query, version])
  const change = (key, value) => setQuery(current => ({ ...current, [key]: value, page: 1 }))
  return <><PageHeader eyebrow="Inventory" title="Reservations" subtitle="Hold inventory for installations, projects and employee deployments." actions={can(user, 'reservations.CREATE') && <Button icon={Plus} onClick={() => setOpen(true)}>Reserve inventory</Button>}/><FilterBar><SearchInput value={query.search} onChange={value => change('search', value)} placeholder="Search reservation or reference"/><Select aria-label="Reservation warehouse filter" className="sm:w-52" value={query.warehouse} onChange={value => change('warehouse', value)} options={warehouses.map(w => ({ value: w.id, label: w.name }))} placeholder="All accessible warehouses"/><Select aria-label="Reservation status filter" className="sm:w-44" value={query.status} onChange={value => change('status', value)} options={statuses.map(value => ({ value, label: label(value) }))} placeholder="All statuses"/></FilterBar>{loading ? <LoadingSkeleton/> : error ? <ErrorState error={error} retry={() => setVersion(v => v + 1)}/> : <ServerTable rows={result.data} pagination={result.pagination} onPage={page => setQuery(current => ({ ...current, page }))} emptyTitle="No reservations found" emptyDescription="Reserve available stock when inventory is needed for a project or deployment." columns={[
    { key: 'reservationNumber', label: 'Reservation', render: row => <Link className="font-semibold text-brand-600" to={`/inventory/reservations/${row.id}`}>{row.reservationNumber}</Link> }, { key: 'warehouse', label: 'Warehouse', render: row => row.warehouse.name }, { key: 'referenceId', label: 'Reference' }, { key: 'status', label: 'Status', render: row => <Badge>{label(row.status)}</Badge> }, { key: 'items', label: 'Lines', render: row => row._count.items }, { key: 'expiresAt', label: 'Expires', render: row => date(row.expiresAt) }
  ]}/>}{open && <CreateReservation open onClose={() => setOpen(false)}/>}</>
}

export function ReservationDetail() {
  const { id } = useParams(), { user, notify, refreshData } = useInventory()
  const [record, setRecord] = useState(null), [result, setResult] = useState(null), [query, setQuery] = useState({ page: 1, limit: 20 }), [version, setVersion] = useState(0), [loading, setLoading] = useState(true), [error, setError] = useState(null)
  const [pending, setPending] = useState(false), [actionError, setActionError] = useState(''), [confirm, setConfirm] = useState(''), [selected, setSelected] = useState(null), [quantity, setQuantity] = useState(''), [serialText, setSerialText] = useState('')
  useEffect(() => { let active = true; setLoading(true); setError(null); Promise.all([api.getReservation(id), api.getReservationItems(id, query)]).then(([metadata, items]) => { if (active) { setRecord(metadata.data); setResult(items) } }).catch(err => { if (active) setError(err) }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [id, query, version])
  async function action() {
    setPending(true); setActionError('')
    try {
      if (confirm === 'fulfill') {
        const amount = Number(quantity)
        if (!Number.isSafeInteger(amount) || amount <= 0) throw new Error('Enter a positive whole quantity.')
        await api.fulfillReservation(id, [{ id: selected.id, quantity: amount, expectedFulfilledQuantity: selected.fulfilledQuantity, serialNumbers: splitSerials(serialText) }])
      } else await api.closeReservation(id, confirm)
      await refreshData(); notify(confirm === 'fulfill' ? 'Reserved stock issued.' : 'Remaining holds released.'); setConfirm(''); setVersion(v => v + 1)
    } catch (err) { setActionError(err.message) } finally { setPending(false) }
  }
  if (loading) return <LoadingSkeleton/>
  if (error) return <ErrorState error={error} retry={() => setVersion(v => v + 1)}/>
  const active = record.status === 'ACTIVE', expired = record.expiresAt && new Date(record.expiresAt) <= new Date()
  return <><PageHeader eyebrow="Inventory / Reservations" title={record.reservationNumber} subtitle={`${record.warehouse.name} · ${label(record.status)}`} actions={active && can(user, 'reservations.RELEASE') && <><Button variant="secondary" disabled={pending} onClick={() => { setActionError(''); setConfirm('release') }}>Release remaining</Button><Button variant="secondary" disabled={pending} onClick={() => { setActionError(''); setConfirm('cancel') }}>Cancel reservation</Button></>}/><Card className="mb-5 p-5"><InfoGrid items={[["Reference type", record.referenceType], ["Reference", record.referenceId], ["Requested by", `${record.requestedBy.firstName} ${record.requestedBy.lastName}`], ["Expires", date(record.expiresAt)], ["Closed", date(record.closedAt)], ["Notes", record.notes]]}/></Card>{active && expired && <p className="mb-4 text-sm text-amber-600">Expiry has passed. Fulfillment is blocked; the worker releases the remaining hold automatically. <button className="font-semibold underline" onClick={() => setVersion(v => v + 1)}>Refresh</button></p>}
    <ServerTable rows={result.data} pagination={result.pagination} onPage={page => setQuery(current => ({ ...current, page }))} disabled={pending} emptyTitle="No reservation lines" columns={[
      { key: 'product', label: 'Product', render: item => <div><strong>{item.product.name}</strong><p className="mt-1 text-xs subtle">{item.product.sku}</p></div> }, { key: 'quantity', label: 'Reserved' }, { key: 'fulfilledQuantity', label: 'Issued' }, { key: 'remaining', label: 'Remaining', render: item => active ? item.quantity - item.fulfilledQuantity : 0 },
      { key: 'serials', label: 'Selected serials', render: item => item.serials.length ? <details><summary className="cursor-pointer text-xs font-semibold text-brand-600">{item.serials.length} serials</summary><div className="mt-2 max-h-36 overflow-auto text-xs">{item.serials.map(selection => <p className="mt-1" key={selection.id}>{selection.serial.serialNumber} · {selection.fulfilledAt ? 'Issued' : active ? 'Held' : 'Released'}</p>)}</div></details> : '—' },
      { key: 'action', label: '', render: item => active && !expired && item.fulfilledQuantity < item.quantity && can(user, 'reservations.FULFILL') && <Button variant="secondary" size="sm" disabled={pending} onClick={() => { setSelected(item); setQuantity(String(item.quantity - item.fulfilledQuantity)); setSerialText(''); setActionError(''); setConfirm('fulfill') }}>Issue stock</Button> }
    ]}/>
    <Modal open={Boolean(confirm)} onOpenChange={value => { if (!pending && !value) setConfirm('') }} title={confirm === 'fulfill' ? 'Issue reserved stock' : confirm === 'cancel' ? 'Cancel reservation' : 'Release remaining inventory'} description={confirm === 'fulfill' ? 'Issued units leave warehouse inventory and are recorded in movement history.' : 'Only the unfulfilled hold is released. Previously issued units remain recorded.'} footer={<><Button variant="secondary" disabled={pending} onClick={() => setConfirm('')}>Back</Button><Button loading={pending} onClick={action}>{confirm === 'fulfill' ? 'Issue stock' : 'Release hold'}</Button></>}>
      {confirm === 'fulfill' && selected ? <div className="space-y-4"><p className="text-sm font-semibold">{selected.product.name}</p><Field label={`Quantity (up to ${selected.quantity - selected.fulfilledQuantity})`}><input aria-label="Issue quantity" type="number" min="1" max={selected.quantity - selected.fulfilledQuantity} step="1" disabled={pending} className="field" value={quantity} onChange={event => setQuantity(event.target.value)}/></Field>{selected.product.trackSerialNumbers && <Field label="Exact serials (optional)"><textarea aria-label="Issue serials" disabled={pending} className="field min-h-24" value={serialText} onChange={event => setSerialText(event.target.value)} placeholder="One reserved serial per line; leave blank to use remaining selected serials."/></Field>}</div> : <p className="text-sm">{record.reservationNumber}</p>}{actionError && <p role="alert" className="mt-3 text-sm text-rose-600">{actionError}</p>}
    </Modal>
  </>
}
