import { useEffect, useRef, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { createPortal } from 'react-dom'
import { Printer, ScanLine } from 'lucide-react'
import { useInventory } from '../../context/InventoryContext.jsx'
import { can } from '../../lib/permissions.js'
import { Button, Card, EmptyState, Field, LoadingSkeleton, PageHeader, Select } from '../../components/ui.jsx'
import ScanInput from '../../components/ScanInput.jsx'
import InventoryLabel from '../../components/InventoryLabel.jsx'
import * as api from '../../services/barcodeService.js'
import './labels.css'

export function Scanner() {
  const [result, setResult] = useState(null), [error, setError] = useState(''), [loading, setLoading] = useState(false), [code, setCode] = useState('')
  const latest = useRef(0)
  async function scan(value) { const request = ++latest.current; setCode(value); setLoading(true); setError(''); try { const response = await api.lookup(value); if (request === latest.current) setResult(response.data) } catch (err) { if (request === latest.current) setError(err.message) } finally { if (request === latest.current) setLoading(false) } }
  return <><PageHeader eyebrow="Inventory" title="Scan & Labels" subtitle="Scan a barcode or QR identifier with a USB scanner, or enter it manually."/><Card className="mb-5 p-5"><ScanInput global disabled={loading} onScan={scan} label="Scan or enter barcode, SKU, serial or asset tag"/><p className="mt-3 text-xs subtle">Scanners send the identifier and Enter. Normal text fields keep their usual behavior.</p></Card>{loading ? <LoadingSkeleton rows={3}/> : error ? <Card><EmptyState title="Lookup unavailable" description={error} action={<Button onClick={() => scan(code)}>Retry lookup</Button>}/></Card> : result ? result.length ? <div className="grid gap-4 sm:grid-cols-2">{result.map(item => <Card key={`${item.type}-${item.id}`} className="p-5"><div className="text-xs uppercase subtle">{item.type}</div><h2 className="mt-2 font-semibold">{item.title}</h2><p className="mt-1 break-all text-sm subtle">{item.identifier}</p>{item.status && <p className="mt-2 text-xs">Status: {item.status.toLowerCase().replaceAll('_', ' ')}</p>}<div className="mt-4 flex gap-3">{item.route && <Link className="text-sm font-semibold text-brand-600" to={item.route}>Open record</Link>}<Link className="text-sm font-semibold text-brand-600" to={`/inventory/labels?type=${item.type}&id=${item.id}`}>Print label</Link></div></Card>)}</div> : <Card><EmptyState icon={ScanLine} title="No accessible match" description={`No record matches “${code}” within your permissions and warehouse access.`}/></Card> : <Card><EmptyState icon={ScanLine} title="Ready to scan" description="Product, serial, asset and warehouse identifiers are resolved by the backend."/></Card>}</>
}

export function LabelPrinter() {
  const [params] = useSearchParams(), { user, notify, refreshData } = useInventory()
  const type = params.get('type') || 'product', id = params.get('id') || ''
  const [data, setData] = useState(null), [error, setError] = useState(''), [loading, setLoading] = useState(true), [mode, setMode] = useState('qr'), [format, setFormat] = useState('40x30'), [copies, setCopies] = useState(1), [pending, setPending] = useState(false), [version, setVersion] = useState(0), [readyLabels, setReadyLabels] = useState({})
  const labelKey = data ? `${mode}:${data.qrValue}:${data.identifier}` : ''
  const allReady = data && Array.from({ length: copies }, (_, index) => readyLabels[`${labelKey}:${index}`]).every(Boolean)
  useEffect(() => { if (!id) { setLoading(false); return } let active = true; setLoading(true); setError(''); api.labelData(type, id).then(response => { if (active) setData(response.data) }).catch(err => { if (active) setError(err.message) }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [type, id, version])
  async function generate() { setPending(true); setError(''); try { await api.generateProductBarcode(id); await refreshData(); notify('Product barcode ready.'); setVersion(v => v + 1) } catch (err) { setError(err.message) } finally { setPending(false) } }
  if (!id) return <Card><EmptyState title="Choose a record to label" description="Scan an identifier and select Print label from its result." action={<Link className="font-semibold text-brand-600" to="/inventory/scanner">Open scanner</Link>}/></Card>
  return <><div className="print-hidden"><PageHeader eyebrow="Inventory" title="Print Inventory Labels" subtitle="Labels contain identifiers only. Keep print scaling at 100%." actions={<Button icon={Printer} disabled={loading || Boolean(error) || !data || !allReady || pending || (mode === 'barcode' && !/^[\x20-\x7E]{1,40}$/.test(data.identifier))} onClick={() => window.print()}>Print labels</Button>}/><Card className="mb-5 p-5"><div className="flex flex-wrap items-end gap-4"><Field label="Encoding"><Select aria-label="Label encoding" value={mode} onChange={value => value && setMode(value)} options={[{ value: 'qr', label: 'QR code' }, { value: 'barcode', label: 'Code 128 barcode' }]}/></Field><Field label="Layout"><Select aria-label="Label layout" value={format} onChange={value => value && setFormat(value)} options={[{ value: '40x30', label: '40 × 30 mm' }, { value: '50x25', label: '50 × 25 mm' }, { value: 'a4', label: 'A4 label sheet (50 × 25 mm)' }]}/></Field><Field label="Copies"><input aria-label="Label copies" type="number" min="1" max="100" className="field w-24" value={copies} onChange={event => setCopies(Math.max(1, Math.min(100, Math.trunc(Number(event.target.value)) || 1)))}/></Field>{type === 'product' && can(user, 'products.EDIT') && <Button loading={pending} variant="secondary" onClick={generate}>Generate product barcode</Button>}</div><p className="mt-3 text-xs subtle">Use QR for long or non-ASCII identifiers. Test a printed label with your scanner before printing a batch.</p></Card>{error && <Card><EmptyState title="Label unavailable" description={error} action={<Button onClick={() => setVersion(v => v + 1)}>Retry label</Button>}/></Card>}{loading && <LoadingSkeleton rows={2}/>}</div>
    {data && !loading && !error && <><style>{`@media print { @page { size: ${format === 'a4' ? 'A4' : format === '40x30' ? '40mm 30mm' : '50mm 25mm'}; margin: ${format === 'a4' ? '10mm' : '0'}; } }`}</style><div className={`label-sheet label-${format}`}>{Array.from({ length: copies }, (_, index) => <InventoryLabel key={index} data={data} mode={mode}/>)}</div>{createPortal(<div className="inventory-print-root"><div className={`label-sheet label-${format}`}>{Array.from({ length: copies }, (_, index) => <InventoryLabel key={`${labelKey}:${index}`} data={data} mode={mode} onReady={() => setReadyLabels(previous => previous[`${labelKey}:${index}`] ? previous : { ...previous, [`${labelKey}:${index}`]: true })}/>)}</div></div>, document.body)}</>}
  </>
}
