import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { Clock3, Printer } from 'lucide-react'
import { useInventory } from '../../context/InventoryContext.jsx'
import { can } from '../../lib/permissions.js'
import { shortDate } from '../../lib/format.js'
import { Badge, Button, Card, EmptyState, LoadingSkeleton, PageHeader } from '../../components/ui.jsx'
import * as api from '../../services/serialLifecycleService.js'

const title = value => value?.toLowerCase().replaceAll('_', ' ').replace(/^./, character => character.toUpperCase())
const eventTitles = { HISTORY_STARTED: 'History recording started', RECEIVED: 'Received from supplier', TRANSFER_SHIPPED: 'Transfer shipped', TRANSFER_RECEIVED: 'Transfer received', ASSET_CREATED: 'Registered as company asset', COUNT_MISSING: 'Missing in physical count', COUNT_DISCOVERED: 'Discovered in physical count', COUNT_RECOVERED: 'Recovered in physical count', RESERVATION_EXPIRED: 'Reservation expired' }
function Fact({ label, children }) { return <div><dt className="text-xs subtle">{label}</dt><dd className="mt-1 break-words text-sm font-medium">{children || '—'}</dd></div> }

export default function SerialLifecycle() {
  const { id } = useParams(), { user } = useInventory()
  const [record, setRecord] = useState(null), [events, setEvents] = useState([]), [page, setPage] = useState(1), [pagination, setPagination] = useState(null)
  const [loading, setLoading] = useState(true), [error, setError] = useState(''), [version, setVersion] = useState(0)
  useEffect(() => { let active = true; setLoading(true); setError('')
    Promise.all([api.getSerial(id), api.getEvents(id, { page, limit: 20 })]).then(([detail, history]) => { if (active) { setRecord(detail.data); setEvents(history.data); setPagination(history.pagination) } }).catch(err => { if (active) setError(err.message) }).finally(() => { if (active) setLoading(false) })
    return () => { active = false }
  }, [id, page, version])
  if (loading) return <LoadingSkeleton rows={6}/>
  if (error) return <Card><EmptyState title="Serial history unavailable" description={error} action={<Button onClick={() => setVersion(value => value + 1)}>Retry</Button>}/></Card>
  if (!record) return null
  const asset = record.asset, assignee = asset?.assignments[0]
  return <><PageHeader eyebrow="Inventory · Serial lifecycle" title={record.serialNumber} subtitle={`${record.product.name} · ${record.product.sku}`} actions={<Link className="inline-flex items-center gap-2 rounded-lg bg-brand-600 px-4 py-2 text-sm font-semibold text-white" to={`/inventory/labels?type=serial&id=${id}`}><Printer size={16}/>Print label</Link>}/>
    <div className="mb-5 grid gap-5 lg:grid-cols-2"><Card className="p-5"><div className="mb-5 flex items-center justify-between"><h2 className="font-semibold">Current record</h2><Badge>{title(record.status)}</Badge></div><dl className="grid grid-cols-2 gap-5"><Fact label="Product">{can(user, 'products.VIEW') ? <Link className="text-brand-600" to={`/products/${record.product.id}`}>{record.product.name}</Link> : record.product.name}</Fact><Fact label="SKU">{record.product.sku}</Fact><Fact label="Warehouse">{record.warehouse?.name || asset?.warehouse?.name}</Fact><Fact label="Supplier">{record.supplier?.companyName}</Fact><Fact label="Purchase order">{record.purchaseOrder && <Link className="text-brand-600" to={`/procurement/purchase-orders/${record.purchaseOrder.id}`}>{record.purchaseOrder.poNumber}</Link>}</Fact><Fact label="Receipt">{record.receipt?.receiptNumber}</Fact><Fact label="Warranty starts">{shortDate(record.warrantyStart)}</Fact><Fact label="Warranty ends">{shortDate(record.warrantyEnd)}</Fact><Fact label="Registered">{shortDate(record.registeredAt)}</Fact><Fact label="Received">{shortDate(record.receipt?.receivedAt)}</Fact></dl></Card>
      <Card className="p-5"><h2 className="mb-5 font-semibold">Asset & custody</h2>{asset ? <dl className="grid grid-cols-2 gap-5"><Fact label="Current asset"><Link className="text-brand-600" to={`/assets?search=${encodeURIComponent(asset.assetTag)}`}>{asset.assetTag}</Link></Fact><Fact label="Asset status">{title(asset.status)}</Fact><Fact label="Current assignee">{assignee?.assignedTo}</Fact><Fact label="Department">{assignee?.department}</Fact><Fact label="Location">{assignee?.location}</Fact><Fact label="Assigned">{shortDate(assignee?.assignedDate)}</Fact></dl> : <p className="text-sm subtle">No current asset is available within your permissions.</p>}<p className="mt-6 text-xs leading-relaxed subtle">{record.historyNotice}</p>{!record.receipt && <p className="mt-3 text-xs subtle">No exact receipt link is available. A purchase order link alone does not identify a partial receipt.</p>}</Card></div>
    <Card className="overflow-hidden"><div className="flex items-center gap-2 border-b divider p-5"><Clock3 size={18}/><h2 className="font-semibold">Lifecycle timeline</h2><span className="ml-auto text-xs subtle">{pagination.total} recorded events</span></div>{events.length ? <ol className="divide-y divider">{events.map(event => <li key={event.id} className="grid gap-3 p-5 sm:grid-cols-[160px_1fr]"><time className="text-xs subtle" dateTime={event.occurredAt}>{new Date(event.occurredAt).toLocaleString('en-PH')}</time><div><h3 className="text-sm font-semibold">{eventTitles[event.type] || title(event.type)}</h3>{(event.fromStatus || event.toStatus) && <p className="mt-1 text-xs subtle">{event.fromStatus ? `${title(event.fromStatus)} → ` : ''}{title(event.toStatus) || 'Recorded'}</p>}{event.referenceNumber && <p className="mt-2 text-xs font-medium">{event.referenceNumber}</p>}{event.warehouse && <p className="mt-1 text-xs subtle">{event.warehouse.name}{event.relatedWarehouse ? ` · ${event.relatedWarehouse.name}` : ''}</p>}{event.notes && <p className="mt-2 whitespace-pre-wrap text-sm">{event.notes}</p>}<p className="mt-2 text-xs subtle">{event.user ? `${event.user.firstName} ${event.user.lastName}` : 'System'}</p></div></li>)}</ol> : <EmptyState title="No accessible lifecycle events" description="Events are recorded when this unit is handled through inventory, procurement or asset workflows."/>}<div className="flex items-center justify-between border-t divider p-4"><span className="text-xs subtle">Page {pagination.page} of {Math.max(1, pagination.totalPages)}</span><div className="flex gap-2"><Button size="sm" variant="secondary" disabled={page <= 1} onClick={() => setPage(value => value - 1)}>Previous</Button><Button size="sm" variant="secondary" disabled={page >= pagination.totalPages} onClick={() => setPage(value => value + 1)}>Next</Button></div></div></Card>
  </>
}
